import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import mongoose from 'mongoose';
import request from 'supertest';

const base = process.env.CLASSIC_MART_LIVE_BASE_URL;
const uri = process.env.CLASSIC_MART_LIVE_TEST_MONGO_URI;
const csrf = html => html.match(/(?:name="_csrf"[^>]*value|name="csrf-token" content)="([^"]+)"/)[1];

test('customer dashboard data, addresses and notifications persist and isolate accounts', { skip: !base || !uri }, async () => {
  const target = new URL(uri);
  assert.equal(target.hostname, '127.0.0.1');
  assert.match(target.pathname, /verification|test/i);
  await mongoose.connect(uri);
  try {
    const db = mongoose.connection.db;
    async function signup(name) {
      const suffix = crypto.randomBytes(6).toString('hex');
      const email = `customer-${suffix}@example.com`;
      const agent = request.agent(base);
      const form = await agent.get('/signup').expect(200);
      const password = `Customer-${suffix}A1!`;
      const phone = '+2567' + crypto.randomInt(10000000, 99999999);
      await agent.post('/signup').type('form').send({ name, email, phone, password, confirmPassword: password, acceptTerms: 'on', _csrf: csrf(form.text) }).expect(302);
      const user = await db.collection('users').findOne({ emailNormalized: email });
      return { agent, user, phone, password, email };
    }
    const { agent, user, phone, password, email } = await signup('Customer One');
    const { agent: other } = await signup('Customer Two');
    for (const page of ['dashboard', 'orders', 'wishlist', 'addresses', 'rewards', 'wallet', 'returns', 'support', 'profile', 'categories', 'cart', 'notifications', 'club']) {
      const response = await agent.get(page === 'dashboard' ? '/dashboard' : '/' + page).expect(200);
      assert.doesNotMatch(response.text, /CM12345|Awan Mabur|Welcome back, Awan|roleSwitcher/);
      assert.match(response.text, /Hi, Customer/);
      assert.doesNotMatch(response.text, /src="\/approved-dashboard\/(script|role-workspaces|enhancements)\.js/);
      assert.match(response.text, /src="\/approved-dashboard\/customer-live\.js/);
    }
    for (const id of ['dashboard','orders','wishlist','addresses','rewards','wallet','returns','support','profile','categories','cart','notifications','club']) {
      const canonical=id==='dashboard'?'/dashboard':'/'+id;
      await agent.get('/dashboard/'+id+'?review=1').expect(308).expect('location',canonical+'?review=1');
      const secured=await agent.get(canonical).expect(200);
      assert.match(secured.headers['cache-control'],/private/);
      assert.match(secured.headers['cache-control'],/no-store/);
      assert.equal(secured.headers['x-robots-tag'],'noindex, nofollow, noarchive');
    }
    const anonymous=request(base);
    for(const path of ['/orders','/addresses','/wallet','/notifications']) await anonymous.get(path).expect(302).expect('location','/login?next='+encodeURIComponent(path));
    for(const path of ['/categories','/cart','/returns','/return-policy']) await anonymous.get(path).expect(200);
    const home=await agent.get('/').expect(200);
    assert.match(home.headers['cache-control'],/private/);
    const signupForm=await anonymous.get('/signup').expect(200);
    assert.match(signupForm.headers['cache-control'],/no-store/);
    await agent.post('/addresses').type('form').send({fullName:'CSRF Test'}).expect(403);
    let page = await agent.get('/addresses').expect(200);
    const address = { fullName: 'Customer One', label: 'Home', phone: '+256700000001', address: 'First Test Street', city: 'Kampala', country: 'UG', _csrf: csrf(page.text) };
    await agent.post('/addresses').type('form').send(address).expect(302);
    const stored = await db.collection('customeraddresses').findOne({ userId: user._id });
    assert.equal(stored.isDefault, true);
    page = await agent.get('/addresses').expect(200);
    assert.match(page.text, /First Test Street/);
    const otherPage = await other.get('/addresses').expect(200);
    assert.doesNotMatch(otherPage.text, /First Test Street/);
    await other.post('/addresses/' + stored.publicId).type('form').send({ ...address, _csrf: csrf(otherPage.text) }).expect(404);
    await agent.post('/addresses/' + stored.publicId).type('form').send({ ...address, address: 'Updated Test Street', _csrf: csrf(page.text) }).expect(302);
    assert.equal((await db.collection('customeraddresses').findOne({ _id: stored._id })).address, 'Updated Test Street');
    const notificationId = 'ntf_' + crypto.randomBytes(10).toString('hex');
    await db.collection('notifications').insertOne({ publicId: notificationId, userId: user._id, country: 'UG', type: 'account', title: 'Account scoped notification', body: '<script>alert(1)</script>', importance: 'normal', createdAt: new Date(), href: 'javascript:alert(1)' });
    const notifications = await agent.get('/notifications').expect(200);
    assert.match(notifications.text, /Account scoped notification/);
    assert.doesNotMatch(notifications.text, /<script>alert\(1\)<\/script>|href="javascript:/);
    const foreign = await other.get('/notifications').expect(200);
    assert.doesNotMatch(foreign.text, /Account scoped notification/);
    await other.post('/notifications/' + notificationId + '/read').type('form').send({ _csrf: csrf(foreign.text) }).expect(404);
    await agent.post('/notifications/' + notificationId + '/read').type('form').send({ _csrf: csrf(notifications.text) }).expect(302);
    assert.ok((await db.collection('notifications').findOne({ publicId: notificationId })).readAt);
    const preferencesPage = await agent.get('/notifications').expect(200);
    await agent.post('/notifications/preferences').type('form').send({orders:'on',offers:'on',_csrf:csrf(preferencesPage.text)}).expect(302);
    assert.deepEqual((await db.collection('users').findOne({_id:user._id})).preferences.notifications,{orders:true,wishlist:false,offers:true,club:false});
    const support = await agent.get('/support').expect(200);
    await agent.post('/account/support').type('form').send({ category:'account', subject:'Account persistence test', message:'Please confirm my account settings are saved correctly.', priority:'normal', returnTo:'/support', _csrf:csrf(support.text) }).expect(302).expect('location','/support');
    const ticket = await db.collection('supporttickets').findOne({ userId:user._id, subject:'Account persistence test' });
    assert.ok(ticket);
    assert.match((await agent.get('/support').expect(200)).text,/Account persistence test/);
    assert.doesNotMatch((await other.get('/support').expect(200)).text,/Account persistence test/);
    await db.collection('supporttickets').updateOne({_id:ticket._id},{$set:{status:'resolved',resolvedAt:new Date()},$push:{notes:{$each:[{message:'Public support response',internal:false,at:new Date()},{message:'INTERNAL_ONLY_SECRET_NOTE',internal:true,at:new Date()}]}}});
    const resolved = await agent.get('/support').expect(200);
    assert.match(resolved.text,/Public support response/);
    assert.doesNotMatch(resolved.text,/INTERNAL_ONLY_SECRET_NOTE/);
    await other.post('/account/support/'+ticket.publicId+'/reopen').type('form').send({message:'I still need help',returnTo:'/support',_csrf:csrf((await other.get('/support')).text)}).expect(404);
    await agent.post('/account/support/'+ticket.publicId+'/csat').type('form').send({rating:'5',comment:'Resolved correctly',returnTo:'/support',_csrf:csrf(resolved.text)}).expect(302);
    assert.equal((await db.collection('satisfactionsurveys').findOne({ticketId:ticket._id,userId:user._id})).rating,5);
    await agent.post('/account/support/'+ticket.publicId+'/reopen').type('form').send({message:'I still need help with this account',returnTo:'/support',_csrf:csrf(resolved.text)}).expect(302);
    assert.equal((await db.collection('supporttickets').findOne({_id:ticket._id})).status,'open');
    const profile = await agent.get('/profile').expect(200);
    await agent.post('/account/profile').type('form').send({name:'Customer Updated',phone,country:'UG',currency:'UGX',locale:'en-UG',returnTo:'/profile',_csrf:csrf(profile.text)}).expect(302).expect('location','/profile');
    const savedProfile = await agent.get('/profile').expect(200);
    assert.match(savedProfile.text,/Your profile was updated/);
    assert.equal((await db.collection('users').findOne({_id:user._id})).name,'Customer Updated');
    assert.match((await agent.get('/profile').expect(200)).text,/Customer Updated/);

    const suffix = crypto.randomBytes(8).toString('hex');
    const categoryId = new mongoose.Types.ObjectId(), storeId = new mongoose.Types.ObjectId(), productId = new mongoose.Types.ObjectId(), variantId = new mongoose.Types.ObjectId(), warehouseId = new mongoose.Types.ObjectId();
    const productPublicId = 'prd_' + suffix, variantPublicId = 'var_' + suffix;
    await db.collection('stores').insertOne({_id:storeId,publicId:'sto_'+suffix,ownerUserId:new mongoose.Types.ObjectId(),name:'Verification Store',slug:'verification-'+suffix,country:'UG',currency:'UGX',status:'verified'});
    await db.collection('categories').insertOne({_id:categoryId,publicId:'cat_'+suffix,name:'Verification Category',slug:'verification-'+suffix,active:true,restricted:false,countries:['UG']});
    await db.collection('products').insertOne({_id:productId,publicId:productPublicId,storeId,ownerUserId:user._id,categoryId,title:'Account scoped cart product',slug:'verification-'+suffix,description:'Verification product',countries:['UG'],status:'published',tags:[],createdAt:new Date(),publishedAt:new Date()});
    await db.collection('productvariants').insertOne({_id:variantId,publicId:variantPublicId,productId,storeId,sku:'TEST-'+suffix,title:'Default',priceMinor:15000,currency:'UGX',active:true});
    await db.collection('warehouses').insertOne({_id:warehouseId,publicId:'whs_'+suffix,storeId,ownerUserId:user._id,name:'Verification Warehouse',country:'UG',city:'Kampala',address:'Verification warehouse street',active:true});
    await db.collection('stockitems').insertOne({publicId:'stk_'+suffix,storeId,warehouseId,variantId,onHand:5,reserved:0,damaged:0,quarantined:0});
    const cartPage = await agent.get('/cart').expect(200);
    const headers = {'x-csrf-token':csrf(cartPage.text)};
    await agent.post('/api/v1/storefront/wishlist/'+productPublicId).set(headers).send({}).expect(201);
    assert.match((await agent.get('/wishlist').expect(200)).text,/Account scoped cart product/);
    assert.doesNotMatch((await other.get('/wishlist').expect(200)).text,/Account scoped cart product/);
    await agent.post('/api/v1/cart/items').set(headers).send({productId:productPublicId,variantId:variantPublicId,quantity:1}).expect(200);
    assert.match((await agent.get('/cart').expect(200)).text,/Account scoped cart product/);
    const otherCart = await other.get('/cart').expect(200);
    assert.doesNotMatch(otherCart.text,/Account scoped cart product/);
    await other.patch('/api/v1/cart/items/'+variantPublicId).set('x-csrf-token',csrf(otherCart.text)).send({quantity:2}).expect(404);
    await agent.patch('/api/v1/cart/items/'+variantPublicId).set(headers).send({quantity:2}).expect(200);
    assert.equal((await db.collection('carts').findOne({userId:user._id})).items[0].quantity,2);
    await agent.patch('/api/v1/cart/items/'+variantPublicId).set(headers).send({quantity:6}).expect(409);
    assert.equal((await db.collection('carts').findOne({userId:user._id})).items[0].quantity,2);
    const returning = request.agent(base);
    const loginForm = await returning.get('/login').expect(200);
    await returning.post('/login').type('form').send({email,password,_csrf:csrf(loginForm.text)}).expect(302);
    const restored = await returning.get('/cart').expect(200);
    assert.match(restored.text,/Account scoped cart product/);
    assert.equal((await db.collection('carts').findOne({userId:user._id})).items[0].quantity,2);
    assert.equal(await db.collection('carts').countDocuments({userId:user._id}),1);
    await agent.delete('/api/v1/cart/items/'+variantPublicId).set(headers).expect(200);
    assert.equal((await db.collection('carts').findOne({userId:user._id})).items.length,0);
    await agent.delete('/api/v1/storefront/wishlist/'+productPublicId).set(headers).expect(200);
    assert.doesNotMatch((await agent.get('/wishlist').expect(200)).text,/Account scoped cart product/);
    await db.collection('stockitems').deleteMany({variantId});
    await db.collection('warehouses').deleteOne({_id:warehouseId,storeId});
    await db.collection('productvariants').deleteOne({_id:variantId});
    await db.collection('products').deleteOne({_id:productId});
    await db.collection('stores').deleteOne({_id:storeId});
    await db.collection('categories').deleteOne({_id:categoryId});
    const updated = await agent.get('/addresses').expect(200);
    await agent.post('/addresses/' + stored.publicId + '/archive').type('form').send({ _csrf: csrf(updated.text) }).expect(302);
    assert.ok((await db.collection('customeraddresses').findOne({ _id: stored._id })).archivedAt);
  } finally { await mongoose.disconnect(); }
});
