import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs/promises';
import http from 'node:http';
import mongoose from 'mongoose';
import request from 'supertest';
import sharp from 'sharp';
import { chromium } from '@playwright/test';

const suffix = crypto.randomBytes(8).toString('hex');
process.env.NODE_ENV = 'test';
process.env.SIMPLE_LOGIN = 'false';
process.env.PRIVILEGED_MFA_REQUIRED = 'true';
process.env.MAIL_MODE = 'log';
process.env.UPLOAD_DIR = `/tmp/classicmart-product-images-test-${suffix}`;
process.env.REDIS_URL = '';
const uri = process.env.CLASSIC_MART_LIVE_TEST_MONGO_URI;
const csrf = html => html.match(/(?:name="_csrf"[^>]*value|name="csrf-token" content)="([^"]+)"/)[1];

test('seller products complete authenticated creation, inventory, independent review and public publication without exposing drafts', { skip: !uri }, async t => {
  assert.equal(new URL(uri).hostname, '127.0.0.1');
  assert.match(new URL(uri).pathname, /verification|test/i);
  const database = `classicmart_seller_products_test_${suffix}`;
  await mongoose.connect(uri, { dbName: database });
  const { createApp } = await import('../src/app.js');
  const { User, Store, StoreMember, Product, ProductVariant, ProductMedia, Category, Brand, Warehouse, StockItem, InventoryMovement, InventoryReservation, Order, CountrySetting, ShippingZone, AuditLog, Notification, OutboxEvent, Cart } = await import('../src/models/index.js');
  const { hashPassword } = await import('../src/core/crypto.js');
  const { pendingMfaEnrollment, totpCode } = await import('../src/services/mfa.js');
  const { readMediaObjectBuffer, deleteMediaObject, putMediaObject } = await import('../src/services/object-storage.js');
  const { updateSellerProduct, adjustSellerProductStock, uploadSellerProductImage, sellerProductList } = await import('../src/services/seller-products.js');
  const { reviewProduct } = await import('../src/services/product-moderation.js');
  const { publishedProduct } = await import('../src/services/storefront.js');
  const { processNotificationOutbox } = await import('../src/services/outbox.js');
  const { env } = await import('../src/config/env.js');
  assert.equal(env.mediaStorageDriver, 'filesystem');
  assert.equal(env.uploadDir, process.env.UPLOAD_DIR);
  const app = createApp(null);
  const password = `Products-${suffix}A1!`;
  const png = await sharp({ create: { width: 640, height: 640, channels: 3, background: '#ef6c00' } }).withMetadata({ exif: { IFD0: { Artist: 'PRODUCT_PRIVATE_CAMERA_METADATA' } } }).png().toBuffer();
  const transports = [];
  let actorSequence = 0, server, browser;
  async function actor(role = 'seller', country = 'UG', mfa = true) {
    const index = actorSequence++, email = `products-${suffix}-${index}@example.com`, phone = '+2567' + crypto.randomInt(10000000, 99999999);
    const user = await User.create({ publicId: `usr_prod_${suffix}_${index}`, name: `Product User ${index}`, email, emailNormalized: email, phone, phoneNormalized: phone,
      passwordHash: await hashPassword(password), role, country, currency: 'UGX', emailVerifiedAt: new Date(), onboardingCompletedAt: new Date(),
      consents: { terms: true, privacy: true, recordedAt: new Date() } });
    // Distinct real loopback clients keep actor traffic separate without changing
    // production rate limits or trusting forged forwarding headers.
    const transport = new http.Agent({ localAddress: `127.0.0.${index + 2}`, keepAlive: false });
    transports.push(transport);
    const agent = request.agent(app).use(req => req.agent(transport));
    const login = await agent.get('/login').expect(200);
    await agent.post('/login').type('form').send({ email, password, _csrf: csrf(login.text) }).expect(302);
    if (mfa) {
      const security = await agent.get('/account/security').expect(200);
      await agent.post('/account/mfa/begin').type('form').send({ currentPassword: password, _csrf: csrf(security.text) }).expect(302);
      const pending = await pendingMfaEnrollment(user._id);
      await agent.post('/account/mfa/confirm').type('form').send({ code: totpCode(pending.secret), _csrf: csrf((await agent.get('/account/security')).text) }).expect(302);
      assert.equal((await User.findById(user._id)).security.mfaEnabled, true);
    }
    return { user: await User.findById(user._id), agent };
  }
  try {
    await Promise.all([Store.init(), StoreMember.init(), Product.init(), ProductVariant.init(), ProductMedia.init(), StockItem.init(), Category.init(), Brand.init()]);
    await CountrySetting.create({ code: 'UG', name: 'Uganda', currency: 'UGX', locale: 'en-UG', timeZone: 'Africa/Kampala', phonePrefix: '+256', active: true });
    await ShippingZone.create({ publicId: `zone_products_${suffix}`, country: 'UG', name: 'Test Kampala Delivery', cities: ['Kampala'], standardFeeMinor: 5000, currency: 'UGX', active: true });
    await request(app).get('/seller/products').expect(302).expect('location', '/login?next=%2Fseller%2Fproducts');
    const owner = await actor();
    const listing = await owner.agent.get('/seller/products').expect(200);
    assert.match(listing.text, /Products/);
    assert.doesNotMatch(listing.text, /Development preview|role-workspaces\.js|roleSwitcher/);
    assert.match(listing.headers['cache-control'], /private/);
    assert.match(listing.headers['cache-control'], /no-store/);
    assert.equal(listing.headers['x-robots-tag'], 'noindex, nofollow, noarchive');
    const store = await Store.findOne({ ownerUserId: owner.user._id });
    assert.equal(store.status, 'pending_verification');
    const category = await Category.create({ publicId: `cat_prod_${suffix}`, name: 'Everyday Goods', slug: `everyday-${suffix}`, countries: ['UG'], active: true });
    const restrictedCategory = await Category.create({ publicId: `cat_restricted_${suffix}`, name: 'Restricted Goods', slug: `restricted-${suffix}`, countries: ['UG'], active: true, restricted: true });
    const brand = await Brand.create({ publicId: `brd_prod_${suffix}`, name: 'Test Approved Brand', slug: `approved-brand-${suffix}`, status: 'approved' });
    const warehouse = await Warehouse.create({ publicId: `wh_prod_${suffix}`, storeId: store._id, ownerUserId: owner.user._id, name: 'Kampala Test Warehouse', country: 'UG', city: 'Kampala', address: 'Warehouse test address', active: true });
    const fields = { title: `Cotton Travel Bag ${suffix}`, description: 'A durable cotton travel bag with a reinforced strap and zipped interior pocket. Suitable for everyday shopping and weekend travel. Check the dimensions and fabric care instructions before purchasing.',
      categoryPublicId: category.publicId, brandPublicId: brand.publicId, sku: `BAG-${suffix}`, variantTitle: 'Natural Cotton', price: '45000', compareAt: '50000', weightGrams: '650' };
    const newPage = await owner.agent.get('/seller/products/new').expect(200);
    await owner.agent.post('/seller/products').type('form').send(fields).expect(403);
    assert.equal(await Product.countDocuments(), 0);
    const invalid = await owner.agent.post('/seller/products').type('form').send({ ...fields, description: 'Short', _csrf: csrf(newPage.text) }).expect(422);
    assert.match(invalid.text, new RegExp(fields.title));
    assert.match(invalid.text, /value="45000"/);
    await owner.agent.post('/seller/products').type('form').send({ ...fields, _csrf: csrf(newPage.text), status: 'published', countries: ['KE'], ownerUserId: new mongoose.Types.ObjectId().toString() }).expect(302);
    let product = await Product.findOne({ storeId: store._id });
    assert.equal(product.status, 'draft');
    assert.equal(String(product.ownerUserId), String(owner.user._id));
    assert.deepEqual(product.countries.toObject(), ['UG']);
    let variant = await ProductVariant.findOne({ productId: product._id });
    assert.equal(variant.priceMinor, 45000); assert.equal(variant.compareAtMinor, 50000);
    assert.equal(variant.currency, 'UGX'); assert.equal(variant.weightGrams, 650);
    const duplicate = await owner.agent.post('/seller/products').type('form').send({ ...fields, title: 'Duplicate SKU must never create a partial product', _csrf: csrf(newPage.text) }).expect(409);
    assert.match(duplicate.text, /SKU/);
    assert.equal(await Product.countDocuments({ storeId: store._id }), 1);
    assert.equal(await ProductVariant.countDocuments({ storeId: store._id }), 1);
    const base = '/seller/products/' + product.publicId;
    const version = async () => (await Product.findById(product._id)).__v;
    const ownerPost = async (action, payload = {}) => {
      const view = await owner.agent.get(base).expect(200);
      return owner.agent.post(base + '/' + action).type('form').send({ version: await version(), _csrf: csrf(view.text), ...payload });
    };
    const upload = async (bytes = png, contentType = 'image/png', position = 0) => {
      const view = await owner.agent.get(base).expect(200);
      return owner.agent.post(base + '/images').field('_csrf', csrf(view.text)).field('version', String(await version())).field('altText', 'Cotton bag view ' + position).field('position', String(position)).attach('image', bytes, { filename: 'bag.png', contentType });
    };
    await request(app).get('/products/' + product.publicId).expect(404);
    assert.equal((await ownerPost('submit')).status, 409, 'pending stores cannot submit a product');
    await Store.updateOne({ _id: store._id }, { $set: { status: 'verified', verifiedAt: new Date() } });
    assert.equal((await ownerPost('submit')).status, 422, 'submission requires three current images');
    assert.equal((await upload(Buffer.from('not a real image'))).status, 422);
    assert.equal((await upload(Buffer.from('<svg/>'), 'image/svg+xml')).status, 422);
    await owner.agent.post(base + '/images').field('version', String(await version())).field('altText', 'An image without CSRF must not be stored').field('position', '0').attach('image', png, { filename: 'no-csrf.png', contentType: 'image/png' }).expect(403);
    assert.equal(await ProductMedia.countDocuments({ productId: product._id }), 0);
    assert.equal((await upload()).status, 302);
    const media = await ProductMedia.findOne({ productId: product._id }).select('+storageKey +thumbnailStorageKey');
    assert.equal(media.status, 'ready');
    const imageBytes = await readMediaObjectBuffer(media.storageKey), metadata = await sharp(imageBytes).metadata();
    assert.equal(metadata.format, 'webp'); assert.equal(metadata.exif, undefined);
    assert.equal(imageBytes.includes(Buffer.from('PRODUCT_PRIVATE_CAMERA_METADATA')), false);
    await request(app).get('/media/catalogue/' + media.publicId).expect(404);
    const preview = await owner.agent.get('/media/catalogue/' + media.publicId).expect(200);
    assert.match(preview.headers['cache-control'], /private/);
    assert.match(preview.headers['cache-control'], /no-store/);
    const thumbnailBytes = await readMediaObjectBuffer(media.thumbnailStorageKey);
    await deleteMediaObject(media.storageKey); await deleteMediaObject(media.thumbnailStorageKey);
    await request(app).get('/media/catalogue/' + media.publicId).expect(404);
    const missingImage = await owner.agent.get('/media/catalogue/' + media.publicId).expect(200);
    assert.equal(missingImage.headers['x-classic-mart-media-fallback'], 'missing-object');
    assert.match(missingImage.headers['content-type'], /image\/svg\+xml/);
    assert.match(missingImage.headers['cache-control'], /no-store/);
    await putMediaObject(media.storageKey, imageBytes, { contentType: 'image/webp' });
    await putMediaObject(media.thumbnailStorageKey, thumbnailBytes, { contentType: 'image/webp' });
    assert.equal((await upload(png, 'image/png', 1)).status, 302);
    assert.equal((await upload(png, 'image/png', 2)).status, 302);
    assert.equal(await ProductMedia.countDocuments({ productId: product._id }), 3);
    const objectDirectory = `${process.env.UPLOAD_DIR}/${product.publicId}`;
    const beforeObjects = (await fs.readdir(objectDirectory)).sort();
    t.mock.method(AuditLog, 'create', async () => { throw new Error('Product upload audit unavailable'); });
    assert.equal((await upload(png, 'image/png', 3)).status, 500);
    t.mock.restoreAll();
    assert.deepEqual((await fs.readdir(objectDirectory)).sort(), beforeObjects);
    assert.equal(await ProductMedia.countDocuments({ productId: product._id }), 3);

    const other = await actor();
    await other.agent.get('/seller/products').expect(200);
    const otherStore = await Store.findOne({ ownerUserId: other.user._id });
    await other.agent.get(base).expect(404);
    await other.agent.get('/media/catalogue/' + media.publicId).expect(404);
    const delegated = await StoreMember.create({ publicId: `stm_prod_${suffix}`, storeId: store._id, userId: other.user._id, invitedByUserId: owner.user._id, role: 'catalogue', status: 'active' });
    await other.agent.get('/media/catalogue/' + media.publicId).expect(200);
    await StoreMember.updateOne({ _id: delegated._id }, { $set: { status: 'revoked', revokedAt: new Date() } });
    await other.agent.get('/media/catalogue/' + media.publicId).expect(404);
    await assert.rejects(updateSellerProduct({ id: `revoked-product-${suffix}`, user: other.user, store, params: { publicId: product.publicId }, body: { ...fields, version: await version() }, get: () => '' }), { code: 'STORE_PERMISSION_DENIED' });

    const firstVersion = await version();
    assert.equal((await ownerPost('update', { ...fields, version: firstVersion - 1 })).status, 409);
    const fractional = await ownerPost('variants/' + variant.publicId, { sku: variant.sku, title: 'Natural Cotton', price: '45000.50', compareAt: '50000', weightGrams: 650, active: 'yes' });
    assert.equal(fractional.status, 422, 'UGX amounts must never be silently rounded');
    assert.equal((await ProductVariant.findById(variant._id)).priceMinor, 45000);
    const previousTitle = (await Product.findById(product._id)).title;
    t.mock.method(AuditLog, 'create', async () => { throw new Error('Product update audit unavailable'); });
    await assert.rejects(updateSellerProduct({ id: `update-audit-${suffix}`, user: owner.user, store, params: { publicId: product.publicId }, body: { ...fields, title: 'Rollback product title', version: await version() }, get: () => '' }), /Product update audit unavailable/);
    t.mock.restoreAll();
    assert.equal((await Product.findById(product._id)).title, previousTitle);
    const competingVersion = await version();
    const competing = await Promise.allSettled(Array.from({ length: 6 }, (_, index) => updateSellerProduct({ id: `competing-product-${suffix}-${index}`, user: owner.user, store, params: { publicId: product.publicId }, body: { ...fields, title: `${fields.title} edit ${index}`, version: competingVersion }, get: () => '' })));
    assert.equal(competing.filter(row => row.status === 'fulfilled').length, 1, competing.filter(row => row.status === 'rejected').map(row => row.reason.code || row.reason.message).join(', '));
    assert.equal(await version(), competingVersion + 1);
    assert.equal((await ownerPost('update', fields)).status, 302);
    const variantVersion = await version();
    assert.equal((await ownerPost('variants', { sku: `BAG-BLUE-${suffix}`, title: 'Blue Cotton', price: '47000', compareAt: '52000', weightGrams: 650, active: 'yes', optionName: 'Colour', optionValue: 'Blue' })).status, 302);
    assert.equal(await version(), variantVersion + 1, 'variant creation must invalidate earlier aggregate forms even when quality is unchanged');
    const blue = await ProductVariant.findOne({ productId: product._id, sku: `BAG-BLUE-${suffix}`.toUpperCase() });
    assert.equal(blue.priceMinor, 47000); assert.equal(blue.options.get('Colour'), 'Blue');
    assert.equal((await ownerPost('variants/' + blue.publicId, { sku: blue.sku, title: 'Blue Cotton Updated', price: '48000', compareAt: '52000', weightGrams: 700, active: 'yes' })).status, 302);
    assert.equal((await ProductVariant.findById(blue._id)).priceMinor, 48000);
    const stockFields = { variantPublicId: variant.publicId, warehousePublicId: warehouse.publicId, quantity: 12, reason: 'Received twelve sellable bags', reorderPoint: 3 };
    const stockVersion = await version();
    assert.equal((await ownerPost('stock', stockFields)).status, 302);
    assert.equal(await version(), stockVersion + 1, 'stock updates must invalidate earlier inventory forms');
    let stock = await StockItem.findOne({ variantId: variant._id, warehouseId: warehouse._id });
    assert.equal(stock.onHand, 12); assert.equal(stock.reorderPoint, 3);
    assert.equal(await InventoryMovement.countDocuments({ stockItemId: stock._id }), 1);
    await StockItem.updateOne({ _id: stock._id }, { $set: { reserved: 4, damaged: 2 } });
    assert.equal((await ownerPost('stock', { ...stockFields, quantity: -7 })).status, 409, 'reserved and damaged stock cannot be reduced below on-hand');
    assert.equal((await ownerPost('variants/' + variant.publicId, { sku: variant.sku, title: variant.title, price: '45000', compareAt: '50000', weightGrams: 650, active: 'no' })).status, 409, 'a variant with outstanding reservations cannot be deactivated');
    assert.equal((await ProductVariant.findById(variant._id)).active, true);
    assert.equal((await StockItem.findById(stock._id)).onHand, 12);
    t.mock.method(AuditLog, 'create', async () => { throw new Error('Stock audit unavailable'); });
    await assert.rejects(adjustSellerProductStock({ id: `stock-audit-${suffix}`, user: owner.user, store, params: { publicId: product.publicId }, body: { ...stockFields, quantity: 2, version: await version() }, get: () => '' }), /Stock audit unavailable/);
    t.mock.restoreAll();
    assert.equal((await StockItem.findById(stock._id)).onHand, 12);
    assert.equal(await InventoryMovement.countDocuments({ stockItemId: stock._id }), 1);
    const foreignWarehouse = await Warehouse.create({ publicId: `wh_foreign_${suffix}`, storeId: otherStore._id, ownerUserId: other.user._id, name: 'Other Store Warehouse', country: 'UG', city: 'Jinja', address: 'Other warehouse test address' });
    assert.equal((await ownerPost('stock', { ...stockFields, warehousePublicId: foreignWarehouse.publicId })).status, 404);
    await StockItem.updateOne({ _id: stock._id }, { $set: { reserved: 0, damaged: 0 } });
    const metadataVersion = await version();
    assert.equal((await ownerPost('images/' + media.publicId, { action: 'update', altText: 'Cotton bag showing reinforced carry strap', position: 2 })).status, 302);
    assert.equal(await version(), metadataVersion + 1, 'image metadata changes must invalidate earlier review and edit forms');
    assert.equal((await ProductMedia.findById(media._id)).altText, 'Cotton bag showing reinforced carry strap');
    assert.equal((await ownerPost('submit')).status, 302);
    assert.equal((await Product.findById(product._id)).status, 'submitted');
    assert.equal((await ownerPost('update', fields)).status, 409, 'submitted content remains stable for review');
    assert.equal((await ownerPost('publish')).status, 409);
    await request(app).get('/products/' + product.publicId).expect(404);

    const reviewer = await actor('moderator'), contender = await actor('moderator'), foreignReviewer = await actor('moderator', 'KE');
    const reviewBase = '/moderation/products/' + product.publicId;
    assert.match((await reviewer.agent.get('/moderation/products').expect(200)).text, new RegExp(fields.title));
    assert.doesNotMatch((await foreignReviewer.agent.get('/moderation/products').expect(200)).text, new RegExp(fields.title));
    await foreignReviewer.agent.get(reviewBase).expect(403);
    await foreignReviewer.agent.get('/media/catalogue/' + media.publicId).expect(403);
    const reviewPost = async (session, action, payload = {}, id = product.publicId) => {
      const view = await session.agent.get('/moderation/products/' + id).expect(200);
      const fresh = await Product.findOne({ publicId: id });
      return session.agent.post('/moderation/products/' + id + '/' + action).type('form').send({ version: fresh.__v, _csrf: csrf(view.text), ...payload });
    };
    assert.equal((await reviewPost(reviewer, 'decision', { decision: 'approve' })).status, 409);
    const claimVersion = await version();
    const claims = await Promise.allSettled(Array.from({ length: 12 }, (_, index) => reviewProduct({ id: `product-claim-${suffix}-${index}`, user: index % 2 ? reviewer.user : contender.user, params: { publicId: product.publicId }, body: { version: claimVersion }, get: () => '' }, 'claim')));
    assert.equal(claims.filter(row => row.status === 'fulfilled').length, 1, claims.filter(row => row.status === 'rejected').map(row => row.reason.code || row.reason.message).join(', '));
    product = await Product.findById(product._id);
    assert.equal(product.moderation.reviewHistory.filter(row => row.action === 'claim').length, 1);
    if (String(product.moderation.assignedUserId) !== String(reviewer.user._id)) {
      assert.equal((await reviewPost(contender, 'release')).status, 302);
      assert.equal((await reviewPost(reviewer, 'claim')).status, 302);
    }
    assert.equal((await reviewPost(reviewer, 'decision', { decision: 'changes', reason: 'Short' })).status, 422);
    assert.equal((await reviewPost(reviewer, 'decision', { decision: 'changes', reason: 'Clarify fabric care instructions in the description.' })).status, 302);
    assert.equal((await Product.findById(product._id)).status, 'changes_requested');
    assert.match((await owner.agent.get(base).expect(200)).text, /Clarify fabric care instructions/);
    assert.equal((await ownerPost('update', { ...fields, description: fields.description + ' Hand wash with cold water and dry in the shade.' })).status, 302);
    assert.equal((await ownerPost('submit')).status, 302);
    assert.equal((await reviewPost(reviewer, 'claim')).status, 302);
    const notificationsBeforeApproval = await Notification.countDocuments({ userId: owner.user._id });
    t.mock.method(AuditLog, 'create', async () => { throw new Error('Product decision audit unavailable'); });
    await assert.rejects(reviewProduct({ id: `decision-audit-${suffix}`, user: reviewer.user, params: { publicId: product.publicId }, body: { version: await version(), decision: 'approve', reason: 'Product details confirmed.' }, get: () => '' }, 'decision'), /Product decision audit unavailable/);
    t.mock.restoreAll();
    assert.equal((await Product.findById(product._id)).status, 'submitted');
    assert.equal(await ProductMedia.countDocuments({ productId: product._id, status: 'approved' }), 0);
    assert.equal(await Notification.countDocuments({ userId: owner.user._id }), notificationsBeforeApproval);
    assert.equal((await reviewPost(reviewer, 'decision', { decision: 'approve', reason: 'Product details and images confirmed.' })).status, 302);
    assert.equal((await Product.findById(product._id)).status, 'approved');
    assert.equal(await ProductMedia.countDocuments({ productId: product._id, status: 'approved' }), 3);
    await request(app).get('/media/catalogue/' + media.publicId).expect(404);
    assert.equal((await ownerPost('publish')).status, 302);
    assert.equal((await Product.findById(product._id)).status, 'published');
    const publicProduct = await request(app).get('/products/' + product.publicId).expect(200);
    assert.match(publicProduct.text, /application\/ld\+json/); assert.match(publicProduct.text, /https:\/\/schema\.org/);
    assert.match(publicProduct.text, new RegExp(fields.title));
    const publicImage = await request(app).get('/media/catalogue/' + media.publicId).expect(200);
    assert.match(publicImage.headers['cache-control'], /public/);
    const customer = await actor('customer', 'UG', false);
    const cart = await customer.agent.get('/api/v1/cart').expect(200);
    const secondWarehouse = await Warehouse.create({ publicId: `wh_second_${suffix}`, storeId: store._id, ownerUserId: owner.user._id, name: 'Second Active Warehouse', country: 'UG', city: 'Kampala', address: 'Second warehouse test address', active: true });
    await StockItem.create({ publicId: `stk_second_${suffix}`, storeId: store._id, warehouseId: secondWarehouse._id, variantId: variant._id, onHand: 5 });
    const inactiveWarehouse = await Warehouse.create({ publicId: `wh_inactive_${suffix}`, storeId: store._id, ownerUserId: owner.user._id, name: 'Inactive Warehouse', country: 'UG', city: 'Kampala', address: 'Inactive warehouse test address', active: false });
    await StockItem.create({ publicId: `stk_inactive_${suffix}`, storeId: store._id, warehouseId: inactiveWarehouse._id, variantId: variant._id, onHand: 100 });
    const country = { code: 'UG', currency: 'UGX', locale: 'en-UG' };
    const catalogueProduct = await publishedProduct(product.publicId, country);
    assert.equal(catalogueProduct.variants.find(row => row.id === variant.publicId).stock, 12, 'one cart line can only be reserved in one active warehouse');
    const addedCart = await customer.agent.post('/api/v1/cart/items').set('x-csrf-token', cart.body.csrfToken).send({ productId: product.publicId, variantId: variant.publicId, quantity: 2 }).expect(200);
    assert.equal(addedCart.body.cart.items[0].available, 12);
    const storedCart = await Cart.findOne({ userId: customer.user._id });
    assert.equal(storedCart.items[0].quantity, 2); assert.equal(String(storedCart.items[0].variantId), String(variant._id));
    await customer.agent.patch('/api/v1/cart/items/' + variant.publicId).set('x-csrf-token', cart.body.csrfToken).send({ quantity: 13 }).expect(409);
    const checkout = await customer.agent.post('/api/v1/checkout/review').set('x-csrf-token', cart.body.csrfToken).send({ deliveryMethod: 'standard', paymentMethod: 'cod', city: 'Kampala' }).expect(200);
    const orderInput = { checkoutId: checkout.body.checkoutId, deliveryMethod: 'standard', paymentMethod: 'cod', city: 'Kampala', contact: { fullName: 'Product Test Buyer', email: customer.user.email, phone: customer.user.phone, address: 'Buyer test street address', city: 'Kampala', country: 'Uganda' } };
    const deniedOrder = async reason => {
      const response = await customer.agent.post('/api/v1/orders').set('x-csrf-token', cart.body.csrfToken).send({ ...orderInput, idempotencyKey: `product-denied-${suffix}-${reason}` }).expect(409);
      assert.equal(response.body.error.code, 'CART_CHANGED');
      assert.equal(await Order.countDocuments(), 0); assert.equal(await InventoryReservation.countDocuments(), 0);
      assert.equal((await StockItem.findById(stock._id)).reserved, 0);
    };
    await Store.updateOne({ _id: store._id }, { $set: { status: 'suspended' } });
    await request(app).get('/products/' + product.publicId).expect(404);
    await request(app).get('/media/catalogue/' + media.publicId).expect(404);
    await customer.agent.post('/api/v1/cart/items').set('x-csrf-token', cart.body.csrfToken).send({ productId: product.publicId, variantId: variant.publicId, quantity: 1 }).expect(404);
    await deniedOrder('suspended-store');
    await Store.updateOne({ _id: store._id }, { $set: { status: 'verified' } });
    await Brand.updateOne({ _id: brand._id }, { $set: { status: 'rejected' } });
    await request(app).get('/products/' + product.publicId).expect(404);
    await deniedOrder('rejected-brand');
    await Brand.updateOne({ _id: brand._id }, { $set: { status: 'approved' } });
    await Category.updateOne({ _id: category._id }, { $set: { active: false } });
    assert.equal((await customer.agent.get('/api/v1/cart').expect(200)).body.cart.items.length, 0);
    await deniedOrder('inactive-category');
    await Category.updateOne({ _id: category._id }, { $set: { active: true } });
    await ProductVariant.updateOne({ _id: variant._id }, { $set: { currency: 'USD' } });
    await customer.agent.post('/api/v1/cart/items').set('x-csrf-token', cart.body.csrfToken).send({ productId: product.publicId, variantId: variant.publicId, quantity: 1 }).expect(409);
    await deniedOrder('invalid-variant-currency');
    await ProductVariant.updateOne({ _id: variant._id }, { $set: { currency: 'UGX' } });
    assert.equal((await ownerPost('archive')).status, 302);
    assert.equal((await Product.findById(product._id)).status, 'archived');
    await request(app).get('/products/' + product.publicId).expect(404);
    await request(app).get('/media/catalogue/' + media.publicId).expect(404);
    await customer.agent.post('/api/v1/cart/items').set('x-csrf-token', cart.body.csrfToken).send({ productId: product.publicId, variantId: variant.publicId, quantity: 1 }).expect(404);
    assert.equal((await ownerPost('reopen')).status, 302);
    assert.equal((await Product.findById(product._id)).status, 'draft');
    assert.equal(await ProductMedia.countDocuments({ productId: product._id, status: 'approved' }), 0);
    assert.equal((await ownerPost('publish')).status, 409, 'reopening never retains earlier approval');

    // A required category attribute must be supplied before the draft is reviewable.
    const requiredCategory = await Category.create({ publicId: `cat_attr_${suffix}`, name: 'Attributed Bags', slug: `attributes-${suffix}`, countries: ['UG'], attributes: [{ key: 'material', label: 'Material', type: 'select', required: true, options: ['Cotton', 'Canvas'] }] });
    assert.equal((await ownerPost('update', { ...fields, categoryPublicId: requiredCategory.publicId })).status, 302);
    assert.equal((await ownerPost('submit')).status, 422);
    assert.equal((await ownerPost('update', { ...fields, categoryPublicId: requiredCategory.publicId, 'attribute[material]': 'Plastic' })).status, 422);
    assert.equal((await ownerPost('update', { ...fields, categoryPublicId: requiredCategory.publicId, 'attribute[invented]': 'Unexpected attribute' })).status, 422);
    assert.equal((await ownerPost('update', { ...fields, categoryPublicId: requiredCategory.publicId, 'attribute[material]': 'Cotton' })).status, 302);
    assert.equal((await Product.findById(product._id)).attributes.get('material'), 'Cotton');

    const restrictedFields = { ...fields, title: `Restricted Travel Bag ${suffix}`, categoryPublicId: restrictedCategory.publicId, sku: `RESTRICTED-${suffix}` };
    await owner.agent.post('/seller/products').type('form').send({ ...restrictedFields, _csrf: csrf(newPage.text) }).expect(302);
    const restricted = await Product.findOne({ storeId: store._id, title: restrictedFields.title });
    const restrictedBase = '/seller/products/' + restricted.publicId;
    const restrictedVariant = await ProductVariant.findOne({ productId: restricted._id });
    const restrictedPost = async (action, payload = {}) => owner.agent.post(restrictedBase + '/' + action).type('form').send({ version: (await Product.findById(restricted._id)).__v, _csrf: csrf(newPage.text), ...payload });
    for (let position = 0; position < 3; position++) {
      await owner.agent.post(restrictedBase + '/images').field('_csrf', csrf(newPage.text)).field('version', String((await Product.findById(restricted._id)).__v)).field('altText', 'Restricted cotton bag view ' + position).field('position', String(position)).attach('image', png, { filename: 'restricted-bag.png', contentType: 'image/png' }).expect(302);
    }
    assert.equal((await restrictedPost('stock', { ...stockFields, variantPublicId: restrictedVariant.publicId, quantity: 5 })).status, 302);
    assert.equal((await restrictedPost('submit')).status, 302);
    assert.equal((await reviewPost(reviewer, 'claim', {}, restricted.publicId)).status, 302);
    assert.equal((await reviewPost(reviewer, 'decision', { decision: 'approve', reason: 'First restricted product review confirmed.' }, restricted.publicId)).status, 302);
    let firstApproval = await Product.findById(restricted._id);
    assert.equal(firstApproval.status, 'submitted');
    assert.equal(String(firstApproval.moderation.firstApprovalByUserId), String(reviewer.user._id));
    assert.equal(firstApproval.moderation.secondReviewRequired, true);
    assert.equal((await restrictedPost('publish')).status, 409);
    await assert.rejects(reviewProduct({ id: `same-second-review-${suffix}`, user: reviewer.user, params: { publicId: restricted.publicId }, body: { version: firstApproval.__v }, get: () => '' }, 'claim'), { code: 'MODERATION_FOUR_EYES' });
    assert.equal((await reviewPost(contender, 'claim', {}, restricted.publicId)).status, 302);
    assert.equal((await reviewPost(contender, 'decision', { decision: 'approve', reason: 'Independent second restricted product review confirmed.' }, restricted.publicId)).status, 302);
    assert.equal((await Product.findById(restricted._id)).status, 'approved');
    assert.equal((await restrictedPost('publish')).status, 302);
    await request(app).get('/products/' + restricted.publicId).expect(200);

    const reviewerStore = await Store.create({ publicId: `str_self_product_${suffix}`, ownerUserId: reviewer.user._id, name: 'Reviewer conflict fixture', slug: `reviewer-conflict-${suffix}`, country: 'UG', currency: 'UGX', status: 'verified', verifiedAt: new Date() });
    const selfProduct = await Product.create({ publicId: `prd_${crypto.randomBytes(16).toString('hex')}`, storeId: reviewerStore._id, ownerUserId: reviewer.user._id, categoryId: category._id, title: 'Reviewer owned product', slug: `self-${suffix}`, description: fields.description, countries: ['UG'], status: 'submitted', moderation: { submittedAt: new Date() } });
    await assert.rejects(reviewProduct({ id: `self-product-review-${suffix}`, user: reviewer.user, params: { publicId: selfProduct.publicId }, body: { version: selfProduct.__v }, get: () => '' }, 'claim'), { code: 'REVIEW_CONFLICT_OF_INTEREST' });

    // Concurrent uploads must serialize through the same aggregate version.
    const imageVersion = await version(), imageCount = await ProductMedia.countDocuments({ productId: product._id });
    const uploadClaims = await Promise.allSettled(Array.from({ length: 6 }, (_, index) => uploadSellerProductImage({ id: `product-upload-race-${suffix}-${index}`, user: owner.user, store, params: { publicId: product.publicId }, body: { version: imageVersion, altText: 'Concurrent product image ' + index, position: imageCount }, file: { buffer: png, mimetype: 'image/png', originalname: 'race.png' }, get: () => '' })));
    assert.equal(uploadClaims.filter(row => row.status === 'fulfilled').length, 1, uploadClaims.filter(row => row.status === 'rejected').map(row => row.reason.code || row.reason.message).join(', '));
    assert.equal(await ProductMedia.countDocuments({ productId: product._id }), imageCount + 1);
    assert.equal((await fs.readdir(objectDirectory)).length, (imageCount + 1) * 2);
    const raceImage = await ProductMedia.findOne({ productId: product._id, altText: /^Concurrent product image/ });
    t.mock.method(AuditLog, 'create', async () => { throw new Error('Image deletion audit unavailable'); });
    assert.equal((await ownerPost('images/' + raceImage.publicId, { action: 'remove' })).status, 500);
    t.mock.restoreAll();
    assert.equal(await ProductMedia.countDocuments({ productId: product._id }), imageCount + 1);
    assert.equal((await fs.readdir(objectDirectory)).length, (imageCount + 1) * 2);
    assert.equal((await ownerPost('images/' + raceImage.publicId, { action: 'remove' })).status, 302);
    assert.equal(await ProductMedia.countDocuments({ productId: product._id }), imageCount);
    assert.equal((await fs.readdir(objectDirectory)).length, imageCount * 2);
    await owner.agent.get('/media/catalogue/' + raceImage.publicId).expect(404);

    if (process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE) {
      await Store.updateOne({ _id: otherStore._id }, { $set: { status: 'verified', verifiedAt: new Date() } });
      server = app.listen(0, '127.0.0.1'); await new Promise(resolve => server.once('listening', resolve));
      const origin = `http://127.0.0.1:${server.address().port}`;
      browser = await chromium.launch({ executablePath: process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE, args: ['--no-sandbox'] });
      const errors = [];
      async function browserSession(session, path) {
        const context = await browser.newContext();
        const cookie = (await session.agent.get(path)).headers['set-cookie'].find(value => value.startsWith('cm.sid=')).split(';')[0];
        const split = cookie.indexOf('='); await context.addCookies([{ name: cookie.slice(0, split), value: cookie.slice(split + 1), url: origin }]);
        const browserPage = await context.newPage(); browserPage.on('pageerror', error => errors.push(error.message));
        return { context, browserPage };
      }
      async function submitBrowserForm(browserPage, form, button = 'button[type="submit"]') {
        await Promise.all([browserPage.waitForNavigation({ waitUntil: 'domcontentloaded' }), form.locator(button).click()]);
        assert.equal(new URL(browserPage.url()).hash, '');
      }
      const sellerBrowser = await browserSession(other, '/seller/products');
      const browserPage = sellerBrowser.browserPage;
      await browserPage.goto(origin + '/seller/products/new');
      const createForm = browserPage.locator('form[action="/seller/products"]');
      await createForm.locator('[name="title"]').fill('Browser Cotton Travel Bag');
      await createForm.locator('[name="description"]').fill(fields.description);
      await createForm.locator('[name="categoryPublicId"]').selectOption(category.publicId);
      await createForm.locator('[name="brandPublicId"]').selectOption(brand.publicId);
      await createForm.locator('[name="sku"]').fill(`BROWSER-${suffix}`);
      await createForm.locator('[name="variantTitle"]').fill('Browser Default');
      await createForm.locator('[name="price"]').fill('55000');
      await createForm.locator('[name="compareAt"]').fill('60000');
      await createForm.locator('[name="weightGrams"]').fill('600');
      await submitBrowserForm(browserPage, createForm);
      const browserProduct = await Product.findOne({ storeId: otherStore._id, title: 'Browser Cotton Travel Bag' });
      assert.ok(browserProduct); assert.equal(browserProduct.status, 'draft');
      const browserBase = '/seller/products/' + browserProduct.publicId;
      assert.equal(new URL(browserPage.url()).pathname, browserBase);
      const warehouseForm = browserPage.locator(`form[action="${browserBase}/warehouses"]`);
      await warehouseForm.locator('xpath=..').locator('summary').click();
      await warehouseForm.locator('[name="name"]').fill('Browser Created Warehouse');
      await warehouseForm.locator('[name="city"]').fill('Kampala');
      await warehouseForm.locator('[name="address"]').fill('Browser warehouse collection address');
      await submitBrowserForm(browserPage, warehouseForm);
      const browserWarehouse = await Warehouse.findOne({ storeId: otherStore._id, name: 'Browser Created Warehouse' });
      assert.ok(browserWarehouse); assert.equal(browserWarehouse.country, 'UG');
      const browserVariant = await ProductVariant.findOne({ productId: browserProduct._id });
      const stockForm = browserPage.locator(`form[action="${browserBase}/stock"]`);
      await stockForm.locator('[name="variantPublicId"]').selectOption(browserVariant.publicId);
      await stockForm.locator('[name="warehousePublicId"]').selectOption(browserWarehouse.publicId);
      await stockForm.locator('[name="quantity"]').fill('8');
      await stockForm.locator('[name="reason"]').fill('Browser real inventory receipt');
      await submitBrowserForm(browserPage, stockForm);
      assert.equal((await StockItem.findOne({ variantId: browserVariant._id })).onHand, 8);
      for (let position = 0; position < 3; position++) {
        const imageForm = browserPage.locator(`form[action="${browserBase}/images"]`);
        await imageForm.locator('[name="image"]').setInputFiles({ name: 'browser-bag.png', mimeType: 'image/png', buffer: png });
        await imageForm.locator('[name="altText"]').fill('Browser cotton bag view ' + position);
        await imageForm.locator('[name="position"]').fill(String(position));
        await submitBrowserForm(browserPage, imageForm);
      }
      const originalBrowserImage = await ProductMedia.findOne({ productId: browserProduct._id, position: 0 }).select('+storageKey +thumbnailStorageKey');
      const replaceForm = browserPage.locator(`form[action="${browserBase}/images/${originalBrowserImage.publicId}/replace"]`);
      await replaceForm.locator('xpath=..').locator('summary').click();
      await replaceForm.locator('[name="image"]').setInputFiles({ name: 'replaced-browser-bag.png', mimeType: 'image/png', buffer: png });
      await replaceForm.locator('[name="altText"]').fill('Replacement browser cotton bag cover');
      await submitBrowserForm(browserPage, replaceForm);
      assert.equal(await ProductMedia.exists({ _id: originalBrowserImage._id }), null);
      assert.equal(await ProductMedia.countDocuments({ productId: browserProduct._id }), 3);
      assert.equal((await ProductMedia.findOne({ productId: browserProduct._id, position: 0 })).altText, 'Replacement browser cotton bag cover');
      await assert.rejects(readMediaObjectBuffer(originalBrowserImage.storageKey), { code: 'MEDIA_OBJECT_NOT_FOUND' });
      await assert.rejects(readMediaObjectBuffer(originalBrowserImage.thumbnailStorageKey), { code: 'MEDIA_OBJECT_NOT_FOUND' });
      await browserPage.setViewportSize({ width: 390, height: 950 });
      assert.equal(await browserPage.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
      const mobileSkuCell = browserPage.locator('.seller-product-page .role-table tbody tr').first().locator('td[data-label="Variant"]');
      assert.ok((await mobileSkuCell.boundingBox()).height < 80, 'mobile SKU text should stay readable instead of wrapping one character per line');
      assert.ok((await mobileSkuCell.boundingBox()).width >= 100, 'mobile inventory values need enough space to read');
      await browserPage.screenshot({ path: '/tmp/classicmart-seller-products-editable-390.png', fullPage: true });
      await browserPage.setViewportSize({ width: 1366, height: 950 });
      await submitBrowserForm(browserPage, browserPage.locator(`form[action="${browserBase}/submit"]`));
      assert.equal((await Product.findById(browserProduct._id)).status, 'submitted');
      const reviewerBrowser = await browserSession(reviewer, '/moderation/products');
      const reviewPage = reviewerBrowser.browserPage, browserReviewBase = '/moderation/products/' + browserProduct.publicId;
      await reviewPage.goto(origin + browserReviewBase);
      await submitBrowserForm(reviewPage, reviewPage.locator(`form[action="${browserReviewBase}/claim"]`));
      const decisionForm = reviewPage.locator(`form[action="${browserReviewBase}/decision"]`);
      await decisionForm.locator('[name="reason"]').fill('Browser independent product review confirmed.');
      await submitBrowserForm(reviewPage, decisionForm, 'button[name="decision"][value="approve"]');
      assert.equal((await Product.findById(browserProduct._id)).status, 'approved');
      await browserPage.goto(origin + browserBase);
      await submitBrowserForm(browserPage, browserPage.locator(`form[action="${browserBase}/publish"]`));
      assert.equal((await Product.findById(browserProduct._id)).status, 'published');
      for (const [page, path, name] of [[browserPage, browserBase, 'seller'], [reviewPage, browserReviewBase, 'reviewer']]) {
        for (const width of [1366, 390]) {
          await page.setViewportSize({ width, height: 950 });
          const response = await page.goto(origin + path); assert.equal(response.status(), 200);
          assert.ok(await page.locator('h1').isVisible());
          assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
          await page.screenshot({ path: `/tmp/classicmart-${name}-products-${width}.png`, fullPage: true });
        }
      }
      await sellerBrowser.context.close(); await reviewerBrowser.context.close();
      assert.deepEqual(errors, []);
    }

    const queuedNotifications = await OutboxEvent.countDocuments({ type: 'catalogue.product_notification', status: 'pending' });
    assert.ok(queuedNotifications > 0);
    const delivery = await processNotificationOutbox({ limit: 50 });
    assert.equal(delivery.processed, queuedNotifications); assert.equal(delivery.failed, 0);
    assert.equal(await OutboxEvent.countDocuments({ type: 'catalogue.product_notification', status: 'processed', lastError: /no external email was sent/ }), queuedNotifications, 'development notification processing must clearly report that no provider email was delivered');

    const pageFixtures = await Product.insertMany(Array.from({ length: 51 }, (_, index) => ({ publicId: `prd_${crypto.randomBytes(16).toString('hex')}`, storeId: store._id, ownerUserId: owner.user._id, categoryId: category._id, title: `Paged Test Bag ${index}`, slug: `page-bag-${suffix}-${index}`, description: fields.description, countries: ['UG'], status: 'draft' })));
    const listRequest = { user: owner.user, store };
    const firstPage = await sellerProductList(listRequest, { status: 'draft', q: 'Paged Test Bag' });
    assert.equal(firstPage.items.length, 50); assert.equal(firstPage.page.hasMore, true);
    const nextPage = await sellerProductList(listRequest, { status: 'draft', q: 'Paged Test Bag', after: firstPage.page.next });
    assert.equal(nextPage.items.length, 1); assert.equal(nextPage.page.hasMore, false);
    assert.equal(new Set([...firstPage.items, ...nextPage.items].map(row => row.publicId)).size, pageFixtures.length);
    assert.ok([...firstPage.items, ...nextPage.items].every(row => String(row.storeId || store._id) === String(store._id) && row.description === undefined));
    const publishedList = await sellerProductList(listRequest, { status: 'published' });
    assert.equal(publishedList.items.length, 1); assert.equal(publishedList.items[0].publicId, restricted.publicId);
    const exactSearch = await sellerProductList(listRequest, { q: '.*' });
    assert.equal(exactSearch.items.length, 0, 'search input must be literal text rather than executable regular expressions');
  } finally {
    t.mock.restoreAll(); await browser?.close();
    if (server) await new Promise(resolve => server.close(resolve));
    for (const transport of transports) transport.destroy();
    assert.equal(mongoose.connection.name, database);
    await mongoose.connection.dropDatabase(); await mongoose.disconnect();
    await fs.rm(process.env.UPLOAD_DIR, { recursive: true, force: true });
  }
});
