import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';
const read = path => readFile(new URL(`../${path}`, import.meta.url), 'utf8');

test('Stage 5 verifies provider payments before marking orders paid', async()=>{const source=await read('src/services/payments.js');assert.match(source,/verifyFlutterwaveTransaction/);assert.match(source,/amountMinor===intent\.amountMinor/);assert.match(source,/providerReference/);assert.match(source,/order\.status='paid'/);});
test('Stage 5 uses immutable balanced double entry ledger transactions', async()=>{const model=await read('src/models/LedgerTransaction.js');assert.match(model,/debitMinor/);assert.match(model,/creditMinor/);assert.match(model,/d>0&&d===c/);assert.match(model,/Ledger transactions are immutable/);});
test('Stage 5 webhook is HMAC verified and deduplicated without legacy secret-as-signature fallback', async()=>{const service=await read('src/services/payments.js');const routes=await read('src/routes/payments.js');const model=await read('src/models/ProviderEvent.js');assert.match(service,/createHmac\('sha256'/);assert.match(routes,/flutterwave-signature/i);assert.match(service,/WEBHOOK_SIGNATURE_INVALID/);assert.doesNotMatch(service,/signature\s*===\s*env\.flwWebhookSecret/);assert.match(model,/provider:1,eventId:1.*unique:true/s);});
test('Stage 5 keeps raw card data out of Classic Mart', async()=>{const cart=await read('views/cart.ejs');const payment=await read('src/services/payments.js');assert.doesNotMatch(cart,/name="cvv"|name="card_number"|name="cardNumber"/i);assert.match(payment,/\/v3\/payments/);});
test('Stage 5 payout flow reserves balance and requires separate finance approval',async()=>{const service=await read('src/services/payments.js');const routes=await read('src/routes/payments.js');assert.match(service,/payout-hold:/);assert.match(service,/releasePayoutHold/);assert.match(routes,/FOUR_EYES_REQUIRED/);assert.match(routes,/payouts\/:id\/submit/);});
test('Stage 5 supports COD refunds without pretending they are Flutterwave refunds',async()=>{const service=await read('src/services/payments.js');const model=await read('src/models/Refund.js');const routes=await read('src/routes/payments.js');assert.match(model,/cod_manual/);assert.match(service,/completeManualRefund/);assert.match(service,/FOUR_EYES_REQUIRED/);assert.match(service,/cod_clearing/);assert.match(routes,/refunds\/:id\/manual-complete/);});

test('Stage 5 shares seller net-settlement math between provider and COD payments',async()=>{const money=await read('src/services/money.js');const payments=await read('src/services/payments.js');const logistics=await read('src/services/logistics.js');assert.match(money,/sellerSettlementBreakdown/);assert.match(money,/subtotalMinor - appliedDiscountMinor/);assert.match(payments,/sellerSettlementBreakdown\s*}\s*from ['"]\.\/money\.js['"]/);assert.match(payments,/sellerSettlementBreakdown\(sellerOrder\)/);assert.match(logistics,/sellerSettlementBreakdown\s*}\s*from ['"]\.\/money\.js['"]/);assert.match(logistics,/sellerSettlementBreakdown\(sellerOrder\)/);});

test('Stage 5 reloads refund order and payment records inside the refund transaction',async()=>{const service=await read('src/services/payments.js');assert.match(service,/async function postRefundLedger\(orderLike,refund,intentLike\)/);assert.match(service,/Order\.findById\(orderLike\._id\)\.session\(session\)/);assert.match(service,/PaymentIntent\.findById\(intentLike\._id\)\.session\(session\)/);assert.match(service,/LedgerTransaction\.exists\(/);assert.match(service,/\.session\(session\)\)return/);});
