import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const read=p=>fs.readFileSync(new URL(`../${p}`,import.meta.url),'utf8');
test('stage 8 exposes return dispute support review evidence and trust models',()=>{for(const f of ['src/models/ReturnRequest.js','src/models/Dispute.js','src/models/SupportTicket.js','src/models/Review.js','src/models/TrustCase.js','src/models/EvidenceDocument.js','src/models/RiskSignal.js'])assert.equal(fs.existsSync(new URL(`../${f}`,import.meta.url)),true);});
test('returns are tied to real owned orders and enforce purchase-time window and quantities',()=>{const s=read('src/services/trust.js');assert.match(s,/Order\.findOne\(\{publicId:input\.orderId,userId:request\.user\._id\}/);assert.match(s,/RETURN_WINDOW_CLOSED/);assert.match(s,/RETURN_QUANTITY_INVALID/);assert.match(s,/RETURN_ALREADY_OPEN/);assert.match(s,/policySnapshot|returnWindow/i);});
test('support inspection cannot directly post a refund',()=>{const r=read('src/routes/trust.js');assert.match(r,/finance\/returns\/:id\/refund/);assert.match(r,/financeOnly/);assert.match(r,/refund_pending/);assert.match(r,/createRefund/);});
test('verified reviews require purchased order item and block seller self review',()=>{const s=read('src/services/trust.js');assert.match(s,/VERIFIED_PURCHASE_REQUIRED/);assert.match(s,/SELF_REVIEW_BLOCKED/);assert.match(s,/verifiedPurchase:true/);});
test('private evidence uploads use deferred multipart CSRF and sanitized media pipeline',()=>{const r=read('src/routes/trust.js'),m=read('src/services/media.js');assert.match(r,/verifyDeferredCsrf/);assert.match(r,/EvidenceDocument/);assert.match(m,/scanUpload/);assert.match(m,/sharp/);});
test('support and trust queues enforce country scope and preserve timelines',()=>{const s=read('src/services/trust.js'),r=read('src/routes/trust.js');assert.match(s,/supportScope/);assert.match(r,/supportScope\(req\.user\)/);assert.match(r,/operations\/support/);assert.match(r,/disputes\/:id\/status/);assert.match(r,/tickets\/:id\/status/);assert.match(r,/trust\/:id\/status/);});
test('customer trust decisions are visible and appealable from the buyer protection UI',()=>{const r=read('src/routes/trust.js'),v=read('views/returns-workspace.ejs');assert.match(r,/trust-cases\/:id\/appeal/);assert.match(v,/account\/trust-cases\/<%=c\.publicId%>\/appeal/);assert.match(v,/Decision:/);});
test('refund service supports partial refund continuation and COD manual completion',()=>{const s=read('src/services/payments.js');assert.match(s,/\['paid','partially_refunded'\]/);assert.match(s,/REFUND_EXHAUSTED/);assert.match(s,/postRefundLedger/);assert.match(s,/completeManualRefund/);});

test('public Help and Contact requests persist into the support SLA queue',()=>{const r=read('src/routes/trust.js'),s=read('src/services/trust.js'),h=read('views/help.ejs'),c=read('views/contact.ejs');assert.match(r,/\/support\/request/);assert.match(r,/createPublicSupportTicket/);assert.match(s,/createPublicSupportTicket/);assert.match(h,/action="\/support\/request"/);assert.match(c,/action="\/support\/request"/);});
