import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const read=p=>fs.readFileSync(new URL(`../${p}`,import.meta.url),'utf8');
test('stage 7 exposes delivery offers parcels shipment and executable warehouse models',()=>{for(const f of ['src/models/DeliveryProfile.js','src/models/ShippingZone.js','src/models/Shipment.js','src/models/DeliveryOffer.js','src/models/Parcel.js','src/models/WarehouseTask.js','src/models/OperationAction.js'])assert.equal(fs.existsSync(new URL(`../${f}`,import.meta.url)),true);});
test('shipment transitions require controlled state changes OTP proof and fulfilled parcel handoff',()=>{const s=read('src/services/logistics.js');assert.match(s,/allowedTransitions/);assert.match(s,/verifyProofCode/);assert.match(s,/PROOF_INVALID/);assert.match(s,/PARCEL_HANDOFF_REQUIRED/);assert.match(s,/return_to_sender/);});
test('shipment proof secrets are encrypted and customer scoped',()=>{const s=read('src/services/logistics.js'),r=read('src/routes/checkout.js');assert.match(s,/encryptSensitive\(pickup\)/);assert.match(s,/encryptSensitive\(delivery\)/);assert.match(r,/getOrderForRequest/);assert.match(r,/deliveryCodeEncrypted/);});
test('confirmed payment creates fulfilment shipment and seller parcels',()=>{const p=read('src/services/payments.js'),l=read('src/services/logistics.js');assert.match(p,/ensureShipmentForOrder/);assert.match(p,/commitOrderInventoryAndMoney/);assert.match(l,/Parcel/);});
test('warehouse operations execute inventory/parcel transitions and COD reconciliation',()=>{const r=read('src/routes/logistics.js'),s=read('src/services/logistics.js');for(const term of [/receive/,/put_away/,/pick/,/pack/,/dispatch/,/transfer/,/return_inspection/])assert.match(s,term);assert.match(r,/reconcile-cod/);assert.match(s,/reconcileCod/);});
test('delivery offline queue is idempotent and server re-authorized',()=>{const js=read('public/delivery-offline.js');const r=read('src/routes/logistics.js');assert.match(js,/indexedDB/);assert.match(js,/408, 429/);assert.match(js,/error\.status >= 400/);assert.match(r,/OperationAction/);assert.match(r,/clientActionId/);});
test('country scope is enforced for logistics operations',()=>{const r=read('src/routes/logistics.js');assert.match(r,/countryScope/);assert.match(r,/COUNTRY_SCOPE/);assert.match(r,/warehouseIds/);});

test('COD reconciliation reloads trusted records inside its transaction and keeps batch failure evidence',()=>{const s=read('src/services/logistics.js');assert.match(s,/Shipment\.findById\(shipment\._id\)\.session\(session\)/);assert.match(s,/Order\.findById\(currentShipment\.orderId\)\.session\(session\)/);assert.match(s,/PaymentIntent\.findOne\(\{ orderId: order\._id, provider: 'cod', status: 'pending_collection' \}\)\.session\(session\)/);assert.match(s,/reconciliationRunId:run\.publicId/);});
