
(() => {
 'use strict';
 const $=s=>document.querySelector(s);
 const save=(key,value)=>{try{localStorage.setItem(key,JSON.stringify(value));}catch{}};
 const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key)||'null')??fallback}catch{return fallback}};
 document.querySelectorAll('[data-apply-role]').forEach(button=>button.addEventListener('click',()=>{const form=$('#careerForm');form.hidden=false;$('#careerRole').value=button.dataset.applyRole;form.scrollIntoView({behavior:'smooth'});}));
 ['#careerForm','#contactForm','#helpPageForm'].forEach(selector=>$(selector)?.addEventListener('submit',event=>{event.preventDefault();const data=Object.fromEntries(new FormData(event.currentTarget));const key=selector==='#careerForm'?'classic-mart-career-applications':selector==='#contactForm'?'classic-mart-contact-messages':'classic-mart-support-requests';const list=read(key,[]);list.unshift({...data,createdAt:new Date().toISOString()});save(key,list.slice(0,20));event.currentTarget.querySelector('.form-status').textContent='Your request has been recorded in this demonstration.';event.currentTarget.reset();}));
 $('#trackPageForm')?.addEventListener('submit',event=>{event.preventDefault();const number=$('#trackPageInput').value.trim().toUpperCase();const orders=read('classic-mart-orders',[]);const order=orders.find(item=>String(item.orderNumber).toUpperCase()===number);const target=$('#trackingPageResult');if(order){target.innerHTML=`<span class="tracking-icon"><img src="assets/icons/circle-check.svg" alt=""></span><div><span class="info-kicker">Order found</span><h2>${order.orderNumber} · ${order.status||'Order confirmed'}</h2><p>${order.items?.length||0} item(s) for ${order.customer?.name||'Classic Mart shopper'}. Total: $${Number(order.totals?.total||0).toFixed(2)}.</p><div class="tracking-timeline"><span class="done"><i></i>Order confirmed</span><span class="done"><i></i>Preparing for fulfilment</span><span><i></i>Carrier update pending</span><span><i></i>Delivered</span></div></div>`;}else if(number==='CM-20491'){target.innerHTML='<span class="tracking-icon"><img src="assets/icons/truck-fast.svg" alt=""></span><div><span class="info-kicker">In transit</span><h2>CM-20491 is on the way</h2><p>The demonstration shipment has left the fulfilment centre and is expected within 2 business days.</p><div class="tracking-timeline"><span class="done"><i></i>Order confirmed</span><span class="done"><i></i>Dispatched</span><span class="done"><i></i>In transit</span><span><i></i>Delivered</span></div></div>';}else{target.innerHTML='<span class="tracking-icon"><img src="assets/icons/box.svg" alt=""></span><div><h2>Order not found</h2><p>Check the order number and try again. Demo checkout orders remain available in the same browser.</p></div>';}});
})();
