(() => {
'use strict';
const $=s=>document.querySelector(s), steps=[...document.querySelectorAll('[data-role-step]')], dots=[...document.querySelectorAll('.role-step-label i')];let step=0,role='';
const roleInfo={customer:{label:'Customer',next:'Start shopping',destination:'profile.html',title:'Build your shopping preferences.',description:'Choose the departments and delivery details that matter most to you.'},seller:{label:'Seller',next:'Prepare your storefront',destination:'seller-profile.html?owner=1',title:'Prepare your seller identity.',description:'Add the basic information customers will see on your seller profile.'},promoter:{label:'Promoter',next:'Create your promoter profile',destination:'promoter-profile.html?owner=1',title:'Shape your promoter profile.',description:'Tell shoppers what you recommend and where your audience follows you.'},business:{label:'Business Buyer',next:'Set up business purchasing',destination:'profile.html?mode=business',title:'Set up your organisation profile.',description:'Add information that helps organise repeat and bulk purchases.'},delivery:{label:'Delivery Partner',next:'Review delivery tools',destination:'profile.html?mode=delivery',title:'Set up your delivery profile.',description:'Choose your service area and the type of delivery work you handle.'}};
function read(k,f){try{const v=localStorage.getItem(k);return v?JSON.parse(v):f}catch{return f}}function write(k,v){try{localStorage.setItem(k,JSON.stringify(v));return true}catch{return false}}
const user=read('classic-mart-user',{})||{}, session=read('classic-mart-session',{})||{};$('#welcomeName').textContent=(user.name||session.name||'new member').split(' ')[0];
const requested=new URLSearchParams(location.search).get('role');if(roleInfo[requested]){const input=document.querySelector(`[name="accountRole"][value="${requested}"]`);if(input)input.checked=true;role=requested}
function detailsTemplate(selected){const common=`<div class="role-form-grid"><label class="role-field">Public profile name<input name="profileName" required value="${user.name||session.name||''}" placeholder="Name shown on your profile"></label>`;const end='</div>';
if(selected==='seller')return common+`<label class="role-field">Store name<input name="businessName" required placeholder="e.g. Awan Electronics"></label><label class="role-field">Main product category<select name="focus" required><option value="">Choose a category</option><option>Electronics</option><option>Fashion</option><option>Home & Kitchen</option><option>Beauty & Wellness</option><option>Books & Stationery</option><option>Other</option></select></label><label class="role-field">Business location<input name="location" required placeholder="City, country"></label><label class="role-field full">Store description<textarea name="bio" rows="4" required placeholder="What do you sell and why should customers choose your store?"></textarea></label>`+end;
if(selected==='promoter')return common+`<label class="role-field">Promoter or channel name<input name="businessName" required placeholder="e.g. Awan Finds"></label><label class="role-field">Main content niche<select name="focus" required><option value="">Choose a niche</option><option>Technology</option><option>Fashion & Beauty</option><option>Home & Lifestyle</option><option>Fitness & Outdoors</option><option>Deals & Shopping</option><option>Education</option></select></label><label class="role-field">Social handle<input name="handle" required placeholder="@yourhandle"></label><label class="role-field full">About your audience<textarea name="bio" rows="4" required placeholder="Describe the products and people your recommendations serve."></textarea></label>`+end;
if(selected==='business')return common+`<label class="role-field">Organisation name<input name="businessName" required placeholder="Company, school or organisation"></label><label class="role-field">Team size<select name="teamSize" required><option value="">Choose team size</option><option>1–5</option><option>6–20</option><option>21–100</option><option>100+</option></select></label><label class="role-field full">Primary buying needs<input name="focus" required placeholder="Office supplies, technology, uniforms..."></label><label class="role-field full">Delivery location<input name="location" required placeholder="City, country"></label>`+end;
if(selected==='delivery')return common+`<label class="role-field">Service area<input name="location" required placeholder="City or districts served"></label><label class="role-field">Transport mode<select name="transport" required><option value="">Choose transport</option><option>Motorcycle</option><option>Bicycle</option><option>Car</option><option>Van / truck</option><option>Delivery team</option></select></label><label class="role-field">Working phone<input name="deliveryPhone" required value="${user.phone||session.phone||''}" placeholder="Phone number"></label><label class="role-field">Availability<select name="availability" required><option>Full time</option><option>Part time</option><option>Weekends</option><option>On demand</option></select></label>`+end;
return common+`<label class="role-field">Delivery city<input name="location" required placeholder="City, country"></label><div class="role-field full"><span>Favourite departments</span><div class="role-choice-list"><label><input type="checkbox" name="interests" value="Electronics"><span>Electronics</span></label><label><input type="checkbox" name="interests" value="Fashion"><span>Fashion</span></label><label><input type="checkbox" name="interests" value="Home"><span>Home & Kitchen</span></label><label><input type="checkbox" name="interests" value="Beauty"><span>Beauty</span></label><label><input type="checkbox" name="interests" value="Sports"><span>Sports</span></label><label><input type="checkbox" name="interests" value="Books"><span>Books</span></label></div></div><label class="role-field full">Shopping preference<select name="focus" required><option>Best value and deals</option><option>Premium products</option><option>New arrivals</option><option>Local sellers</option><option>Fast delivery</option></select></label>`+end}
function show(next){step=Math.max(0,Math.min(2,next));steps.forEach((el,i)=>{el.hidden=i!==step;el.classList.toggle('active',i===step)});dots.forEach((d,i)=>d.classList.toggle('active',i<=step));$('#stepLabel').textContent=`Step ${step+1} of 3`;$('#roleBack').disabled=step===0;$('#roleNext').innerHTML=step===2?'Open my profile <img src="assets/icons/chevron-right.svg" alt="">':'Continue <img src="assets/icons/chevron-right.svg" alt="">';window.scrollTo({top:0,behavior:'smooth'})}
function collect(){const data={};new FormData($('#roleOnboardingForm')).forEach((v,k)=>{if(k==='accountRole')return;if(data[k])data[k]=[].concat(data[k],v);else data[k]=v});return data}
function prepareDetails(){const checked=document.querySelector('[name="accountRole"]:checked');if(!checked){toast('Choose a role to continue');return false}role=checked.value;const info=roleInfo[role];$('#detailsTitle').textContent=info.title;$('#detailsDescription').textContent=info.description;$('#roleDetailsPanel').innerHTML=detailsTemplate(role);return true}
function prepareSummary(){const panel=$('#roleDetailsPanel');if(!panel.querySelectorAll('input,select,textarea').length||![...panel.querySelectorAll('[required]')].every(el=>el.reportValidity()))return false;const info=roleInfo[role],data=collect();$('#summaryRole').textContent=info.label;$('#summaryName').textContent=data.businessName||data.profileName||user.name||'Classic Mart member';$('#summaryNext').textContent=info.next;$('#roleSummary').textContent=`Your ${info.label.toLowerCase()} profile will use these details to show the right marketplace tools and information.`;return true}
function finish(){const info=roleInfo[role],details=collect();const updated={...user,name:user.name||details.profileName||session.name||'Classic Mart member',email:user.email||session.email||'',phone:user.phone||session.phone||'',role,roleLabel:info.label,roleProfile:details,onboardingCompletedAt:new Date().toISOString()};write('classic-mart-user',updated);write('classic-mart-session',{...session,name:updated.name,email:updated.email,phone:updated.phone,role,roleLabel:info.label,signedInAt:session.signedInAt||new Date().toISOString()});write('classic-mart-onboarding-complete',true);location.href=info.destination}
function toast(message){const t=$('#pageToast');t.textContent=message;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),2200)}
$('#roleNext').addEventListener('click',()=>{if(step===0){if(prepareDetails())show(1)}else if(step===1){if(prepareSummary())show(2)}else finish()});$('#roleBack').addEventListener('click',()=>show(step-1));document.querySelectorAll('[name="accountRole"]').forEach(input=>input.addEventListener('change',()=>role=input.value));show(0);
})();