(() => {
'use strict';
const promoters=[
    ['Amina Style','Fashion & beauty','Trusted fashion editor sharing wearable looks and practical beauty finds.','https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=700&q=86',['Fashion','Beauty'],4.9,'84K','1.2K','fashion'],
    ['Daniel Tech','Electronics','Clear gadget comparisons, setup guides and dependable everyday technology picks.','https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=700&q=86',['Tech','Audio'],4.8,'67K','948','electronics'],
    ['Nadia Home','Home ideas','Space-saving home products, kitchen tools and simple room refresh ideas.','https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=700&q=86',['Home','Kitchen'],4.9,'52K','776','home'],
    ['Musa Fitness','Sports','Fitness essentials, training accessories and realistic beginner-friendly recommendations.','https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=700&q=86',['Sports','Fitness'],4.7,'46K','605','sports'],
    ['Grace Finds','Daily deals','Value-focused marketplace finds with clear reasons each deal is worth considering.','https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=700&q=86',['Deals','Lifestyle'],4.8,'73K','1.0K','beauty'],
    ['Leo Outdoors','Travel gear','Practical travel, hiking and outdoor products selected for comfort and durability.','https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=700&q=86',['Travel','Outdoor'],4.7,'39K','512','sports'],
    ['Ruth Beauty','Skin care','Gentle skin-care routines and transparent product explanations for everyday use.','https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=700&q=86',['Skin care','Wellness'],4.9,'58K','889','beauty'],
    ['Peter Auto','Automotive','Useful vehicle accessories, maintenance tools and organized car essentials.','https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?auto=format&fit=crop&w=700&q=86',['Auto','Tools'],4.6,'31K','430','automotive'],
    ['Eva Books','Books & learning','Books, stationery and learning resources for students, families and professionals.','https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=700&q=86',['Books','Learning'],4.8,'44K','692','books'],
    ['Samuel Select','Marketplace picks','Balanced product roundups covering useful items across the whole marketplace.','https://images.unsplash.com/photo-1507591064344-4c6ce005b128?auto=format&fit=crop&w=700&q=86',['Popular','Mixed'],4.7,'61K','804','all']
  ];
const sellers=[
    ['Classic Electronics','Verified electronics seller','Phones, audio, accessories and reliable everyday technology.','https://images.unsplash.com/photo-1560472354-b33ff0c44a43?auto=format&fit=crop&w=700&q=86',['Electronics','Warranty'],4.9,'12K','8.4K','electronics'],
    ['Urban Style House','Fashion marketplace seller','Modern clothing, shoes and accessories with clear sizing information.','https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=700&q=86',['Fashion','Fast dispatch'],4.8,'9.8K','6.7K','fashion'],
    ['HomeNest Store','Home & kitchen seller','Furniture, kitchen tools and décor selected for practical homes.','https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=700&q=86',['Home','Kitchen'],4.8,'7.6K','5.3K','home'],
    ['GlowCare Market','Beauty & wellness seller','Skin care, personal care and beauty essentials from trusted brands.','https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=700&q=86',['Beauty','Wellness'],4.7,'6.1K','4.8K','beauty'],
    ['ActiveLife Shop','Sports seller','Fitness, outdoor and recreation products for active routines.','https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=700&q=86',['Sports','Outdoor'],4.7,'5.4K','3.9K','sports'],
    ['BookPoint','Books & stationery seller','Learning resources, office stationery and books for every age.','https://images.unsplash.com/photo-1526243741027-444d633d7365?auto=format&fit=crop&w=700&q=86',['Books','Stationery'],4.9,'4.9K','3.5K','books'],
    ['AutoPro Supplies','Automotive seller','Vehicle accessories, cleaning products and maintenance essentials.','https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?auto=format&fit=crop&w=700&q=86',['Automotive','Tools'],4.6,'4.1K','2.8K','automotive'],
    ['Fresh Basket','Grocery seller','Pantry staples and household essentials with organized fulfilment.','https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=700&q=86',['Grocery','Household'],4.8,'8.2K','6.1K','grocery'],
    ['PetJoy Store','Pet supplies seller','Food, care and play essentials for cats, dogs and small pets.','https://images.unsplash.com/photo-1601758228041-f3b2795255f1?auto=format&fit=crop&w=700&q=86',['Pets','Care'],4.7,'3.8K','2.4K','pets'],
    ['ToyBox World','Toys & games seller','Creative play, family games and age-friendly children’s products.','https://images.unsplash.com/photo-1594787318286-3d835c1d207f?auto=format&fit=crop&w=700&q=86',['Toys','Games'],4.8,'5.7K','4.0K','toys']
  ];
const $=s=>document.querySelector(s);function read(k,f){try{const v=localStorage.getItem(k);return v?JSON.parse(v):f}catch{return f}}function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}const isSeller=location.pathname.includes('seller-profile'),source=isSeller?sellers:promoters,key=isSeller?'seller':'promoter',owner=new URLSearchParams(location.search).get('owner')==='1';let index=Math.max(0,Math.min(source.length-1,Number(new URLSearchParams(location.search).get(key))||0));let item=source[index];
if(owner){const u=read('classic-mart-user',{}),d=u.roleProfile||{},name=d.businessName||d.profileName||u.name||item[0],role=isSeller?'Owner-managed seller profile':'Owner-managed promoter profile',bio=d.bio||item[2],tags=[d.focus||item[4][0],isSeller?'Verified business':'Growing creator'];item=[name,role,bio,item[3],tags,4.8,isSeller?'0':'0',isSeller?'0':'0',(d.focus||item[8]).toLowerCase().split(' ')[0]]}
document.title=`${item[0]} — Classic Mart`;$('#profileAvatar').src=item[3];$('#profileAvatar').alt=item[0];$('#profileName').textContent=item[0];$('#profileRole').textContent=item[1];$('#profileBio').textContent=item[2];$('#profileShortName').textContent=item[0];$('#profileTags').innerHTML=item[4].map(t=>`<span>${esc(t)}</span>`).join('');$('#profileMetrics').innerHTML=`<span><strong>${item[5]}</strong><small>Rating</small></span><span><strong>${item[6]}</strong><small>${isSeller?'Orders':'Followers'}</small></span><span><strong>${item[7]}</strong><small>${isSeller?'Products':'Curated picks'}</small></span>`;$('#profileAboutTitle').textContent=isSeller?'About this seller':'About this promoter';$('#profileCollectionTitle').textContent=isSeller?'Products from this seller':'Recommended by this promoter';$('#profileAllProducts').href=`products.html?category=${item[8]}`;
const products=[['Essential marketplace pick',29.99,'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=600&q=82'],['Customer favourite',64.50,'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=82'],['New collection item',42.00,'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=600&q=82']];$('#profileProducts').innerHTML=products.map(p=>`<article class="profile-product"><img src="${p[2]}" alt="${p[0]}"><div><h3>${p[0]}</h3><span><strong>$${p[1].toFixed(2)}</strong><a href="products.html?category=${item[8]}" aria-label="View product"><img src="assets/icons/chevron-right.svg" alt=""></a></span></div></article>`).join('');
const about=$('#profileBio').closest('.profile-card');about.insertAdjacentHTML('afterend',`<article class="profile-card profile-rich-card"><div class="profile-section-head"><div><span class="profile-kicker">Profile details</span><h2>${isSeller?'Store performance and service':'Audience and collaboration'}</h2></div><span class="profile-online"><i></i>Active today</span></div><div class="profile-detail-grid"><span><img src="assets/icons/location-dot.svg" alt=""><b>Location</b><small>${owner?(read('classic-mart-user',{}).roleProfile?.location||'Kampala, Uganda'):'Kampala, Uganda'}</small></span><span><img src="assets/icons/bolt.svg" alt=""><b>Response time</b><small>${isSeller?'Usually within 2 hours':'Usually within 4 hours'}</small></span><span><img src="assets/icons/box.svg" alt=""><b>${isSeller?'Fulfilment':'Publishing'}</b><small>${isSeller?'Same or next business day':'3–5 quality picks weekly'}</small></span><span><img src="assets/icons/circle-check.svg" alt=""><b>Member since</b><small>2024 · Verified by Classic Mart</small></span></div></article>`);
const collection=$('#profileProducts').closest('.profile-card');collection.insertAdjacentHTML('afterend',`<article class="profile-card"><div class="profile-section-head"><div><span class="profile-kicker">Trust and reputation</span><h2>Recent customer feedback</h2></div><strong class="profile-review-score">${item[5]} / 5</strong></div><div class="profile-review-list"><blockquote><div><b>★★★★★</b><time>2 days ago</time></div><p>Clear product information, quick answers and a smooth experience from start to finish.</p><footer>— Verified Classic Mart customer</footer></blockquote><blockquote><div><b>★★★★★</b><time>1 week ago</time></div><p>${isSeller?'The order was prepared quickly and arrived exactly as described.':'The recommendation was useful, honest and easy to compare with other options.'}</p><footer>— Marketplace member</footer></blockquote></div><div class="profile-achievements"><span><img src="assets/icons/circle-check.svg" alt=""><b>Verified identity</b></span><span><img src="assets/icons/heart.svg" alt=""><b>Customer favourite</b></span><span><img src="assets/icons/bolt.svg" alt=""><b>Fast response</b></span></div></article>`);
const sidebar=$('.profile-sidebar');sidebar.insertAdjacentHTML('beforeend',`<article class="profile-card profile-side-info"><span class="profile-kicker">At a glance</span><h2>${isSeller?'Store policies':'Collaboration details'}</h2><div><p><img src="assets/icons/rotate-left.svg" alt=""><span><b>${isSeller?'7-day returns':'Transparent recommendations'}</b><small>${isSeller?'Eligible items can be returned within 7 days.':'Paid and organic picks are clearly explained.'}</small></span></p><p><img src="assets/icons/headset.svg" alt=""><span><b>Before and after support</b><small>Questions are welcome throughout your marketplace journey.</small></span></p><p><img src="assets/icons/lock.svg" alt=""><span><b>Buyer-first standards</b><small>Activity follows Classic Mart marketplace policies.</small></span></p></div></article>`);
let following=false;$('#followProfile').addEventListener('click',e=>{following=!following;e.currentTarget.innerHTML=`<img src="assets/icons/${following?'heart':'heart-regular'}.svg" alt="">${following?'Following':'Follow'}`});$('#shareProfile').addEventListener('click',async()=>{const url=location.href;try{await navigator.clipboard.writeText(url);toast('Profile link copied')}catch{prompt('Copy this profile link:',url)}});$('#profileContactForm').addEventListener('submit',e=>{e.preventDefault();$('#profileContactStatus').textContent='Message prepared. A live backend would deliver it to this profile.';e.currentTarget.reset()});function toast(m){const t=$('#pageToast');if(!t)return;t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
})();