(() => {
'use strict';
const products=[
{id:1,name:'Wireless Earbuds',subtitle:'Premium Sound',category:'Electronics',image:'https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?auto=format&fit=crop&w=900&q=84',price:29.99,oldPrice:64.99,rating:4.8,reviews:4820,stock:54},
{id:2,name:'Travel Backpack',subtitle:'Water Resistant',category:'Fashion',image:'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=84',price:39.99,oldPrice:49.99,rating:4.7,reviews:2140,stock:31},
{id:3,name:'Smart Watch',subtitle:'Fitness Tracker',category:'Electronics',image:'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=84',price:89.99,oldPrice:129.99,rating:4.9,reviews:3410,stock:67},
{id:4,name:'Portable Blender',subtitle:'USB Rechargeable',category:'Home & Kitchen',image:'https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=900&q=84',price:25.49,oldPrice:29.99,rating:4.5,reviews:1230,stock:44},
{id:5,name:"Men's Sneakers",subtitle:'Comfort & Style',category:'Fashion',image:'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=84',price:49.99,oldPrice:79.99,rating:4.8,reviews:2740,stock:38},
{id:6,name:'Luxury Perfume',subtitle:'Long Lasting',category:'Beauty',image:'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=900&q=84',price:36.99,oldPrice:64.99,rating:4.6,reviews:2410,stock:22},
{id:7,name:'Non-Stick Cookware',subtitle:'10-Piece Set',category:'Home & Kitchen',image:'https://images.unsplash.com/photo-1584990347449-a4ecad58a21d?auto=format&fit=crop&w=900&q=84',price:79.99,oldPrice:99.99,rating:4.7,reviews:3720,stock:18},
{id:8,name:'Hydration Bottle',subtitle:'Smart Temperature Display',category:'Sports',image:'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=900&q=84',price:22.99,oldPrice:31.99,rating:4.5,reviews:760,stock:82},
{id:9,name:'Coffee Maker',subtitle:'Programmable Brew',category:'Home & Kitchen',image:'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=84',price:59.99,oldPrice:79.99,rating:4.8,reviews:980,stock:26},
{id:10,name:'Noise Cancelling Headphones',subtitle:'Studio Wireless',category:'Electronics',image:'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=84',price:89.99,oldPrice:149.99,rating:4.9,reviews:4130,stock:43},
{id:11,name:'Bluetooth Speaker',subtitle:'Portable Bass',category:'Electronics',image:'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=900&q=84',price:25.99,oldPrice:39.99,rating:4.6,reviews:1720,stock:71},
{id:12,name:'LED Desk Lamp',subtitle:'Touch Control',category:'Home & Kitchen',image:'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=900&q=84',price:19.99,oldPrice:24.99,rating:4.5,reviews:540,stock:61}
];
const $=s=>document.querySelector(s); let saved=read('shophub-wishlist',[]).map(Number).filter(Boolean); let sort='recent';
function read(k,f){try{const v=localStorage.getItem(k);return v?JSON.parse(v):f}catch{return f}}
function write(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch{} try{window.dispatchEvent(new CustomEvent('classic-mart-wishlist-change',{detail:v}))}catch{}}
function money(v){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(v)}
function toast(message){const t=$('#pageToast');if(!t)return;t.textContent=message;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),2200)}
function product(id){return products.find(p=>p.id===Number(id))}
function card(p,canRemove=true){return `<article class="wishlist-card"><a class="wishlist-card-image" href="index.html?product=${p.id}#trending"><img src="${p.image}" alt="${p.name}" loading="lazy" referrerpolicy="no-referrer"></a>${canRemove?`<button class="wishlist-remove" data-remove-wishlist="${p.id}" aria-label="Remove ${p.name}"><img src="assets/icons/xmark.svg" alt=""></button>`:''}<div class="wishlist-card-body"><span class="wishlist-card-badge">${p.stock>0?'In stock':'Unavailable'}</span><h3>${p.name}</h3><p class="wishlist-card-subtitle">${p.subtitle}</p><div class="wishlist-rating"><b>★★★★★</b><span>${p.rating} (${p.reviews.toLocaleString()})</span></div><div class="wishlist-pricing"><strong>${money(p.price)}</strong><del>${money(p.oldPrice)}</del></div><div class="wishlist-card-actions"><button data-wishlist-cart="${p.id}"><img src="assets/icons/cart-plus.svg" alt="">Add to cart</button><a href="index.html?product=${p.id}#trending" aria-label="View ${p.name}"><img src="assets/icons/chevron-right.svg" alt=""></a></div></div></article>`}
function sorted(list){return [...list].sort((a,b)=>sort==='price-low'?a.price-b.price:sort==='price-high'?b.price-a.price:sort==='rating'?b.rating-a.rating:sort==='saving'?(b.oldPrice-b.price)-(a.oldPrice-a.price):saved.indexOf(b.id)-saved.indexOf(a.id))}
function render(){const list=sorted(saved.map(product).filter(Boolean));$('#wishlistGrid').innerHTML=list.map(p=>card(p)).join('');$('#wishlistGrid').hidden=!list.length;$('#wishlistEmpty').hidden=!!list.length;$('#wishlistTotal').textContent=String(list.length);$('#wishlistSavings').textContent=money(list.reduce((s,p)=>s+Math.max(0,p.oldPrice-p.price),0));$('#wishlistAvailable').textContent=String(list.filter(p=>p.stock>0).length);const rec=products.filter(p=>!saved.includes(p.id)).slice(0,4);$('#wishlistRecommendations').innerHTML=rec.map(p=>card(p,false)).join('');document.querySelectorAll('[data-wishlist-count]').forEach(el=>el.textContent=String(saved.length));}
function addCart(p){if(!p)return;if(window.ClassicMartCart)window.ClassicMartCart.add(p,1);else{const cart=read('shophub-cart',{});cart[p.id]=(Number(cart[p.id])||0)+1;write('shophub-cart',cart)}toast(`${p.name} added to cart`)}
document.addEventListener('click',e=>{const remove=e.target.closest('[data-remove-wishlist]');if(remove){saved=saved.filter(id=>id!==Number(remove.dataset.removeWishlist));write('shophub-wishlist',saved);render();toast('Product removed from wishlist');return}const add=e.target.closest('[data-wishlist-cart]');if(add){addCart(product(add.dataset.wishlistCart));return}});
$('#wishlistSort')?.addEventListener('change',e=>{sort=e.target.value;render()});
$('#clearWishlist')?.addEventListener('click',()=>{if(!saved.length)return toast('Your wishlist is already empty');saved=[];write('shophub-wishlist',saved);render();toast('Wishlist cleared')});
$('#addAllWishlist')?.addEventListener('click',()=>{const list=saved.map(product).filter(Boolean);if(!list.length)return toast('Save products before adding them to your cart');list.forEach(addCart);toast(`${list.length} products added to cart`)});
render();
})();