import { Router } from 'express';
import rateLimit from 'express-rate-limit';
import multer from 'multer';
import sharp from 'sharp';
import { z } from 'zod';
import { AppError } from '../core/errors.js';
import { requireAuth, requireOnboarding, requirePermission, requireVerified } from '../middleware/auth.js';
import { verifyDeferredCsrf } from '../middleware/csrf.js';
import { loadSellerStore, requireStoreCapability } from '../middleware/store.js';
import { noStore } from '../middleware/request.js';
import { setFlash } from '../middleware/view.js';
import {
  AiEvaluationRun,AiJob,AiModelRegistry,AiPromptVersion,Campaign,CampaignApplication,Product,SupportTicket,TrustCase,
} from '../models/index.js';
import {
  aiObservability,applyCartDraft,approveSellerAiJob,approveSupportAiJob,askClassic,hybridSearch,latestReviewSummary,
  queueAiJob,recommendationsFor,rejectAiJob,runEvaluationSuite,similarProducts,submitAiFeedback,
} from '../services/ai.js';
import { describeImage } from '../services/ai-provider.js';
import { scanUpload } from '../services/malware.js';
import { writeAudit } from '../services/audit.js';
import { createApproval } from '../services/stage9.js';

const router=Router();
const aiLimit=rateLimit({windowMs:60_000,limit:20,standardHeaders:'draft-8',legacyHeaders:false});
const imageUpload=multer({storage:multer.memoryStorage(),limits:{fileSize:5*1024*1024,files:1,fields:4},fileFilter(_req,file,cb){if(!['image/jpeg','image/png','image/webp','image/avif'].includes(file.mimetype))return cb(new AppError('Upload a JPEG, PNG, WebP or AVIF image.',422,'AI_IMAGE_TYPE_INVALID'));cb(null,true);}}).single('image');
const supportRoles=new Set(['support','country_admin','super_admin']);
const adminRoles=new Set(['country_admin','super_admin']);
function supportOnly(req,_res,next){return supportRoles.has(req.user?.role)?next():next(new AppError('Support access required.',403,'FORBIDDEN'));}
function adminOnly(req,_res,next){return adminRoles.has(req.user?.role)?next():next(new AppError('Administrator access required.',403,'FORBIDDEN'));}
function countryScope(req){return req.user.role==='country_admin'?{country:req.user.country}:{};}
function requireAiFeature(key){return (req,_res,next)=>req.features?.[key]===false?next(new AppError('This Classic AI feature is not enabled for your account/country.',404,'AI_FEATURE_DISABLED')):next();}

router.get('/ask-classic',noStore,requireAiFeature('classic_ai.ask'),async(req,res,next)=>{try{const recommendations=await recommendationsFor(req,{limit:8});res.render('ask-classic',{result:null,recommendations,visualResults:[],question:''});}catch(e){next(e);}});
router.post('/ask-classic',noStore,aiLimit,requireAiFeature('classic_ai.ask'),async(req,res,next)=>{try{const input=z.object({question:z.string().trim().min(2).max(2000)}).parse(req.body);const [result,recommendations]=await Promise.all([askClassic(req,input.question),recommendationsFor(req,{limit:8})]);res.render('ask-classic',{result,recommendations,visualResults:[],question:input.question});}catch(e){next(e);}});
router.post('/ask-classic/cart-drafts/:id/apply',noStore,async(req,res,next)=>{try{await applyCartDraft(req,req.params.id);setFlash(req,'success','AI cart draft was revalidated against live stock and added to your server cart.');res.redirect('/cart');}catch(e){next(e);}});
router.post('/api/v1/ai/feedback',aiLimit,async(req,res,next)=>{try{const input=z.object({usageId:z.string().min(4).max(120),rating:z.enum(['helpful','not_helpful','incorrect','unsafe']),comment:z.string().trim().max(1000).optional().default('')}).parse(req.body);res.status(201).json({feedback:await submitAiFeedback(req,input)});}catch(e){next(e);}});
router.post('/ask-classic/feedback',noStore,aiLimit,async(req,res,next)=>{try{const input=z.object({usageId:z.string().min(4).max(120),rating:z.enum(['helpful','not_helpful','incorrect','unsafe']),comment:z.string().trim().max(1000).optional().default('')}).parse(req.body);await submitAiFeedback(req,input);setFlash(req,'success','Thanks. Your AI feedback was recorded for evaluation.');res.redirect('/ask-classic');}catch(e){next(e);}});
router.get('/api/v1/ai/search',aiLimit,async(req,res,next)=>{try{const input=z.object({q:z.string().trim().min(1).max(120),category:z.string().max(100).optional().default(''),brand:z.string().max(100).optional().default(''),seller:z.string().max(100).optional().default('')}).parse(req.query);res.json(await hybridSearch(req.country,{query:input.q,category:input.category,brand:input.brand,seller:input.seller,limit:40}));}catch(e){next(e);}});
router.get('/api/v1/ai/products/:id/similar',aiLimit,async(req,res,next)=>{try{res.json({products:await similarProducts(req.country,req.params.id,{limit:12})});}catch(e){next(e);}});
router.get('/api/v1/ai/recommendations',aiLimit,async(req,res,next)=>{try{res.set('Cache-Control','private, no-store').json({products:await recommendationsFor(req,{limit:12})});}catch(e){next(e);}});
router.get('/api/v1/ai/products/:id/review-summary',aiLimit,async(req,res,next)=>{try{res.json({summary:await latestReviewSummary(req.country,req.params.id)});}catch(e){next(e);}});
router.post('/ask-classic/visual',noStore,aiLimit,requireAiFeature('classic_ai.ask'),imageUpload,async(req,res,next)=>{try{verifyDeferredCsrf(req);if(!req.file?.buffer)throw new AppError('Choose a product image.',422,'AI_IMAGE_REQUIRED');await scanUpload(req.file.buffer);const normalized=await sharp(req.file.buffer,{failOn:'warning',limitInputPixels:25_000_000}).rotate().resize({width:768,height:768,fit:'inside',withoutEnlargement:true}).jpeg({quality:80}).toBuffer();const described=await describeImage({dataUrl:`data:image/jpeg;base64,${normalized.toString('base64')}`,instructions:'Describe only visible product/category/style/material/color/function details useful for shopping search.',country:req.country.code,role:req.user?.role||'customer'});const results=await hybridSearch(req.country,{query:described.text,limit:16});const recommendations=await recommendationsFor(req,{limit:8});res.render('ask-classic',{result:null,recommendations,visualResults:results.products,question:`Visual search: ${described.text}`});}catch(e){next(e);}});

router.post('/promoter/ai/jobs',noStore,aiLimit,requireAiFeature('classic_ai.promoter'),requireAuth,requireVerified,requirePermission('promoter:manage'),async(req,res,next)=>{try{const input=z.object({campaignId:z.string().min(4).max(120),channel:z.string().trim().max(50).optional().default(''),brief:z.string().trim().min(3).max(3000)}).parse(req.body);const campaign=await Campaign.findOne({publicId:input.campaignId,country:req.user.country,status:'active'});if(!campaign)throw new AppError('Active campaign not found.',404,'CAMPAIGN_NOT_FOUND');const application=await CampaignApplication.findOne({campaignId:campaign._id,promoterUserId:req.user._id,status:'approved'}).lean();if(!application)throw new AppError('Campaign approval is required before AI content can be generated.',403,'CAMPAIGN_APPROVAL_REQUIRED');const job=await queueAiJob({type:'promoter_content',country:req.user.country,actorUserId:req.user._id,input:{campaignId:campaign.publicId,channel:input.channel,brief:input.brief}});await writeAudit(req,'ai.promoter_content_queued',{targetType:'ai_job',targetPublicId:job.publicId,country:req.user.country,metadata:{campaignId:campaign.publicId,channel:input.channel}});setFlash(req,'success','Classic AI campaign content queued. It is constrained to seller-approved campaign facts and disclosure.');res.redirect('/promoter#classic-ai');}catch(e){next(e);}});

router.use('/seller/ai',noStore,requireAiFeature('classic_ai.seller'),requireAuth,requireVerified,requireOnboarding,loadSellerStore,requireStoreCapability('catalogue'));
router.get('/seller/ai',async(req,res,next)=>{try{const [products,jobs]=await Promise.all([Product.find({storeId:req.store._id}).select('publicId title status').sort({updatedAt:-1}).limit(100).lean(),AiJob.find({storeId:req.store._id}).sort({createdAt:-1}).limit(100).lean()]);res.render('ai-workspace',{section:'seller',products,jobs,tickets:[],observability:null,evaluations:[],models:[],prompts:[]});}catch(e){next(e);}});
router.post('/seller/ai/jobs',aiLimit,async(req,res,next)=>{try{const input=z.object({type:z.enum(['product_draft','category_attributes','translation','image_quality','seller_assistant']),productId:z.string().trim().max(120).optional().default(''),notes:z.string().trim().max(6000).optional().default(''),targetLanguage:z.string().trim().max(80).optional().default('')}).parse(req.body);let product=null;if(input.productId){product=await Product.findOne({publicId:input.productId,storeId:req.store._id});if(!product)throw new AppError('Product not found.',404,'PRODUCT_NOT_FOUND');}if(['translation','image_quality','seller_assistant'].includes(input.type)&&!product)throw new AppError('Choose a product for that AI job.',422,'AI_PRODUCT_REQUIRED');const job=await queueAiJob({type:input.type,country:req.store.country,actorUserId:req.user._id,storeId:req.store._id,productId:product?._id,input:{notes:input.notes,question:input.notes,targetLanguage:input.targetLanguage}});await writeAudit(req,'ai.job_queued',{targetType:'ai_job',targetPublicId:job.publicId,country:req.store.country,metadata:{type:job.type,productPublicId:product?.publicId||''}});setFlash(req,'success','Classic AI job queued. Generated facts remain pending until you approve them.');res.redirect('/seller/ai');}catch(e){next(e);}});
router.post('/seller/ai/jobs/:id/approve',async(req,res,next)=>{try{const job=await approveSellerAiJob(req,req.params.id);await writeAudit(req,'ai.seller_suggestion_approved',{targetType:'ai_job',targetPublicId:job.publicId,country:job.country,metadata:{type:job.type}});setFlash(req,'success','AI suggestion approved by the seller and applied only to editable draft fields.');res.redirect('/seller/ai');}catch(e){next(e);}});
router.post('/seller/ai/jobs/:id/reject',async(req,res,next)=>{try{const job=await rejectAiJob(req,req.params.id,req.body.note);await writeAudit(req,'ai.seller_suggestion_rejected',{targetType:'ai_job',targetPublicId:job.publicId,country:job.country});setFlash(req,'success','AI suggestion rejected.');res.redirect('/seller/ai');}catch(e){next(e);}});

router.use('/operations/support/ai',noStore,requireAiFeature('classic_ai.support'),requireAuth,requireVerified,requireOnboarding,supportOnly);
router.get('/operations/support/ai',async(req,res,next)=>{try{const scope=countryScope(req);const [tickets,jobs]=await Promise.all([SupportTicket.find({...scope,status:{$nin:['closed','resolved']}}).select('publicId category subject priority status country').sort({priority:-1,createdAt:-1}).limit(100).lean(),AiJob.find({type:'support_assistant',...scope,actorUserId:req.user._id}).sort({createdAt:-1}).limit(100).lean()]);res.render('ai-workspace',{section:'support',products:[],jobs,tickets,observability:null,evaluations:[],models:[],prompts:[]});}catch(e){next(e);}});
router.post('/operations/support/ai/jobs',aiLimit,async(req,res,next)=>{try{const input=z.object({ticketId:z.string().min(4).max(120),question:z.string().trim().max(2000).optional().default('Suggest a concise, factual customer reply and note any escalation need.')}).parse(req.body);const ticket=await SupportTicket.findOne({publicId:input.ticketId,...countryScope(req)});if(!ticket)throw new AppError('Support ticket not found.',404,'TICKET_NOT_FOUND');const job=await queueAiJob({type:'support_assistant',country:ticket.country,actorUserId:req.user._id,ticketId:ticket._id,input:{question:input.question}});await writeAudit(req,'ai.support_job_queued',{targetType:'ai_job',targetPublicId:job.publicId,country:ticket.country,metadata:{ticketId:ticket.publicId}});setFlash(req,'success','Support suggestion queued. Nothing will be sent until you approve it.');res.redirect('/operations/support/ai');}catch(e){next(e);}});
router.post('/operations/support/ai/jobs/:id/approve',async(req,res,next)=>{try{const job=await approveSupportAiJob(req,req.params.id);await writeAudit(req,'ai.support_suggestion_approved',{targetType:'ai_job',targetPublicId:job.publicId,country:job.country,metadata:{ticketId:String(job.ticketId)}});setFlash(req,'success','Human-approved AI reply was sent through the normal support channel.');res.redirect('/operations/support/ai');}catch(e){next(e);}});
router.post('/operations/support/ai/jobs/:id/reject',async(req,res,next)=>{try{const job=await rejectAiJob(req,req.params.id,req.body.note);await writeAudit(req,'ai.support_suggestion_rejected',{targetType:'ai_job',targetPublicId:job.publicId,country:job.country});setFlash(req,'success','AI support suggestion rejected.');res.redirect('/operations/support/ai');}catch(e){next(e);}});

router.use('/admin/ai',noStore,requireAiFeature('classic_ai.admin'),requireAuth,requireVerified,requireOnboarding,adminOnly);
router.get('/admin/ai',async(req,res,next)=>{try{const scope=countryScope(req);const countryAdmin=req.user.role==='country_admin';const [observabilityRaw,evaluations,models,prompts,jobs]=await Promise.all([aiObservability(countryAdmin?req.user.country:''),AiEvaluationRun.find(countryAdmin?{country:req.user.country}:{}).sort({createdAt:-1}).limit(30).lean(),countryAdmin?Promise.resolve([]):AiModelRegistry.find({}).sort({purpose:1,priority:1}).lean(),AiPromptVersion.find(countryAdmin?{$or:[{country:req.user.country},{country:''}]}:{}).sort({key:1,version:-1}).limit(100).lean(),AiJob.find(scope).sort({createdAt:-1}).limit(100).lean()]);const observability=countryAdmin?{...observabilityRaw,providerConfigured:undefined,provider:'managed',chatModel:'',embeddingModel:'managed'}:observabilityRaw;res.render('ai-workspace',{section:'admin',products:[],tickets:[],jobs,observability,evaluations,models,prompts});}catch(e){next(e);}});
router.post('/admin/ai/evaluations/run',aiLimit,async(req,res,next)=>{try{const run=await runEvaluationSuite({suite:'stage10-core',country:req.user.role==='country_admin'?req.user.country:'UG'});await writeAudit(req,'ai.evaluation_run',{targetType:'ai_evaluation',targetPublicId:run.publicId,country:req.user.role==='country_admin'?req.user.country:'',metadata:{status:run.status,metrics:run.metrics}});setFlash(req,run.status==='passed'?'success':'error',`AI evaluation ${run.status}.`);res.redirect('/admin/ai');}catch(e){next(e);}});
router.post('/admin/ai/jobs/triage',aiLimit,async(req,res,next)=>{try{const input=z.object({caseId:z.string().min(4).max(120)}).parse(req.body);const trust=await TrustCase.findOne({publicId:input.caseId,...countryScope(req)}).lean();if(!trust)throw new AppError('Trust case not found.',404,'TRUST_CASE_NOT_FOUND');const job=await queueAiJob({type:'admin_triage',country:trust.country,actorUserId:req.user._id,input:{case:{publicId:trust.publicId,type:trust.type,status:trust.status,description:trust.description,decision:trust.decision,productPublicId:trust.productPublicId,storePublicId:trust.storePublicId}}});await writeAudit(req,'ai.admin_triage_queued',{targetType:'ai_job',targetPublicId:job.publicId,country:trust.country,metadata:{caseId:trust.publicId,readOnly:true}});setFlash(req,'success','Read-only AI triage queued. It cannot execute enforcement.');res.redirect('/admin/ai');}catch(e){next(e);}});
router.post('/admin/ai/jobs/forecast',aiLimit,async(req,res,next)=>{try{const country=req.user.role==='country_admin'?req.user.country:String(req.body.country||'UG').toUpperCase();if(req.user.role==='country_admin'&&country!==req.user.country)throw new AppError('Country is outside your scope.',403,'COUNTRY_SCOPE');const job=await queueAiJob({type:'demand_forecast',country,actorUserId:req.user._id,input:{}});await writeAudit(req,'ai.forecast_queued',{targetType:'ai_job',targetPublicId:job.publicId,country,metadata:{advisoryOnly:true}});setFlash(req,'success','Advisory demand forecast queued. It will fail closed if there is insufficient data.');res.redirect('/admin/ai');}catch(e){next(e);}});
router.post('/admin/ai/models/:id',async(req,res,next)=>{try{if(req.user.role!=='super_admin')throw new AppError('Only Super Admin can request a global AI model registry change.',403,'FORBIDDEN');const model=await AiModelRegistry.findOne({publicId:req.params.id});if(!model)throw new AppError('AI model registry entry not found.',404,'AI_MODEL_NOT_FOUND');const input=z.object({enabled:z.coerce.boolean().default(false),priority:z.coerce.number().int().min(0).max(10000),maxInputChars:z.coerce.number().int().min(1000).max(500000),inputCostMicrosPerMillion:z.coerce.number().int().min(0),outputCostMicrosPerMillion:z.coerce.number().int().min(0),embeddingCostMicrosPerMillion:z.coerce.number().int().min(0),reason:z.string().trim().min(3).max(1000)}).parse(req.body);const approval=await createApproval({user:req.user,type:'ai_model_registry',country:'',targetType:'ai_model',targetPublicId:model.publicId,payload:input,reason:input.reason});await writeAudit(req,'ai.model_registry_change_requested',{targetType:'approval',targetPublicId:approval.publicId,metadata:{aiModel:model.publicId,provider:model.provider,purpose:model.purpose,model:model.model}});setFlash(req,'success','AI model registry change sent to the approval centre. A different Super Admin must approve it.');res.redirect('/admin/ai');}catch(e){next(e);}});

export default router;
