import { Router } from 'express';
import multer from 'multer';
import { z } from 'zod';
import { requireAuth, requireOnboarding, requireVerified } from '../middleware/auth.js';
import { noStore } from '../middleware/request.js';
import { verifyDeferredCsrf } from '../middleware/csrf.js';
import { AppError } from '../core/errors.js';
import { publicId } from '../core/ids.js';
import { writeAudit } from '../services/audit.js';
import { BusinessInvoice, FinancialDocument, Order } from '../models/index.js';
import { grantTrackedOrder } from '../services/order-access.js';
import { initiatePayment } from '../services/payments.js';
import {
  acceptBusinessInvite, acceptQuote, businessContext, businessReplyQuote, businessStatement, cancelProcurementRequest,
  businessWorkspace, createBudget, createProcurementRequest, createProcurementTemplate, parseProcurementCsv,
  createQuoteRequest, decideProcurementRequest, inviteBusinessMember, requireBusinessCapability, updateBusinessProfile,
} from '../services/business.js';
import { businessDocumentAccess, renderBusinessDocumentPdf } from '../services/business-documents.js';

const router=Router();
const csvUpload=multer({storage:multer.memoryStorage(),limits: {fileSize:1024*1024,files:1,fields:12, fieldArrayIndexLimit: 16 },fileFilter(_req,file,cb){const ok=file.originalname.toLowerCase().endsWith('.csv')||['text/csv','application/vnd.ms-excel','text/plain'].includes(file.mimetype);if(!ok)return cb(new AppError('Upload a CSV file.',422,'PROCUREMENT_CSV_TYPE'));cb(null,true);}}).single('csv');
function deferredUpload(request,response,next){csvUpload(request,response,error=>{if(error)return next(error);try{verifyDeferredCsrf(request);return next();}catch(csrfError){return next(csrfError);}});}
router.use('/business',noStore,requireAuth,requireVerified,requireOnboarding);
router.use('/business',(req,_res,next)=>{
  req.user.$locals=req.user.$locals||{};
  req.user.$locals.activeBusinessPublicId=String(req.session?.activeBusinessPublicId||'').trim();
  next();
});
const itemSchema=z.object({variantPublicId:z.string().trim().min(3).max(100),quantity:z.coerce.number().int().min(1).max(9999),note:z.string().trim().max(300).optional()});
function parseItems(body){
  if(Array.isArray(body.items))return z.array(itemSchema).min(1).max(100).parse(body.items);
  const ids=[].concat(body.variantPublicId||[]),qty=[].concat(body.quantity||[]),notes=[].concat(body.itemNote||[]);return ids.map((id,i)=>itemSchema.parse({variantPublicId:id,quantity:qty[i]||1,note:notes[i]||''}));
}
router.get('/business',async(req,res,next)=>{try{const view=await businessWorkspace(req.user,req.query);if(req.session)req.session.activeBusinessPublicId=view.organization.publicId;req.user.$locals.activeBusinessPublicId=view.organization.publicId;res.render('business-workspace',{view});}catch(e){next(e);}});
router.post('/business/workspace',async(req,res,next)=>{try{const organizationPublicId=z.string().trim().min(3).max(100).parse(req.body.organizationPublicId);const {organization}=await businessContext(req.user,{preferredOrganizationPublicId:organizationPublicId,strictPreferred:true});if(req.session)req.session.activeBusinessPublicId=organization.publicId;req.user.$locals.activeBusinessPublicId=organization.publicId;await writeAudit(req,'business.workspace.selected',{targetType:'business_organization',targetPublicId:organization.publicId,country:organization.country});res.redirect('/business');}catch(e){next(e);}});
router.post('/business/profile',async(req,res,next)=>{try{const input=z.object({companyName:z.string().trim().min(2).max(180),billingEmail:z.string().trim().email().max(254),taxId:z.string().trim().max(120).optional().default(''),billingContactName:z.string().trim().max(120).optional().default(''),billingPhone:z.string().trim().max(32).optional().default(''),billingAddress:z.string().trim().max(240).optional().default(''),billingCity:z.string().trim().max(120).optional().default(''),deliveryContactName:z.string().trim().max(120).optional().default(''),deliveryPhone:z.string().trim().max(32).optional().default(''),deliveryAddress:z.string().trim().max(240).optional().default(''),deliveryCity:z.string().trim().max(120).optional().default('')}).parse(req.body);const row=await updateBusinessProfile(req.user,input);await writeAudit(req,'business.profile.updated',{targetType:'business_organization',targetPublicId:row.publicId});res.redirect('/business');}catch(e){next(e);}});
router.post('/business/members',async(req,res,next)=>{try{const input=z.object({email:z.string().trim().email(),role:z.enum(['admin','buyer','approver','viewer']),spendingLimitMinor:z.coerce.number().int().min(0).max(10_000_000_000).default(0),canApprove:z.string().optional()}).parse(req.body);const row=await inviteBusinessMember(req.user,{...input,canApprove:input.canApprove==='on'||input.role==='approver'});await writeAudit(req,'business.member.invited',{targetType:'business_member',targetPublicId:row.publicId});res.redirect('/business');}catch(e){next(e);}});
router.post('/business/invitations/:id/accept',async(req,res,next)=>{try{const row=await acceptBusinessInvite(req.user,req.params.id);await writeAudit(req,'business.member.accepted',{targetType:'business_member',targetPublicId:row.publicId});res.redirect('/business');}catch(e){next(e);}});
router.post('/business/budgets',async(req,res,next)=>{try{const input=z.object({name:z.string().trim().min(2).max(120),limitMinor:z.coerce.number().int().min(1),periodStart:z.coerce.date(),periodEnd:z.coerce.date()}).parse(req.body);const row=await createBudget(req.user,input);await writeAudit(req,'business.budget.created',{targetType:'business_budget',targetPublicId:row.publicId});res.redirect('/business#budgets');}catch(e){next(e);}});
router.get('/business/requests/import/template.csv',(req,res)=>res.set({'Content-Type':'text/csv; charset=utf-8','Content-Disposition':'attachment; filename="classic-mart-procurement-template.csv"','Cache-Control':'private, no-store'}).send('variantPublicId,quantity,note\n'));
router.post('/business/requests/import',deferredUpload,async(req,res,next)=>{try{if(!req.file?.buffer)throw new AppError('Choose a procurement CSV file.',422,'PROCUREMENT_CSV_REQUIRED');const input=z.object({title:z.string().trim().min(2).max(160),budgetId:z.string().trim().max(100).optional().default('')}).parse(req.body);const items=parseProcurementCsv(req.file.buffer.toString('utf8'));const row=await createProcurementRequest(req.user,{...input,items});await writeAudit(req,'business.procurement.bulk_imported',{targetType:'procurement_request',targetPublicId:row.publicId,metadata:{rows:items.length}});res.redirect('/business#requests');}catch(e){next(e);}});
router.post('/business/requests',async(req,res,next)=>{try{const input=z.object({title:z.string().trim().min(2).max(160),budgetId:z.string().trim().max(100).optional().default('')}).parse(req.body);const row=await createProcurementRequest(req.user,{...input,items:parseItems(req.body)});await writeAudit(req,'business.procurement.submitted',{targetType:'procurement_request',targetPublicId:row.publicId});res.redirect('/business#requests');}catch(e){next(e);}});
router.post('/business/requests/:id/decision',async(req,res,next)=>{try{const input=z.object({decision:z.enum(['approve','reject']),reason:z.string().trim().max(500).optional().default('')}).parse(req.body);const row=await decideProcurementRequest(req.user,req.params.id,{approve:input.decision==='approve',reason:input.reason});await writeAudit(req,`business.procurement.${row.status}`,{targetType:'procurement_request',targetPublicId:row.publicId});res.redirect('/business#requests');}catch(e){next(e);}});
router.post('/business/requests/:id/cancel',async(req,res,next)=>{try{const reason=z.string().trim().max(500).optional().default('').parse(req.body.reason);const row=await cancelProcurementRequest(req.user,req.params.id,{reason});await writeAudit(req,'business.procurement.cancelled',{targetType:'procurement_request',targetPublicId:row.publicId});res.redirect('/business#requests');}catch(e){next(e);}});
router.post('/business/quotes',async(req,res,next)=>{try{const input=z.object({quoteTarget:z.string().trim().min(7).max(240),message:z.string().trim().max(2000).optional().default('Please provide a quotation.')}).parse(req.body);const [procurementRequestId,storeId,...extra]=input.quoteTarget.split('|');if(extra.length||!procurementRequestId||!storeId)throw new AppError('Choose a valid approved procurement/seller target.',422,'QUOTE_TARGET_INVALID');const row=await createQuoteRequest(req.user,{procurementRequestId,storeId,message:input.message});await writeAudit(req,'business.quote.requested',{targetType:'quote_request',targetPublicId:row.publicId});res.redirect('/business#quotes');}catch(e){next(e);}});
router.post('/business/quotes/:id/reply',async(req,res,next)=>{try{const message=z.string().trim().min(2).max(2000).parse(req.body.message);await businessReplyQuote(req.user,req.params.id,message);res.redirect('/business#quotes');}catch(e){next(e);}});
router.post('/business/quotes/:id/accept',async(req,res,next)=>{try{const paymentTerms=z.enum(['immediate','credit']).default('immediate').parse(req.body.paymentTerms||'immediate');const po=await acceptQuote(req.user,req.params.id,{paymentTerms});await writeAudit(req,'business.purchase_order.issued',{targetType:'purchase_order',targetPublicId:po.publicId});res.redirect('/business#purchase-orders');}catch(e){next(e);}});
router.post('/business/invoices/:id/pay',async(req,res,next)=>{try{const {organization,membership}=await businessContext(req.user);requireBusinessCapability(membership,'po');const invoice=await BusinessInvoice.findOne({publicId:req.params.id,organizationId:organization._id,status:{$in:['awaiting_payment','open','overdue']}});if(!invoice)throw new AppError('Payable business invoice not found.',404,'BUSINESS_INVOICE_NOT_FOUND');grantTrackedOrder(req,invoice.orderPublicId,10*60_000);const payment=await initiatePayment(req,{orderId:invoice.orderPublicId,idempotencyKey:publicId('idem')});invoice.paymentIntentPublicId=payment.id;await invoice.save();await writeAudit(req,'business.invoice.payment_started',{targetType:'business_invoice',targetPublicId:invoice.publicId});if(payment.checkoutUrl)return res.redirect(payment.checkoutUrl);return res.redirect('/business#invoices');}catch(e){next(e);}});
router.post('/business/templates',async(req,res,next)=>{try{const input=z.object({name:z.string().trim().min(2).max(140),recurrence:z.enum(['none','weekly','monthly']).default('none')}).parse(req.body);const row=await createProcurementTemplate(req.user,{...input,items:parseItems(req.body)});await writeAudit(req,'business.template.created',{targetType:'procurement_template',targetPublicId:row.publicId});res.redirect('/business#templates');}catch(e){next(e);}});
router.get('/business/documents/:id',async(req,res,next)=>{try{const document=await businessDocumentAccess(req.user,req.params.id,{activeOrganizationPublicId:req.user.$locals?.activeBusinessPublicId||''});res.render('business-document',{document});}catch(e){next(e);}});
router.get('/business/documents/:id.pdf',async(req,res,next)=>{try{const document=await businessDocumentAccess(req.user,req.params.id,{activeOrganizationPublicId:req.user.$locals?.activeBusinessPublicId||''});const pdf=renderBusinessDocumentPdf(document);await writeAudit(req,'business.document.downloaded',{targetType:'business_document',targetPublicId:document.publicId,country:document.country,metadata:{type:document.type,documentNumber:document.documentNumber}});res.set({'Content-Type':'application/pdf','Content-Disposition':`attachment; filename="${document.documentNumber.replace(/[^A-Za-z0-9._-]/g,'_')}.pdf"`,'Cache-Control':'private, no-store','Content-Length':String(pdf.length)}).send(pdf);}catch(e){next(e);}});
router.get('/business/financial-documents/:id',async(req,res,next)=>{try{const {organization}=await businessContext(req.user);const document=await FinancialDocument.findOne({publicId:req.params.id}).lean();if(!document)throw new AppError('Business financial document not found.',404,'BUSINESS_FINANCIAL_DOCUMENT_NOT_FOUND');const order=await Order.findOne({_id:document.orderId,businessOrganizationId:organization._id}).lean();if(!order)throw new AppError('Business financial document not found.',404,'BUSINESS_FINANCIAL_DOCUMENT_NOT_FOUND');const documents=await FinancialDocument.find({orderId:order._id}).sort({issuedAt:1}).lean();res.render('financial-document',{document,documents,businessMode:true});}catch(e){next(e);}});
router.get('/business/statement.csv',async(req,res,next)=>{try{const rows=await businessStatement(req.user);const esc=value=>{let text=String(value??'');if(/^[=+@-]/.test(text))text=`'${text}`;return `"${text.replaceAll('"','""')}"`;};const csv=['PO,Date,Store,PO Status,Subtotal,Tax,Total,Currency,Invoice,Invoice Status,Due,Outstanding,Aging',...rows.map(r=>[r.poNumber,r.createdAt.toISOString(),r.storePublicId,r.status,r.subtotalMinor,r.taxMinor,r.totalMinor,r.currency,r.invoiceNumber,r.invoiceStatus,r.dueAt?new Date(r.dueAt).toISOString():'',r.outstandingMinor,r.aging].map(esc).join(','))].join('\n');res.set({'Content-Type':'text/csv; charset=utf-8','Content-Disposition':'attachment; filename="classic-mart-business-statement.csv"','Cache-Control':'private, no-store'}).send(csv);await writeAudit(req,'business.statement.exported',{targetType:'business_organization',targetPublicId:req.user.$locals?.activeBusinessPublicId||'',metadata:{rows:rows.length}});}catch(e){next(e);}});
export default router;
