import { Router } from 'express';
import multer from 'multer';
import { z } from 'zod';
import { requireAuth, requireOnboarding, requireVerified } from '../middleware/auth.js';
import { noStore } from '../middleware/request.js';
import { verifyDeferredCsrf } from '../middleware/csrf.js';
import { AppError } from '../core/errors.js';
import { writeAudit } from '../services/audit.js';
import {
  acceptBusinessInvite, acceptQuote, businessContext, businessReplyQuote, businessStatement, cancelProcurementRequest,
  businessWorkspace, createBudget, createProcurementRequest, createProcurementTemplate, parseProcurementCsv,
  createQuoteRequest, decideProcurementRequest, inviteBusinessMember, updateBusinessProfile,
} from '../services/business.js';

const router=Router();
const csvUpload=multer({storage:multer.memoryStorage(),limits:{fileSize:1024*1024,files:1,fields:12},fileFilter(_req,file,cb){const ok=file.originalname.toLowerCase().endsWith('.csv')||['text/csv','application/vnd.ms-excel','text/plain'].includes(file.mimetype);if(!ok)return cb(new AppError('Upload a CSV file.',422,'PROCUREMENT_CSV_TYPE'));cb(null,true);}}).single('csv');
function deferredUpload(request,response,next){csvUpload(request,response,error=>{if(error)return next(error);try{verifyDeferredCsrf(request);return next();}catch(csrfError){return next(csrfError);}});}
router.use('/business',noStore,requireAuth,requireVerified,requireOnboarding);
const itemSchema=z.object({productPublicId:z.string().trim().min(3).max(100),quantity:z.coerce.number().int().min(1).max(9999),note:z.string().trim().max(300).optional()});
function parseItems(body){
  if(Array.isArray(body.items))return z.array(itemSchema).min(1).max(100).parse(body.items);
  const ids=[].concat(body.productPublicId||[]),qty=[].concat(body.quantity||[]),notes=[].concat(body.itemNote||[]);return ids.map((id,i)=>itemSchema.parse({productPublicId:id,quantity:qty[i]||1,note:notes[i]||''}));
}
router.get('/business',async(req,res,next)=>{try{res.render('business-workspace',{view:await businessWorkspace(req.user)});}catch(e){next(e);}});
router.post('/business/profile',async(req,res,next)=>{try{const input=z.object({companyName:z.string().trim().min(2).max(180),billingEmail:z.string().trim().email().max(254),taxId:z.string().trim().max(120).optional().default('')}).parse(req.body);const row=await updateBusinessProfile(req.user,input);await writeAudit(req,'business.profile.updated',{targetType:'business_organization',targetPublicId:row.publicId});res.redirect('/business');}catch(e){next(e);}});
router.post('/business/members',async(req,res,next)=>{try{const input=z.object({email:z.string().trim().email(),role:z.enum(['admin','buyer','approver','viewer']),spendingLimitMinor:z.coerce.number().int().min(0).max(10_000_000_000).default(0),canApprove:z.string().optional()}).parse(req.body);const row=await inviteBusinessMember(req.user,{...input,canApprove:input.canApprove==='on'||input.role==='approver'});await writeAudit(req,'business.member.invited',{targetType:'business_member',targetPublicId:row.publicId});res.redirect('/business');}catch(e){next(e);}});
router.post('/business/invitations/:id/accept',async(req,res,next)=>{try{const row=await acceptBusinessInvite(req.user,req.params.id);await writeAudit(req,'business.member.accepted',{targetType:'business_member',targetPublicId:row.publicId});res.redirect('/business');}catch(e){next(e);}});
router.post('/business/budgets',async(req,res,next)=>{try{const input=z.object({name:z.string().trim().min(2).max(120),limitMinor:z.coerce.number().int().min(1),periodStart:z.coerce.date(),periodEnd:z.coerce.date()}).parse(req.body);const row=await createBudget(req.user,input);await writeAudit(req,'business.budget.created',{targetType:'business_budget',targetPublicId:row.publicId});res.redirect('/business#budgets');}catch(e){next(e);}});
router.get('/business/requests/import/template.csv',(req,res)=>res.set({'Content-Type':'text/csv; charset=utf-8','Content-Disposition':'attachment; filename="classic-mart-procurement-template.csv"','Cache-Control':'private, no-store'}).send('productPublicId,quantity,note\n'));
router.post('/business/requests/import',deferredUpload,async(req,res,next)=>{try{if(!req.file?.buffer)throw new AppError('Choose a procurement CSV file.',422,'PROCUREMENT_CSV_REQUIRED');const input=z.object({title:z.string().trim().min(2).max(160),budgetId:z.string().trim().max(100).optional().default('')}).parse(req.body);const items=parseProcurementCsv(req.file.buffer.toString('utf8'));const row=await createProcurementRequest(req.user,{...input,items});await writeAudit(req,'business.procurement.bulk_imported',{targetType:'procurement_request',targetPublicId:row.publicId,metadata:{rows:items.length}});res.redirect('/business#requests');}catch(e){next(e);}});
router.post('/business/requests',async(req,res,next)=>{try{const input=z.object({title:z.string().trim().min(2).max(160),budgetId:z.string().trim().max(100).optional().default('')}).parse(req.body);const row=await createProcurementRequest(req.user,{...input,items:parseItems(req.body)});await writeAudit(req,'business.procurement.submitted',{targetType:'procurement_request',targetPublicId:row.publicId});res.redirect('/business#requests');}catch(e){next(e);}});
router.post('/business/requests/:id/decision',async(req,res,next)=>{try{const input=z.object({decision:z.enum(['approve','reject']),reason:z.string().trim().max(500).optional().default('')}).parse(req.body);const row=await decideProcurementRequest(req.user,req.params.id,{approve:input.decision==='approve',reason:input.reason});await writeAudit(req,`business.procurement.${row.status}`,{targetType:'procurement_request',targetPublicId:row.publicId});res.redirect('/business#requests');}catch(e){next(e);}});
router.post('/business/requests/:id/cancel',async(req,res,next)=>{try{const reason=z.string().trim().max(500).optional().default('').parse(req.body.reason);const row=await cancelProcurementRequest(req.user,req.params.id,{reason});await writeAudit(req,'business.procurement.cancelled',{targetType:'procurement_request',targetPublicId:row.publicId});res.redirect('/business#requests');}catch(e){next(e);}});
router.post('/business/quotes',async(req,res,next)=>{try{const input=z.object({procurementRequestId:z.string().trim().min(3).max(100),storeId:z.string().trim().min(3).max(100),message:z.string().trim().max(2000).optional().default('Please provide a quotation.')}).parse(req.body);const row=await createQuoteRequest(req.user,input);await writeAudit(req,'business.quote.requested',{targetType:'quote_request',targetPublicId:row.publicId});res.redirect('/business#quotes');}catch(e){next(e);}});
router.post('/business/quotes/:id/reply',async(req,res,next)=>{try{const message=z.string().trim().min(2).max(2000).parse(req.body.message);await businessReplyQuote(req.user,req.params.id,message);res.redirect('/business#quotes');}catch(e){next(e);}});
router.post('/business/quotes/:id/accept',async(req,res,next)=>{try{const po=await acceptQuote(req.user,req.params.id);await writeAudit(req,'business.purchase_order.issued',{targetType:'purchase_order',targetPublicId:po.publicId});res.redirect('/business#purchase-orders');}catch(e){next(e);}});
router.post('/business/templates',async(req,res,next)=>{try{const input=z.object({name:z.string().trim().min(2).max(140),recurrence:z.enum(['none','weekly','monthly']).default('none')}).parse(req.body);const row=await createProcurementTemplate(req.user,{...input,items:parseItems(req.body)});await writeAudit(req,'business.template.created',{targetType:'procurement_template',targetPublicId:row.publicId});res.redirect('/business#templates');}catch(e){next(e);}});
router.get('/business/statement.csv',async(req,res,next)=>{try{const rows=await businessStatement(req.user);const esc=v=>`"${String(v??'').replaceAll('"','""')}"`;const csv=['PO,Date,Store,Status,Total,Currency,Invoice Terms Days',...rows.map(r=>[r.poNumber,r.createdAt.toISOString(),r.storePublicId,r.status,r.totalMinor,r.currency,r.invoiceTermsDays].map(esc).join(','))].join('\n');res.set({'Content-Type':'text/csv; charset=utf-8','Content-Disposition':'attachment; filename="classic-mart-business-statement.csv"','Cache-Control':'private, no-store'}).send(csv);}catch(e){next(e);}});
export default router;
