import { Router } from 'express';
import { asyncHandler, AppError } from '../core/errors.js';
import { publicId } from '../core/ids.js';
import { DeliveryException, DeliveryOffer, DeliveryProfile, EvidenceDocument, InventoryDiscrepancy, InventoryMovement, OperationAction, Order, Parcel, ProductVariant, ReconciliationRun, Shipment, ShippingZone, StockItem, Store, Warehouse, WarehouseTask, WarehouseWave } from '../models/index.js';
import { requireAuth, requireOnboarding, requirePermission, requireVerified } from '../middleware/auth.js';
import { noStore } from '../middleware/request.js';
import { verifyDeferredCsrf } from '../middleware/csrf.js';
import { setFlash } from '../middleware/view.js';
import { writeAudit } from '../services/audit.js';
import { acceptDeliveryOffer, claimWarehouseTask, completeCycleCount, createPickWave, createWarehouseTask, ensureShipmentForOrder, executeWarehouseTask, offerShipment, recordCodHandover, reconcileCod, reconcileCodBatch, releasePickWave, resolveDeliveryException, releaseWarehouseTask, reviewInventoryDiscrepancy, transitionShipment } from '../services/logistics.js';
import { sanitizeAndStoreEvidenceImage, uploadVerificationImage } from '../services/media.js';
import { assertOperationalCountry, assertWarehouseScope, operationalCountryScope, warehouseScopesFor } from '../services/authorization.js';
import { cursorScope, cursorSort, pageResult } from '../services/pagination.js';

const router=Router();
function countryScope(request){return operationalCountryScope(request.user,'country');}
router.use('/delivery',noStore,requireAuth,requireVerified,requireOnboarding,requirePermission('delivery:manage'));
router.use('/operations/logistics',noStore,requireAuth,requireVerified,requireOnboarding,(req,res,next)=>{
 if(['super_admin','country_admin','warehouse','finance'].includes(req.user.role)) return next();
 return next(new AppError('Logistics operations permission required.',403,'FORBIDDEN'));
});
const adminLogisticsOnly=(req,_res,next)=>['super_admin','country_admin'].includes(req.user.role)?next():next(new AppError('Country logistics administration permission required.',403,'FORBIDDEN'));
const warehouseOpsOnly=(req,_res,next)=>['super_admin','country_admin','warehouse'].includes(req.user.role)?next():next(new AppError('Warehouse operations permission required.',403,'FORBIDDEN'));
const financeLogisticsOnly=(req,_res,next)=>['super_admin','country_admin','finance'].includes(req.user.role)?next():next(new AppError('Finance reconciliation permission required.',403,'FORBIDDEN'));
function upload(middleware){return(req,res,next)=>middleware(req,res,error=>{if(error)return next(error);try{verifyDeferredCsrf(req);return next();}catch(csrfError){return next(csrfError);}});}
function maskPhone(value){const clean=String(value||'').replace(/\s+/g,'');if(clean.length<=4)return '••••';return `${'•'.repeat(Math.min(8,Math.max(4,clean.length-4)))}${clean.slice(-4)}`;}
function navigationUrl(contact){const query=[contact?.address,contact?.city,contact?.country].filter(Boolean).join(', ');return query?`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(query)}`:'';}
function csvCell(value){let text=String(value??'');if(/^[=+@-]/.test(text))text=`'${text}`;return `"${text.replaceAll('\"','\"\"')}"`;}
function parseReportDate(value,{end=false}={}){if(!value)return null;if(!/^\d{4}-\d{2}-\d{2}$/.test(String(value)))throw new AppError('Use YYYY-MM-DD dates for inventory exports.',422,'REPORT_DATE_INVALID');const date=new Date(`${value}T${end?'23:59:59.999':'00:00:00.000'}Z`);if(!Number.isFinite(date.getTime()))throw new AppError('Inventory export date is invalid.',422,'REPORT_DATE_INVALID');return date;}
const code39Patterns=Object.freeze({
 '0':'nnnwwnwnn','1':'wnnwnnnnw','2':'nnwwnnnnw','3':'wnwwnnnnn','4':'nnnwwnnnw','5':'wnnwwnnnn','6':'nnwwwnnnn','7':'nnnwnnwnw','8':'wnnwnnwnn','9':'nnwwnnwnn',
 A:'wnnnnwnnw',B:'nnwnnwnnw',C:'wnwnnwnnn',D:'nnnnwwnnw',E:'wnnnwwnnn',F:'nnwnwwnnn',G:'nnnnnwwnw',H:'wnnnnwwnn',I:'nnwnnwwnn',J:'nnnnwwwnn',
 K:'wnnnnnnww',L:'nnwnnnnww',M:'wnwnnnnwn',N:'nnnnwnnww',O:'wnnnwnnwn',P:'nnwnwnnwn',Q:'nnnnnnwww',R:'wnnnnnwwn',S:'nnwnnnwwn',T:'nnnnwnwwn',
 U:'wwnnnnnnw',V:'nwwnnnnnw',W:'wwwnnnnnn',X:'nwnnwnnnw',Y:'wwnnwnnnn',Z:'nwwnwnnnn','-':'nwnnnnwnw','.':'wwnnnnwnn',' ':'nwwnnnwnn','$':'nwnwnwnnn','/':'nwnwnnnwn','+':'nwnnnwnwn','%':'nnnwnwnwn','*':'nwnnwnwnn',
});
function code39Geometry(value){const clean=String(value||'').toUpperCase();if(!clean||[...clean].some(ch=>!code39Patterns[ch]))return {value:clean,width:1,height:66,rects:[]};const encoded=`*${clean}*`;const narrow=2,wide=5,gap=2,height=58,margin=10;let x=margin;const rects=[];for(const ch of encoded){const pattern=code39Patterns[ch];for(let i=0;i<pattern.length;i+=1){const barWidth=pattern[i]==='w'?wide:narrow;if(i%2===0)rects.push({x,width:barWidth});x+=barWidth;}x+=gap;}return {value:clean,width:x+margin-gap,height:height+8,barHeight:height,rects};}


router.get('/delivery', asyncHandler(async(req,res)=>{
 const profile=await DeliveryProfile.findOneAndUpdate({userId:req.user._id},{$setOnInsert:{publicId:publicId('dlv'),country:req.user.country,transport:'motorcycle'}},{upsert:true,returnDocument:'after',setDefaultsOnInsert:true});
 const size=50,jobBase={country:profile.country,deliveryUserId:req.user._id},offerBase={country:profile.country,deliveryUserId:req.user._id,status:'offered',expiresAt:{$gt:new Date()}};
 const [jobRows,offerRows,jobTotal,offerTotal,profileEvidence]=await Promise.all([
  Shipment.find(cursorScope(jobBase,req.query.jobsAfter)).sort(cursorSort()).limit(size+1).lean(),
  DeliveryOffer.find(cursorScope(offerBase,req.query.offersAfter)).sort(cursorSort()).limit(size+1).lean(),
  Shipment.countDocuments(jobBase),DeliveryOffer.countDocuments(offerBase),
  EvidenceDocument.find({contextType:'delivery_verification',contextPublicId:profile.publicId,status:'ready'}).select('publicId documentType description createdAt').sort({createdAt:-1}).lean(),
 ]);
 const jobPage=pageResult(jobRows,{limit:size,total:jobTotal}),offerPage=pageResult(offerRows,{limit:size,total:offerTotal});
 const orderIds=jobPage.items.map(job=>job.orderId).filter(Boolean);const jobPublicIds=jobPage.items.map(job=>job.publicId);const [orders,jobEvidence,jobExceptions]=await Promise.all([orderIds.length?Order.find({_id:{$in:orderIds}}).select('publicId contact').lean():[],jobPublicIds.length?EvidenceDocument.find({contextType:'delivery_job',contextPublicId:{$in:jobPublicIds},status:'ready'}).select('publicId contextPublicId documentType description createdAt').sort({createdAt:-1}).lean():[],jobPublicIds.length?DeliveryException.find({shipmentPublicId:{$in:jobPublicIds},status:{$in:['open','investigating']}}).select('publicId shipmentPublicId type reasonCode description evidenceRequired status createdAt').sort({createdAt:-1}).lean():[]]);const orderById=new Map(orders.map(order=>[String(order._id),order]));
 const evidenceByShipment=new Map();for(const row of jobEvidence){if(!evidenceByShipment.has(row.contextPublicId))evidenceByShipment.set(row.contextPublicId,[]);evidenceByShipment.get(row.contextPublicId).push(row);}const exceptionByShipment=new Map();for(const row of jobExceptions){if(!exceptionByShipment.has(row.shipmentPublicId))exceptionByShipment.set(row.shipmentPublicId,[]);exceptionByShipment.get(row.shipmentPublicId).push(row);}
 const deliveryJobs=jobPage.items.map(job=>{const order=orderById.get(String(job.orderId));const contact=order?.contact||{};return{...job,evidence:evidenceByShipment.get(job.publicId)||[],openExceptions:exceptionByShipment.get(job.publicId)||[],destination:{fullName:contact.fullName||'',address:contact.address||'',city:contact.city||'',note:contact.note||'',maskedPhone:maskPhone(contact.phone),navigationUrl:navigationUrl(contact)}};});
 res.render('logistics-workspace',{mode:'delivery',profile,profileEvidence,jobs:deliveryJobs,offers:offerPage.items,tasks:[],zones:[],warehouses:[],stock:[],parcels:[],codRuns:[],deliveryEvidenceByProfile:{},queuePages:{jobs:jobPage.page,offers:offerPage.page}});
}));
router.post('/delivery/profile',asyncHandler(async(req,res)=>{
 const transport=String(req.body.transport||''); if(!['bicycle','motorcycle','car','van','truck','other'].includes(transport))throw new AppError('Choose a valid transport mode.',422,'TRANSPORT_INVALID');
 const areas=String(req.body.serviceAreas||'').split(',').map(v=>v.trim()).filter(Boolean).slice(0,30);const profile=await DeliveryProfile.findOne({userId:req.user._id});if(!profile)throw new AppError('Delivery profile not found.',404,'DELIVERY_NOT_FOUND');
 profile.transport=transport;profile.vehicleLabel=String(req.body.vehicleLabel||'').trim().slice(0,120);profile.serviceAreas=areas;profile.available=false;profile.verificationStatus='draft';
 if(String(req.body.action||'save')==='submit'){const evidence=await EvidenceDocument.find({contextType:'delivery_verification',contextPublicId:profile.publicId,status:'ready'}).select('documentType').lean();const types=new Set(evidence.map(doc=>doc.documentType));if(!types.has('identity'))throw new AppError('Upload an identity verification image before submitting.',422,'DELIVERY_IDENTITY_REQUIRED');if(transport!=='bicycle'&&!types.has('vehicle')&&!types.has('permit'))throw new AppError('Upload a vehicle or driving-permit verification image before submitting.',422,'DELIVERY_VEHICLE_DOCUMENT_REQUIRED');profile.verificationStatus='submitted';profile.reviewReason='';}
 await profile.save();setFlash(req,'success',profile.verificationStatus==='submitted'?'Delivery profile submitted for verification.':'Delivery profile saved.'); res.redirect('/delivery');
}));
router.post('/delivery/profile/evidence',upload(uploadVerificationImage),asyncHandler(async(req,res)=>{const profile=await DeliveryProfile.findOne({userId:req.user._id});if(!profile)throw new AppError('Delivery profile not found.',404,'DELIVERY_NOT_FOUND');const documentType=String(req.body.documentType||'');if(!['identity','vehicle','permit'].includes(documentType))throw new AppError('Choose a valid verification document type.',422,'DELIVERY_DOCUMENT_TYPE_INVALID');await sanitizeAndStoreEvidenceImage({file:req.file,user:req.user,country:profile.country,contextType:'delivery_verification',contextPublicId:profile.publicId,documentType,description:String(req.body.description||documentType).slice(0,300)});if(profile.verificationStatus!=='approved')profile.verificationStatus='draft';profile.available=false;await profile.save();setFlash(req,'success','Verification image uploaded securely.');res.redirect('/delivery');}));
router.post('/delivery/availability',asyncHandler(async(req,res)=>{
 const profile=await DeliveryProfile.findOne({userId:req.user._id}); if(!profile||profile.verificationStatus!=='approved')throw new AppError('Approved delivery verification is required.',409,'DELIVERY_NOT_APPROVED'); profile.available=String(req.body.available)==='true';await profile.save();res.redirect('/delivery');
}));
router.post('/delivery/offers/:publicId/accept',asyncHandler(async(req,res)=>{
 const profile=await DeliveryProfile.findOne({userId:req.user._id,verificationStatus:'approved',available:true});if(!profile)throw new AppError('You must be approved and available.',409,'DELIVERY_NOT_AVAILABLE');
 const offer=await DeliveryOffer.findOne({publicId:req.params.publicId,deliveryUserId:req.user._id,country:profile.country,status:'offered'});if(!offer)throw new AppError('Delivery offer not found.',404,'OFFER_NOT_FOUND');
 const shipment=await acceptDeliveryOffer({offer,actorUserId:req.user._id});await writeAudit(req,'delivery.assignment_accepted',{targetType:'shipment',targetPublicId:shipment.publicId});res.redirect('/delivery');
}));

router.post('/delivery/jobs/:publicId/evidence',upload(uploadVerificationImage),asyncHandler(async(req,res)=>{
 const profile=await DeliveryProfile.findOne({userId:req.user._id}).select('country').lean();if(!profile)throw new AppError('Delivery profile not found.',404,'DELIVERY_NOT_FOUND');const shipment=await Shipment.findOne({publicId:req.params.publicId,deliveryUserId:req.user._id,country:profile.country});if(!shipment)throw new AppError('Assigned shipment not found.',404,'SHIPMENT_NOT_FOUND');
 const documentType=String(req.body.documentType||'');if(!['delivery_photo','delivery_signature','failed_attempt','address_exception'].includes(documentType))throw new AppError('Choose a valid delivery evidence type.',422,'DELIVERY_EVIDENCE_TYPE_INVALID');const evidence=await sanitizeAndStoreEvidenceImage({file:req.file,user:req.user,country:shipment.country,contextType:'delivery_job',contextPublicId:shipment.publicId,documentType,description:String(req.body.description||documentType).slice(0,300)});if(['failed_attempt','address_exception'].includes(documentType)){const type=documentType==='address_exception'?'address_exception':'failed_delivery';await DeliveryException.findOneAndUpdate({shipmentId:shipment._id,type,status:{$in:['open','investigating']}},{$addToSet:{evidenceDocumentIds:evidence._id},$push:{timeline:{type:'evidence_added',message:'Delivery partner added photo evidence.',actorUserId:req.user._id}}},{sort:{createdAt:-1}});}await writeAudit(req,'delivery.evidence_uploaded',{targetType:'shipment',targetPublicId:shipment.publicId,country:shipment.country,metadata:{evidencePublicId:evidence.publicId,documentType}});setFlash(req,'success','Delivery evidence uploaded securely.');res.redirect('/delivery');
}));
router.post('/delivery/jobs/:publicId/cod-handover',upload(uploadVerificationImage),asyncHandler(async(req,res)=>{
 const declaredAmountMinor=Number(req.body.declaredAmountMinor);if(!Number.isSafeInteger(declaredAmountMinor)||declaredAmountMinor<0)throw new AppError('COD handover amount must be a non-negative whole minor-unit amount.',422,'COD_HANDOVER_AMOUNT_INVALID');
 const profile=await DeliveryProfile.findOne({userId:req.user._id}).select('country').lean();if(!profile)throw new AppError('Delivery profile not found.',404,'DELIVERY_NOT_FOUND');const shipment=await Shipment.findOne({publicId:req.params.publicId,deliveryUserId:req.user._id,country:profile.country});if(!shipment)throw new AppError('Assigned shipment not found.',404,'SHIPMENT_NOT_FOUND');const evidence=await sanitizeAndStoreEvidenceImage({file:req.file,user:req.user,country:shipment.country,contextType:'delivery_job',contextPublicId:shipment.publicId,documentType:'cod_handover',description:'COD cash handover receipt'});const outcome=await recordCodHandover({shipment,actorUserId:req.user._id,declaredAmountMinor,evidenceDocumentId:evidence._id});await writeAudit(req,outcome.mismatch?'delivery.cod_handover_mismatch':'delivery.cod_handover_recorded',{targetType:'shipment',targetPublicId:shipment.publicId,country:shipment.country,metadata:{declaredAmountMinor,evidencePublicId:evidence.publicId,exceptionPublicId:outcome.exception?.publicId||''}});setFlash(req,outcome.mismatch?(outcome.corrected?'success':'error'):'success',outcome.mismatch?(outcome.corrected?'COD handover corrected. A supervisor must close the existing mismatch case before finance reconciliation.':'COD amount mismatch recorded and escalated for investigation. Do not hand over or retry money outside the reconciliation workflow.'):'COD handover receipt recorded. Finance can now reconcile this shipment.');res.redirect('/delivery');
}));
for(const action of ['picked_up','in_transit','delivered','failed','rescheduled','return_to_sender','returned']){
 router.post(`/delivery/jobs/:publicId/${action}`,asyncHandler(async(req,res)=>{const profile=await DeliveryProfile.findOne({userId:req.user._id}).select('country').lean();if(!profile)throw new AppError('Delivery profile not found.',404,'DELIVERY_NOT_FOUND');const shipment=await Shipment.findOne({publicId:req.params.publicId,deliveryUserId:req.user._id,country:profile.country}).select('+pickupCodeHash +deliveryCodeHash');if(!shipment)throw new AppError('Assigned shipment not found.',404,'SHIPMENT_NOT_FOUND');await transitionShipment({shipment,nextStatus:action,actorUserId:req.user._id,proofCode:String(req.body.proofCode||''),reason:String(req.body.reason||''),reasonCode:String(req.body.reasonCode||'other'),rescheduledFor:req.body.rescheduledFor});res.redirect('/delivery');}));
}

router.get('/operations/logistics',asyncHandler(async(req,res)=>{
 const scope=countryScope(req),pageSize=50,assignedWarehouseScopes=warehouseScopesFor(req.user),warehouseScope={...scope,...(assignedWarehouseScopes.length?{publicId:{$in:assignedWarehouseScopes}}:{})};
 const [warehouseIds,shipmentIds,profileIds]=await Promise.all([
  Warehouse.find(warehouseScope).distinct('_id'),Shipment.find(scope).distinct('_id'),DeliveryProfile.find(scope).distinct('publicId'),
 ]);
 const childScope={
  tasks:warehouseIds.length?{warehouseId:{$in:warehouseIds}}:{_id:{$in:[]}},
  stock:warehouseIds.length?{warehouseId:{$in:warehouseIds}}:{_id:{$in:[]}},
  parcels:shipmentIds.length?{shipmentId:{$in:shipmentIds}}:{_id:{$in:[]}},
  offers:shipmentIds.length?{shipmentId:{$in:shipmentIds}}:{_id:{$in:[]}},
  discrepancies:warehouseIds.length?{...scope,warehouseId:{$in:warehouseIds}}:{_id:{$in:[]}},
 };
 const taskFilters={status:String(req.query.taskStatus||''),type:String(req.query.taskType||''),warehousePublicId:String(req.query.taskWarehouse||''),overdue:String(req.query.taskOverdue||'')==='1'};
 if(taskFilters.warehousePublicId){const selected=await Warehouse.findOne({publicId:taskFilters.warehousePublicId,...warehouseScope}).select('_id').lean();if(!selected)throw new AppError('Warehouse filter is outside your operational scope.',404,'WAREHOUSE_NOT_FOUND');childScope.tasks={warehouseId:selected._id};childScope.stock={warehouseId:selected._id};}
 if(['open','in_progress','completed','cancelled'].includes(taskFilters.status))childScope.tasks.status=taskFilters.status;
 if(['receive','put_away','pick','pack','dispatch','cycle_count','transfer','return_inspection'].includes(taskFilters.type))childScope.tasks.type=taskFilters.type;
 if(taskFilters.overdue){childScope.tasks.status={$in:['open','in_progress']};childScope.tasks.dueAt={$lt:new Date()};}
 let scanResult=null;const scanCode=String(req.query.scanCode||'').trim().slice(0,100);
 if(scanCode){
  const parcel=await Parcel.findOne({...childScope.parcels,barcode:scanCode}).lean();
  if(parcel)scanResult={type:'parcel',title:`Parcel ${parcel.publicId}`,detail:`${parcel.status} · ${parcel.storePublicId} · ${parcel.items?.reduce((sum,row)=>sum+Number(row.quantity||0),0)||0} item(s)`,publicId:parcel.publicId};
  else{
   const variant=await ProductVariant.findOne({$or:[{sku:scanCode.toUpperCase()},{barcode:scanCode}]}).select('_id sku title').lean();
   let stockItem=await StockItem.findOne({...childScope.stock,publicId:scanCode}).populate('warehouseId','name country').populate('variantId','sku title').lean();
   if(!stockItem&&variant)stockItem=await StockItem.findOne({...childScope.stock,variantId:variant._id}).populate('warehouseId','name country').populate('variantId','sku title').lean();
   if(stockItem)scanResult={type:'stock',title:stockItem.variantId?.sku||stockItem.publicId,detail:`${stockItem.warehouseId?.name||''} · on hand ${stockItem.onHand||0} · available ${Math.max(0,Number(stockItem.onHand||0)-Number(stockItem.reserved||0)-Number(stockItem.damaged||0)-Number(stockItem.quarantined||0))}`,publicId:stockItem.publicId};
   else scanResult={type:'not_found',title:'No matching warehouse item',detail:'Check the parcel barcode, stock ID, SKU or product barcode and try again.',publicId:''};
  }
 }
 const rows=async(Model,base,cursor,{field='createdAt',direction=-1,populate=[],select=''}={})=>{
  let q=Model.find(cursorScope(base,cursor,{field,direction})).sort(cursorSort(field,direction)).limit(pageSize+1);
  if(select)q=q.select(select);for(const entry of populate)q=q.populate(...entry);return q.lean();
 };
 const [profileRows,jobRows,zoneRows,warehouseRows,taskRows,discrepancyRows,stockRows,parcelRows,offerRows,codRows,exceptionRows,profileTotal,jobTotal,zoneTotal,warehouseTotal,taskTotal,discrepancyTotal,stockTotal,parcelTotal,offerTotal,codTotal,exceptionTotal,deliveryEvidence]=await Promise.all([
  rows(DeliveryProfile,scope,req.query.profilesAfter,{populate:[['userId','name email phone']]}),
  rows(Shipment,scope,req.query.jobsAfter),
  rows(ShippingZone,scope,req.query.zonesAfter),
  rows(Warehouse,warehouseScope,req.query.warehousesAfter),
  rows(WarehouseTask,childScope.tasks,req.query.tasksAfter,{populate:[['warehouseId','name country'],['assignedUserId','name publicId']]}),
  rows(InventoryDiscrepancy,childScope.discrepancies,req.query.discrepanciesAfter,{populate:[['warehouseId','name country'],['stockItemId','publicId'],['variantId','sku title'],['countedByUserId','name publicId'],['reviewedByUserId','name publicId']]}),
  rows(StockItem,childScope.stock,req.query.stockAfter,{populate:[['warehouseId','name country'],['variantId','sku title']]}),
  rows(Parcel,childScope.parcels,req.query.parcelsAfter),
  rows(DeliveryOffer,childScope.offers,req.query.offersAfter),
  rows(ReconciliationRun,{...scope,provider:'cod'},req.query.codAfter),
  rows(DeliveryException,scope,req.query.exceptionsAfter,{populate:[['deliveryUserId','name publicId'],['evidenceDocumentIds','publicId documentType description createdAt']]}),
  DeliveryProfile.countDocuments(scope),Shipment.countDocuments(scope),ShippingZone.countDocuments(scope),Warehouse.countDocuments(warehouseScope),WarehouseTask.countDocuments(childScope.tasks),InventoryDiscrepancy.countDocuments(childScope.discrepancies),StockItem.countDocuments(childScope.stock),Parcel.countDocuments(childScope.parcels),DeliveryOffer.countDocuments(childScope.offers),ReconciliationRun.countDocuments({...scope,provider:'cod'}),DeliveryException.countDocuments(scope),
  EvidenceDocument.find({contextType:'delivery_verification',contextPublicId:{$in:profileIds},status:'ready'}).select('publicId contextPublicId documentType description createdAt').sort({createdAt:-1}).lean(),
 ]);
 const [waveRows,waveTotal]=await Promise.all([
  rows(WarehouseWave,assignedWarehouseScopes.length?{...scope,warehousePublicId:{$in:assignedWarehouseScopes}}:scope,req.query.wavesAfter,{populate:[['warehouseId','name country'],['assignedUserId','name publicId']]}),
  WarehouseWave.countDocuments(scope),
 ]);
 const pageDefs={
  profiles:pageResult(profileRows,{limit:pageSize,total:profileTotal}),jobs:pageResult(jobRows,{limit:pageSize,total:jobTotal}),zones:pageResult(zoneRows,{limit:pageSize,total:zoneTotal}),warehouses:pageResult(warehouseRows,{limit:pageSize,total:warehouseTotal}),tasks:pageResult(taskRows,{limit:pageSize,total:taskTotal}),waves:pageResult(waveRows,{limit:pageSize,total:waveTotal}),discrepancies:pageResult(discrepancyRows,{limit:pageSize,total:discrepancyTotal}),stock:pageResult(stockRows,{limit:pageSize,total:stockTotal}),parcels:pageResult(parcelRows,{limit:pageSize,total:parcelTotal}),offers:pageResult(offerRows,{limit:pageSize,total:offerTotal}),codRuns:pageResult(codRows,{limit:pageSize,total:codTotal}),exceptions:pageResult(exceptionRows,{limit:pageSize,total:exceptionTotal}),
 };
 const profiles=pageDefs.profiles.items,jobs=pageDefs.jobs.items,zones=pageDefs.zones.items,warehouses=pageDefs.warehouses.items,tasks=pageDefs.tasks.items,waves=pageDefs.waves.items,discrepancies=pageDefs.discrepancies.items,stock=pageDefs.stock.items,parcels=pageDefs.parcels.items,offers=pageDefs.offers.items,codRuns=pageDefs.codRuns.items,exceptions=pageDefs.exceptions.items;
 const deliveryEvidenceByProfile={};for(const doc of deliveryEvidence){(deliveryEvidenceByProfile[doc.contextPublicId]??=[]).push(doc);}
 const capabilities={admin:['super_admin','country_admin'].includes(req.user.role),warehouse:['super_admin','country_admin','warehouse'].includes(req.user.role),finance:['super_admin','country_admin','finance'].includes(req.user.role)};
 res.render('logistics-workspace',{mode:'operations',profiles,jobs,zones,warehouses,tasks,waves,discrepancies,stock,parcels,offers,capabilities,deliveryEvidenceByProfile,codRuns,exceptions,taskFilters,scanCode,scanResult,queuePages:Object.fromEntries(Object.entries(pageDefs).map(([name,value])=>[name,value.page]))});
}));
router.post('/operations/logistics/delivery/:publicId/review',adminLogisticsOnly,asyncHandler(async(req,res)=>{const profile=await DeliveryProfile.findOne({publicId:req.params.publicId,...countryScope(req),verificationStatus:'submitted'});if(!profile)throw new AppError('Submitted delivery profile not found.',404,'DELIVERY_NOT_FOUND');const decision=String(req.body.decision||'');if(!['approve','reject'].includes(decision))throw new AppError('Choose approve or reject.',422,'DELIVERY_REVIEW_INVALID');if(decision==='approve'){const evidence=await EvidenceDocument.find({contextType:'delivery_verification',contextPublicId:profile.publicId,status:'ready'}).select('documentType').lean();const types=new Set(evidence.map(doc=>doc.documentType));if(!types.has('identity'))throw new AppError('Identity evidence is required before approval.',409,'DELIVERY_IDENTITY_REQUIRED');if(profile.transport!=='bicycle'&&!types.has('vehicle')&&!types.has('permit'))throw new AppError('Vehicle or permit evidence is required before approval.',409,'DELIVERY_VEHICLE_DOCUMENT_REQUIRED');}profile.verificationStatus=decision==='approve'?'approved':'rejected';profile.codEnabled=decision==='approve'&&String(req.body.codEnabled)==='true';profile.reviewReason=String(req.body.reason||'').trim().slice(0,500);if(decision==='reject'&&!profile.reviewReason)throw new AppError('A rejection reason is required.',422,'DELIVERY_REVIEW_REASON_REQUIRED');profile.approvedAt=decision==='approve'?new Date():undefined;profile.reviewedAt=new Date();profile.reviewedByUserId=req.user._id;profile.available=false;await profile.save();await writeAudit(req,`delivery.profile_${decision==='approve'?'approved':'rejected'}`,{targetType:'delivery_profile',targetPublicId:profile.publicId});res.redirect('/operations/logistics');}));
router.post('/operations/logistics/shipments/:publicId/offer',adminLogisticsOnly,asyncHandler(async(req,res)=>{const shipment=await Shipment.findOne({publicId:req.params.publicId,...countryScope(req)});if(!shipment)throw new AppError('Shipment not found.',404,'SHIPMENT_NOT_FOUND');const profile=await DeliveryProfile.findOne({publicId:String(req.body.deliveryProfileId||''),verificationStatus:'approved',available:true,...countryScope(req)});if(!profile)throw new AppError('Approved available delivery partner not found.',404,'DELIVERY_NOT_FOUND');if(shipment.cod?.required&&!profile.codEnabled)throw new AppError('This delivery partner is not approved to collect COD.',409,'DELIVERY_COD_NOT_ALLOWED');await offerShipment({shipment,deliveryUserId:profile.userId,earningMinor:Math.max(0,Number(req.body.earningMinor||0)),currency:String(shipment.cod?.currency||req.user.currency).toUpperCase(),actorUserId:req.user._id});res.redirect('/operations/logistics');}));
router.post('/operations/logistics/orders/:publicId/shipment',adminLogisticsOnly,asyncHandler(async(req,res)=>{const order=await Order.findOne({publicId:req.params.publicId,...countryScope(req)});if(!order)throw new AppError('Order not found.',404,'ORDER_NOT_FOUND');await ensureShipmentForOrder(order,req.user._id);res.redirect('/operations/logistics');}));
router.post('/operations/logistics/zones',adminLogisticsOnly,asyncHandler(async(req,res)=>{const country=String(req.body.country||'').trim().toUpperCase();if(!country)throw new AppError('Country is required.',422,'COUNTRY_REQUIRED');if(req.user.role!=='super_admin')assertOperationalCountry(req.user,country);const currency=String(req.body.currency||req.user.currency).toUpperCase();await ShippingZone.create({publicId:publicId('zon'),country,name:String(req.body.name||'').trim(),cities:String(req.body.cities||'').split(',').map(v=>v.trim()).filter(Boolean),standardFeeMinor:Number(req.body.standardFeeMinor||0),expressFeeMinor:Number(req.body.expressFeeMinor||0),currency,standardSlaHours:Number(req.body.standardSlaHours||120),expressSlaHours:Number(req.body.expressSlaHours||48)});res.redirect('/operations/logistics');}));

router.get('/operations/logistics/inventory-audit.csv',warehouseOpsOnly,asyncHandler(async(req,res)=>{
 const scope=countryScope(req);const now=new Date();const from=parseReportDate(req.query.from)||new Date(now.getTime()-30*24*60*60*1000);const to=parseReportDate(req.query.to,{end:true})||now;if(from>to||to-from>366*24*60*60*1000)throw new AppError('Inventory export range must be between 0 and 366 days.',422,'REPORT_RANGE_INVALID');
 let warehouses=await Warehouse.find({...scope,...(warehouseScopesFor(req.user).length?{publicId:{$in:warehouseScopesFor(req.user)}}:{})}).select('_id publicId name country').lean();if(req.query.warehousePublicId){warehouses=warehouses.filter(row=>row.publicId===String(req.query.warehousePublicId));if(!warehouses.length)throw new AppError('Warehouse not found in your operational scope.',404,'WAREHOUSE_NOT_FOUND');}
 const warehouseIds=warehouses.map(row=>row._id);const query={warehouseId:{$in:warehouseIds},createdAt:{$gte:from,$lte:to}};const warehouseById=new Map(warehouses.map(row=>[String(row._id),row]));
 res.set({'Content-Type':'text/csv; charset=utf-8','Content-Disposition':`attachment; filename="classic-mart-inventory-audit-${from.toISOString().slice(0,10)}-${to.toISOString().slice(0,10)}.csv"`,'Cache-Control':'private, no-store'});res.write('Movement ID,Timestamp,Country,Warehouse,Stock ID,SKU,Type,Quantity,On Hand Before,On Hand After,Reserved Before,Reserved After,Damaged Before,Damaged After,Quarantine Before,Quarantine After,Reference,Reason,Actor User ID\n');
 let rowCount=0;const cursor=InventoryMovement.find(query).sort({createdAt:1,_id:1}).populate('stockItemId','publicId').populate('variantId','sku').lean().cursor();for await(const row of cursor){const warehouse=warehouseById.get(String(row.warehouseId))||{};res.write([row.publicId,row.createdAt?.toISOString?.()||'',warehouse.country||'',warehouse.name||String(row.warehouseId||''),row.stockItemId?.publicId||String(row.stockItemId||''),row.variantId?.sku||String(row.variantId||''),row.type,row.quantity,row.onHandBefore,row.onHandAfter,row.reservedBefore,row.reservedAfter,row.damagedBefore,row.damagedAfter,row.quarantinedBefore,row.quarantinedAfter,row.reference,row.reason,String(row.actorUserId||'')].map(csvCell).join(',')+'\n');rowCount+=1;}
 await writeAudit(req,'warehouse.inventory_audit_exported',{targetType:'inventory_movement',targetPublicId:'inventory-audit',metadata:{from:from.toISOString(),to:to.toISOString(),rowCount,warehousePublicId:String(req.query.warehousePublicId||'')}});res.end();
}));
router.get('/operations/logistics/parcels/:publicId/label',warehouseOpsOnly,asyncHandler(async(req,res)=>{const parcel=await Parcel.findOne({publicId:req.params.publicId}).lean();if(!parcel)throw new AppError('Parcel not found.',404,'PARCEL_NOT_FOUND');const shipment=await Shipment.findOne({_id:parcel.shipmentId,...countryScope(req)}).lean();if(!shipment)throw new AppError('Parcel not found.',404,'PARCEL_NOT_FOUND');res.set('Cache-Control','private, no-store');res.render('parcel-label',{parcel,shipment,barcodeGeometry:code39Geometry(parcel.barcode)});}));
router.post('/operations/logistics/tasks',warehouseOpsOnly,asyncHandler(async(req,res)=>{const warehouse=await Warehouse.findOne({publicId:String(req.body.warehousePublicId||''),...countryScope(req),active:true});if(!warehouse)throw new AppError('Warehouse not found.',404,'WAREHOUSE_NOT_FOUND');assertWarehouseScope(req.user,warehouse.publicId);const type=String(req.body.type||'');if(!['receive','put_away','pick','pack','dispatch','cycle_count','transfer'].includes(type))throw new AppError('Warehouse task type is invalid. Return inspection tasks are generated only from received return requests.',422,'TASK_TYPE_INVALID');let stockItem=null;if(req.body.stockPublicId)stockItem=await StockItem.findOne({publicId:String(req.body.stockPublicId),warehouseId:warehouse._id});let destinationWarehouse=null;if(req.body.destinationWarehousePublicId)destinationWarehouse=await Warehouse.findOne({publicId:String(req.body.destinationWarehousePublicId),storeId:warehouse.storeId,active:true});let parcel=null;if(req.body.parcelPublicId){const store=await Store.findById(warehouse.storeId).lean();parcel=await Parcel.findOne({publicId:String(req.body.parcelPublicId),storePublicId:store?.publicId});if(!parcel)throw new AppError('Parcel is outside this warehouse store scope.',403,'PARCEL_SCOPE');}const quantity=Number(req.body.quantity||0);if(!Number.isSafeInteger(quantity)||quantity<0)throw new AppError('Task quantity must be a whole non-negative number.',422,'TASK_QUANTITY_INVALID');await createWarehouseTask({warehouseId:warehouse._id,storeId:warehouse.storeId,type,reference:String(req.body.reference||'').slice(0,120),notes:String(req.body.notes||'').slice(0,500),stockItemId:stockItem?._id,variantId:stockItem?.variantId,destinationWarehouseId:destinationWarehouse?._id,parcelId:parcel?._id,quantity,binCode:String(req.body.binCode||'').trim().slice(0,80),disposition:['good','damaged','quarantine'].includes(String(req.body.disposition||''))?String(req.body.disposition):''});res.redirect('/operations/logistics');}));
router.post('/operations/logistics/pick-waves',warehouseOpsOnly,asyncHandler(async(req,res)=>{const warehouse=await Warehouse.findOne({publicId:String(req.body.warehousePublicId||''),...countryScope(req),active:true});if(!warehouse)throw new AppError('Warehouse not found.',404,'WAREHOUSE_NOT_FOUND');assertWarehouseScope(req.user,warehouse.publicId);const batchSize=Number(req.body.batchSize||20);if(!Number.isSafeInteger(batchSize)||batchSize<2||batchSize>50)throw new AppError('Pick wave size must be between 2 and 50 tasks.',422,'PICK_WAVE_SIZE_INVALID');const wave=await createPickWave({warehouseId:warehouse._id,actorUserId:req.user._id,batchSize});await writeAudit(req,'warehouse.pick_wave_created',{targetType:'warehouse_wave',targetPublicId:wave.publicId,country:warehouse.country,metadata:{taskCount:wave.taskCount,totalQuantity:wave.totalQuantity}});setFlash(req,'success',`Pick wave ${wave.publicId} claimed ${wave.taskCount} task(s) for you.`);res.redirect('/operations/logistics');}));
router.post('/operations/logistics/pick-waves/:publicId/release',warehouseOpsOnly,asyncHandler(async(req,res)=>{const wave=await WarehouseWave.findOne({publicId:req.params.publicId,status:'in_progress'}).populate('warehouseId');if(!wave)throw new AppError('Active pick wave not found.',404,'PICK_WAVE_NOT_FOUND');if(req.user.role!=='super_admin')assertOperationalCountry(req.user,wave.country,'Pick wave not found.');const force=['super_admin','country_admin'].includes(req.user.role);await releasePickWave({wavePublicId:wave.publicId,actorUserId:req.user._id,force});await writeAudit(req,'warehouse.pick_wave_released',{targetType:'warehouse_wave',targetPublicId:wave.publicId,country:wave.country,metadata:{supervisorRelease:force&&String(wave.assignedUserId||'')!==String(req.user._id)}});setFlash(req,'success','Remaining pick tasks were released back to the queue.');res.redirect('/operations/logistics');}));
router.post('/operations/logistics/tasks/:publicId/claim',warehouseOpsOnly,asyncHandler(async(req,res)=>{const task=await WarehouseTask.findOne({publicId:req.params.publicId,status:'open'}).populate('warehouseId');if(!task)throw new AppError('Open warehouse task not found.',404,'TASK_NOT_FOUND');if(req.user.role!=='super_admin')assertOperationalCountry(req.user,task.warehouseId.country,'Warehouse task not found.');assertWarehouseScope(req.user,task.warehouseId.publicId);await claimWarehouseTask({taskPublicId:task.publicId,actorUserId:req.user._id});await writeAudit(req,'warehouse.task_claimed',{targetType:'warehouse_task',targetPublicId:task.publicId,country:task.warehouseId.country});res.redirect('/operations/logistics');}));
router.post('/operations/logistics/tasks/:publicId/release',warehouseOpsOnly,asyncHandler(async(req,res)=>{const task=await WarehouseTask.findOne({publicId:req.params.publicId,status:'in_progress'}).populate('warehouseId');if(!task)throw new AppError('In-progress warehouse task not found.',404,'TASK_NOT_FOUND');if(req.user.role!=='super_admin')assertOperationalCountry(req.user,task.warehouseId.country,'Warehouse task not found.');assertWarehouseScope(req.user,task.warehouseId.publicId);const force=['super_admin','country_admin'].includes(req.user.role);if(task.wavePublicId){await releasePickWave({wavePublicId:task.wavePublicId,actorUserId:req.user._id,force});await writeAudit(req,'warehouse.pick_wave_released',{targetType:'warehouse_wave',targetPublicId:task.wavePublicId,country:task.warehouseId.country,metadata:{triggerTaskPublicId:task.publicId,supervisorRelease:force&&String(task.assignedUserId||'')!==String(req.user._id)}});setFlash(req,'success','The pick wave and all unfinished tasks were released back to the queue.');}else{await releaseWarehouseTask({taskPublicId:task.publicId,actorUserId:req.user._id,force});await writeAudit(req,'warehouse.task_released',{targetType:'warehouse_task',targetPublicId:task.publicId,country:task.warehouseId.country,metadata:{supervisorRelease:force&&String(task.assignedUserId||'')!==String(req.user._id)}});}res.redirect('/operations/logistics');}));
router.post('/operations/logistics/tasks/:publicId/complete',warehouseOpsOnly,asyncHandler(async(req,res)=>{const task=await WarehouseTask.findOne({publicId:req.params.publicId,status:'in_progress',assignedUserId:req.user._id}).populate('warehouseId');if(!task)throw new AppError('Claim this warehouse task before completing it.',409,'WAREHOUSE_TASK_NOT_OWNED');if(req.user.role!=='super_admin')assertOperationalCountry(req.user,task.warehouseId.country,'Warehouse task not found.');assertWarehouseScope(req.user,task.warehouseId.publicId);await executeWarehouseTask({task,actorUserId:req.user._id,disposition:String(req.body.disposition||'')});await writeAudit(req,'warehouse.task_completed',{targetType:'warehouse_task',targetPublicId:task.publicId,country:task.warehouseId.country});res.redirect('/operations/logistics');}));
router.post('/operations/logistics/cycle-count',warehouseOpsOnly,asyncHandler(async(req,res)=>{const stock=await StockItem.findOne({publicId:String(req.body.stockPublicId||'')}).populate('warehouseId');if(!stock)throw new AppError('Stock item not found.',404,'STOCK_NOT_FOUND');if(req.user.role!=='super_admin')assertOperationalCountry(req.user,stock.warehouseId.country,'Stock item not found.');assertWarehouseScope(req.user,stock.warehouseId.publicId);const discrepancy=await completeCycleCount({stockItem:stock,countedOnHand:Number(req.body.countedOnHand),actorUserId:req.user._id,reason:String(req.body.reason||'Cycle count').slice(0,300)});await writeAudit(req,'warehouse.cycle_count_recorded',{targetType:'inventory_discrepancy',targetPublicId:discrepancy.publicId,country:stock.warehouseId.country,metadata:{variance:discrepancy.variance,status:discrepancy.status}});setFlash(req,'success',discrepancy.status==='no_variance'?'Cycle count matched system stock. No adjustment was needed.':'Cycle-count variance recorded. A different supervisor must review it before stock changes.');res.redirect('/operations/logistics');}));
router.post('/operations/logistics/discrepancies/:publicId/review',adminLogisticsOnly,asyncHandler(async(req,res)=>{const discrepancy=await InventoryDiscrepancy.findOne({publicId:req.params.publicId,...countryScope(req),status:'pending_review'});if(!discrepancy)throw new AppError('Pending inventory discrepancy not found.',404,'INVENTORY_DISCREPANCY_NOT_FOUND');const decision=String(req.body.decision||'');const reviewed=await reviewInventoryDiscrepancy({discrepancyPublicId:discrepancy.publicId,decision,actorUserId:req.user._id,reviewNote:String(req.body.reviewNote||'').slice(0,300)});await writeAudit(req,`warehouse.inventory_discrepancy_${reviewed.status}`,{targetType:'inventory_discrepancy',targetPublicId:reviewed.publicId,country:reviewed.country,metadata:{variance:reviewed.variance,adjustmentMovementId:String(reviewed.adjustmentMovementId||'')}});setFlash(req,'success',reviewed.status==='approved'?'Inventory discrepancy approved and adjusted transactionally.':'Inventory discrepancy rejected; stock was not changed.');res.redirect('/operations/logistics');}));
router.post('/operations/logistics/exceptions/:publicId/resolve',adminLogisticsOnly,asyncHandler(async(req,res)=>{const exception=await DeliveryException.findOne({publicId:req.params.publicId,...countryScope(req),status:{$in:['open','investigating']}});if(!exception)throw new AppError('Open delivery exception not found.',404,'DELIVERY_EXCEPTION_NOT_FOUND');const updated=await resolveDeliveryException({exceptionPublicId:exception.publicId,actorUserId:req.user._id,decision:String(req.body.decision||''),resolutionNote:String(req.body.resolutionNote||'')});await writeAudit(req,`delivery.exception_${updated.status}`,{targetType:'delivery_exception',targetPublicId:updated.publicId,country:updated.country,metadata:{type:updated.type,shipmentPublicId:updated.shipmentPublicId}});setFlash(req,'success',`Delivery exception ${updated.publicId} marked ${updated.status}.`);res.redirect('/operations/logistics');}));
router.post('/operations/logistics/shipments/:publicId/reconcile-cod',financeLogisticsOnly,asyncHandler(async(req,res)=>{const shipment=await Shipment.findOne({publicId:req.params.publicId,...countryScope(req)});if(!shipment)throw new AppError('Shipment not found.',404,'SHIPMENT_NOT_FOUND');await reconcileCod({shipment,actorUserId:req.user._id});res.redirect('/operations/logistics');}));
router.post('/operations/logistics/cod-reconciliation',financeLogisticsOnly,asyncHandler(async(req,res)=>{const profile=await DeliveryProfile.findOne({publicId:String(req.body.deliveryProfileId||''),...countryScope(req),verificationStatus:'approved'});if(!profile)throw new AppError('Approved delivery partner not found.',404,'DELIVERY_NOT_FOUND');await reconcileCodBatch({country:profile.country,deliveryUserId:profile.userId,businessDate:String(req.body.businessDate||''),currency:String(req.body.currency||req.user.currency).toUpperCase(),declaredAmountMinor:Number(req.body.declaredAmountMinor),actorUserId:req.user._id});setFlash(req,'success','Driver/day COD batch reconciled to the ledger.');res.redirect('/operations/logistics');}));

router.post('/api/v1/delivery/actions',noStore,requireAuth,requireVerified,requireOnboarding,requirePermission('delivery:manage'),asyncHandler(async(req,res)=>{
 const input=req.body||{};const clientActionId=String(input.clientActionId||'').trim();const action=String(input.action||'').trim();const shipmentId=String(input.shipmentId||'').trim();
 if(!/^[A-Za-z0-9._:-]{8,120}$/.test(clientActionId)||!['picked_up','in_transit','delivered','failed','rescheduled','return_to_sender','returned'].includes(action)||shipmentId.length<4)throw new AppError('Offline action payload is invalid.',422,'ACTION_INVALID');
 const existing=await OperationAction.findOne({userId:req.user._id,clientActionId}).lean();if(existing)return res.json({action:existing,duplicate:true});
 const profile=await DeliveryProfile.findOne({userId:req.user._id}).select('country').lean();if(!profile)throw new AppError('Delivery profile not found.',404,'DELIVERY_NOT_FOUND');
 const shipment=await Shipment.findOne({publicId:shipmentId,deliveryUserId:req.user._id,country:profile.country}).select('+pickupCodeHash +deliveryCodeHash');if(!shipment)throw new AppError('Assigned shipment not found.',404,'SHIPMENT_NOT_FOUND');
 let record;try{record=await OperationAction.create({publicId:publicId('opa'),clientActionId,userId:req.user._id,country:shipment.country,action,targetPublicId:shipmentId,status:'processing'});}catch(error){if(error?.code===11000){const duplicate=await OperationAction.findOne({userId:req.user._id,clientActionId}).lean();return res.json({action:duplicate,duplicate:true});}throw error;}
 try{const updated=await transitionShipment({shipment,nextStatus:action,actorUserId:req.user._id,proofCode:String(input.proofCode||''),reason:String(input.reason||''),reasonCode:String(input.reasonCode||'other'),rescheduledFor:input.rescheduledFor});record.status='completed';record.result={shipmentStatus:updated.status};await record.save();res.json({action:record,shipment:{publicId:updated.publicId,status:updated.status}});}catch(error){record.status='failed';record.error=String(error.message||'Action failed').slice(0,400);await record.save();throw error;}
}));

export default router;
