import { Router } from 'express';
import { asyncHandler, AppError } from '../core/errors.js';
import { publicId } from '../core/ids.js';
import { DeliveryOffer, DeliveryProfile, EvidenceDocument, OperationAction, Order, Parcel, ReconciliationRun, Shipment, ShippingZone, StockItem, Store, Warehouse, WarehouseTask } from '../models/index.js';
import { requireAuth, requireOnboarding, requirePermission, requireVerified } from '../middleware/auth.js';
import { noStore } from '../middleware/request.js';
import { verifyDeferredCsrf } from '../middleware/csrf.js';
import { setFlash } from '../middleware/view.js';
import { writeAudit } from '../services/audit.js';
import { acceptDeliveryOffer, completeCycleCount, createWarehouseTask, ensureShipmentForOrder, executeWarehouseTask, offerShipment, reconcileCod, reconcileCodBatch, transitionShipment } from '../services/logistics.js';
import { sanitizeAndStoreEvidenceImage, uploadVerificationImage } from '../services/media.js';

const router=Router();
function countryScope(request){return request.user.role==='super_admin'?{}:{country:request.user.country};}
router.use('/delivery',noStore,requireAuth,requireVerified,requireOnboarding,requirePermission('delivery:manage'));
router.use('/operations/logistics',noStore,requireAuth,requireVerified,requireOnboarding,(req,res,next)=>{
 if(['super_admin','country_admin','warehouse','finance'].includes(req.user.role)) return next();
 return next(new AppError('Logistics operations permission required.',403,'FORBIDDEN'));
});
const adminLogisticsOnly=(req,_res,next)=>['super_admin','country_admin'].includes(req.user.role)?next():next(new AppError('Country logistics administration permission required.',403,'FORBIDDEN'));
const warehouseOpsOnly=(req,_res,next)=>['super_admin','country_admin','warehouse'].includes(req.user.role)?next():next(new AppError('Warehouse operations permission required.',403,'FORBIDDEN'));
const financeLogisticsOnly=(req,_res,next)=>['super_admin','country_admin','finance'].includes(req.user.role)?next():next(new AppError('Finance reconciliation permission required.',403,'FORBIDDEN'));
function upload(middleware){return(req,res,next)=>middleware(req,res,error=>{if(error)return next(error);try{verifyDeferredCsrf(req);return next();}catch(csrfError){return next(csrfError);}});}
function maskPhone(value){const clean=String(value||'').replace(/\s+/g,'');if(clean.length<=4)return '••••';return `${'•'.repeat(Math.min(8,Math.max(4,clean.length-4)))}${clean.slice(-4)}`;}
function navigationUrl(contact){const query=[contact?.address,contact?.city,contact?.country].filter(Boolean).join(', ');return query?`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(query)}`:'';}

router.get('/delivery', asyncHandler(async(req,res)=>{
 const profile=await DeliveryProfile.findOneAndUpdate({userId:req.user._id},{$setOnInsert:{publicId:publicId('dlv'),country:req.user.country,transport:'motorcycle'}},{upsert:true,returnDocument:'after',setDefaultsOnInsert:true});
 const [jobs,offers,profileEvidence]=await Promise.all([Shipment.find({country:req.user.country,deliveryUserId:req.user._id}).sort({createdAt:-1}).limit(100).lean(),DeliveryOffer.find({country:req.user.country,deliveryUserId:req.user._id,status:'offered',expiresAt:{$gt:new Date()}}).sort({createdAt:-1}).limit(50).lean(),EvidenceDocument.find({contextType:'delivery_verification',contextPublicId:profile.publicId,status:'ready'}).select('publicId documentType description createdAt').sort({createdAt:-1}).lean()]);
 const orderIds=jobs.map(job=>job.orderId).filter(Boolean);const orders=orderIds.length?await Order.find({_id:{$in:orderIds}}).select('publicId contact').lean():[];const orderById=new Map(orders.map(order=>[String(order._id),order]));
 const deliveryJobs=jobs.map(job=>{const order=orderById.get(String(job.orderId));const contact=order?.contact||{};return{...job,destination:{fullName:contact.fullName||'',address:contact.address||'',city:contact.city||'',note:contact.note||'',maskedPhone:maskPhone(contact.phone),navigationUrl:navigationUrl(contact)}};});
 res.render('logistics-workspace',{mode:'delivery',profile,profileEvidence,jobs:deliveryJobs,offers,tasks:[],zones:[],warehouses:[],stock:[],parcels:[],codRuns:[],deliveryEvidenceByProfile:{}});
}));
router.post('/delivery/profile',asyncHandler(async(req,res)=>{
 const transport=String(req.body.transport||''); if(!['bicycle','motorcycle','car','van','truck','other'].includes(transport))throw new AppError('Choose a valid transport mode.',422,'TRANSPORT_INVALID');
 const areas=String(req.body.serviceAreas||'').split(',').map(v=>v.trim()).filter(Boolean).slice(0,30);const profile=await DeliveryProfile.findOne({userId:req.user._id});if(!profile)throw new AppError('Delivery profile not found.',404,'DELIVERY_NOT_FOUND');
 profile.transport=transport;profile.vehicleLabel=String(req.body.vehicleLabel||'').trim().slice(0,120);profile.serviceAreas=areas;profile.available=false;profile.verificationStatus='draft';
 if(String(req.body.action||'save')==='submit'){const evidence=await EvidenceDocument.find({contextType:'delivery_verification',contextPublicId:profile.publicId,status:'ready'}).select('documentType').lean();const types=new Set(evidence.map(doc=>doc.documentType));if(!types.has('identity'))throw new AppError('Upload an identity verification image before submitting.',422,'DELIVERY_IDENTITY_REQUIRED');if(transport!=='bicycle'&&!types.has('vehicle')&&!types.has('permit'))throw new AppError('Upload a vehicle or driving-permit verification image before submitting.',422,'DELIVERY_VEHICLE_DOCUMENT_REQUIRED');profile.verificationStatus='submitted';profile.reviewReason='';}
 await profile.save();setFlash(req,'success',profile.verificationStatus==='submitted'?'Delivery profile submitted for verification.':'Delivery profile saved.'); res.redirect('/delivery');
}));
router.post('/delivery/profile/evidence',upload(uploadVerificationImage),asyncHandler(async(req,res)=>{const profile=await DeliveryProfile.findOne({userId:req.user._id});if(!profile)throw new AppError('Delivery profile not found.',404,'DELIVERY_NOT_FOUND');const documentType=String(req.body.documentType||'');if(!['identity','vehicle','permit'].includes(documentType))throw new AppError('Choose a valid verification document type.',422,'DELIVERY_DOCUMENT_TYPE_INVALID');await sanitizeAndStoreEvidenceImage({file:req.file,user:req.user,country:profile.country,contextType:'delivery_verification',contextPublicId:profile.publicId,documentType,description:String(req.body.description||documentType).slice(0,300)});if(profile.verificationStatus!=='approved')profile.verificationStatus='draft';profile.available=false;await profile.save();setFlash(req,'success','Verification image uploaded securely.');res.redirect('/delivery');}));
router.post('/delivery/availability',asyncHandler(async(req,res)=>{
 const profile=await DeliveryProfile.findOne({userId:req.user._id}); if(!profile||profile.verificationStatus!=='approved')throw new AppError('Approved delivery verification is required.',409,'DELIVERY_NOT_APPROVED'); profile.available=String(req.body.available)==='true';await profile.save();res.redirect('/delivery');
}));
router.post('/delivery/offers/:publicId/accept',asyncHandler(async(req,res)=>{
 const profile=await DeliveryProfile.findOne({userId:req.user._id,verificationStatus:'approved',available:true});if(!profile)throw new AppError('You must be approved and available.',409,'DELIVERY_NOT_AVAILABLE');
 const offer=await DeliveryOffer.findOne({publicId:req.params.publicId,deliveryUserId:req.user._id,country:req.user.country,status:'offered'});if(!offer)throw new AppError('Delivery offer not found.',404,'OFFER_NOT_FOUND');
 const shipment=await acceptDeliveryOffer({offer,actorUserId:req.user._id});await writeAudit(req,'delivery.assignment_accepted',{targetType:'shipment',targetPublicId:shipment.publicId});res.redirect('/delivery');
}));
for(const action of ['picked_up','in_transit','delivered','failed','rescheduled','return_to_sender','returned']){
 router.post(`/delivery/jobs/:publicId/${action}`,asyncHandler(async(req,res)=>{const shipment=await Shipment.findOne({publicId:req.params.publicId,deliveryUserId:req.user._id,country:req.user.country}).select('+pickupCodeHash +deliveryCodeHash');if(!shipment)throw new AppError('Assigned shipment not found.',404,'SHIPMENT_NOT_FOUND');await transitionShipment({shipment,nextStatus:action,actorUserId:req.user._id,proofCode:String(req.body.proofCode||''),reason:String(req.body.reason||''),rescheduledFor:req.body.rescheduledFor});res.redirect('/delivery');}));
}

router.get('/operations/logistics',asyncHandler(async(req,res)=>{
 const scope=countryScope(req); const [profiles,jobs,zones,warehouses]=await Promise.all([
  DeliveryProfile.find(scope).populate('userId','name email phone').sort({createdAt:-1}).limit(100).lean(), Shipment.find(scope).sort({createdAt:-1}).limit(100).lean(), ShippingZone.find(scope).sort({createdAt:-1}).limit(100).lean(), Warehouse.find(scope).sort({createdAt:-1}).limit(100).lean()
 ]); const warehouseIds=warehouses.map(w=>w._id); const shipmentIds=jobs.map(j=>j._id);const profileIds=profiles.map(profile=>profile.publicId); const [tasks,stock,parcels,offers,deliveryEvidence,codRuns]=await Promise.all([WarehouseTask.find({warehouseId:{$in:warehouseIds}}).populate('warehouseId','name country').sort({createdAt:-1}).limit(100).lean(),StockItem.find({warehouseId:{$in:warehouseIds}}).populate('warehouseId','name country').populate('variantId','sku title').limit(100).lean(),Parcel.find({shipmentId:{$in:shipmentIds}}).sort({createdAt:-1}).limit(200).lean(),DeliveryOffer.find({shipmentId:{$in:shipmentIds}}).sort({createdAt:-1}).limit(100).lean(),EvidenceDocument.find({contextType:'delivery_verification',contextPublicId:{$in:profileIds},status:'ready'}).select('publicId contextPublicId documentType description createdAt').sort({createdAt:-1}).lean(),ReconciliationRun.find({...scope,provider:'cod'}).populate('deliveryUserId','name email').sort({createdAt:-1}).limit(50).lean()]);const deliveryEvidenceByProfile={};for(const doc of deliveryEvidence){(deliveryEvidenceByProfile[doc.contextPublicId]??=[]).push(doc);}const capabilities={admin:['super_admin','country_admin'].includes(req.user.role),warehouse:['super_admin','country_admin','warehouse'].includes(req.user.role),finance:['super_admin','country_admin','finance'].includes(req.user.role)};res.render('logistics-workspace',{mode:'operations',profiles,jobs,zones,warehouses,tasks,stock,parcels,offers,capabilities,deliveryEvidenceByProfile,codRuns});
}));
router.post('/operations/logistics/delivery/:publicId/review',adminLogisticsOnly,asyncHandler(async(req,res)=>{const profile=await DeliveryProfile.findOne({publicId:req.params.publicId,...countryScope(req),verificationStatus:'submitted'});if(!profile)throw new AppError('Submitted delivery profile not found.',404,'DELIVERY_NOT_FOUND');const decision=String(req.body.decision||'');if(!['approve','reject'].includes(decision))throw new AppError('Choose approve or reject.',422,'DELIVERY_REVIEW_INVALID');if(decision==='approve'){const evidence=await EvidenceDocument.find({contextType:'delivery_verification',contextPublicId:profile.publicId,status:'ready'}).select('documentType').lean();const types=new Set(evidence.map(doc=>doc.documentType));if(!types.has('identity'))throw new AppError('Identity evidence is required before approval.',409,'DELIVERY_IDENTITY_REQUIRED');if(profile.transport!=='bicycle'&&!types.has('vehicle')&&!types.has('permit'))throw new AppError('Vehicle or permit evidence is required before approval.',409,'DELIVERY_VEHICLE_DOCUMENT_REQUIRED');}profile.verificationStatus=decision==='approve'?'approved':'rejected';profile.codEnabled=decision==='approve'&&String(req.body.codEnabled)==='true';profile.reviewReason=String(req.body.reason||'').trim().slice(0,500);if(decision==='reject'&&!profile.reviewReason)throw new AppError('A rejection reason is required.',422,'DELIVERY_REVIEW_REASON_REQUIRED');profile.approvedAt=decision==='approve'?new Date():undefined;profile.reviewedAt=new Date();profile.reviewedByUserId=req.user._id;profile.available=false;await profile.save();await writeAudit(req,`delivery.profile_${decision==='approve'?'approved':'rejected'}`,{targetType:'delivery_profile',targetPublicId:profile.publicId});res.redirect('/operations/logistics');}));
router.post('/operations/logistics/shipments/:publicId/offer',adminLogisticsOnly,asyncHandler(async(req,res)=>{const shipment=await Shipment.findOne({publicId:req.params.publicId,...countryScope(req)});if(!shipment)throw new AppError('Shipment not found.',404,'SHIPMENT_NOT_FOUND');const profile=await DeliveryProfile.findOne({publicId:String(req.body.deliveryProfileId||''),verificationStatus:'approved',available:true,...countryScope(req)});if(!profile)throw new AppError('Approved available delivery partner not found.',404,'DELIVERY_NOT_FOUND');if(shipment.cod?.required&&!profile.codEnabled)throw new AppError('This delivery partner is not approved to collect COD.',409,'DELIVERY_COD_NOT_ALLOWED');await offerShipment({shipment,deliveryUserId:profile.userId,earningMinor:Math.max(0,Number(req.body.earningMinor||0)),currency:String(shipment.cod?.currency||req.user.currency).toUpperCase(),actorUserId:req.user._id});res.redirect('/operations/logistics');}));
router.post('/operations/logistics/orders/:publicId/shipment',adminLogisticsOnly,asyncHandler(async(req,res)=>{const order=await Order.findOne({publicId:req.params.publicId,...countryScope(req)});if(!order)throw new AppError('Order not found.',404,'ORDER_NOT_FOUND');await ensureShipmentForOrder(order,req.user._id);res.redirect('/operations/logistics');}));
router.post('/operations/logistics/zones',adminLogisticsOnly,asyncHandler(async(req,res)=>{const country=String(req.body.country||req.user.country).toUpperCase();if(req.user.role!=='super_admin'&&country!==req.user.country)throw new AppError('Country scope violation.',403,'COUNTRY_SCOPE');const currency=String(req.body.currency||req.user.currency).toUpperCase();await ShippingZone.create({publicId:publicId('zon'),country,name:String(req.body.name||'').trim(),cities:String(req.body.cities||'').split(',').map(v=>v.trim()).filter(Boolean),standardFeeMinor:Number(req.body.standardFeeMinor||0),expressFeeMinor:Number(req.body.expressFeeMinor||0),currency,standardSlaHours:Number(req.body.standardSlaHours||120),expressSlaHours:Number(req.body.expressSlaHours||48)});res.redirect('/operations/logistics');}));
router.post('/operations/logistics/tasks',warehouseOpsOnly,asyncHandler(async(req,res)=>{const warehouse=await Warehouse.findOne({publicId:String(req.body.warehousePublicId||''),...(req.user.role==='super_admin'?{}:{country:req.user.country}),active:true});if(!warehouse)throw new AppError('Warehouse not found.',404,'WAREHOUSE_NOT_FOUND');const type=String(req.body.type||'');if(!['receive','put_away','pick','pack','dispatch','cycle_count','transfer','return_inspection'].includes(type))throw new AppError('Warehouse task type is invalid.',422,'TASK_TYPE_INVALID');let stockItem=null;if(req.body.stockPublicId)stockItem=await StockItem.findOne({publicId:String(req.body.stockPublicId),warehouseId:warehouse._id});let destinationWarehouse=null;if(req.body.destinationWarehousePublicId)destinationWarehouse=await Warehouse.findOne({publicId:String(req.body.destinationWarehousePublicId),storeId:warehouse.storeId,active:true});let parcel=null;if(req.body.parcelPublicId){const store=await Store.findById(warehouse.storeId).lean();parcel=await Parcel.findOne({publicId:String(req.body.parcelPublicId),storePublicId:store?.publicId});if(!parcel)throw new AppError('Parcel is outside this warehouse store scope.',403,'PARCEL_SCOPE');}const quantity=Number(req.body.quantity||0);if(!Number.isSafeInteger(quantity)||quantity<0)throw new AppError('Task quantity must be a whole non-negative number.',422,'TASK_QUANTITY_INVALID');await createWarehouseTask({warehouseId:warehouse._id,storeId:warehouse.storeId,type,reference:String(req.body.reference||'').slice(0,120),notes:String(req.body.notes||'').slice(0,500),assignedUserId:req.user._id,stockItemId:stockItem?._id,variantId:stockItem?.variantId,destinationWarehouseId:destinationWarehouse?._id,parcelId:parcel?._id,quantity,binCode:String(req.body.binCode||'').trim().slice(0,80),disposition:['good','damaged','quarantine'].includes(String(req.body.disposition||''))?String(req.body.disposition):''});res.redirect('/operations/logistics');}));
router.post('/operations/logistics/tasks/:publicId/complete',warehouseOpsOnly,asyncHandler(async(req,res)=>{const task=await WarehouseTask.findOne({publicId:req.params.publicId,status:{$in:['open','in_progress']}}).populate('warehouseId');if(!task|| (req.user.role!=='super_admin'&&task.warehouseId.country!==req.user.country))throw new AppError('Warehouse task not found.',404,'TASK_NOT_FOUND');await executeWarehouseTask({task,actorUserId:req.user._id,disposition:String(req.body.disposition||'')});res.redirect('/operations/logistics');}));
router.post('/operations/logistics/cycle-count',warehouseOpsOnly,asyncHandler(async(req,res)=>{const stock=await StockItem.findOne({publicId:String(req.body.stockPublicId||'')}).populate('warehouseId');if(!stock||(req.user.role!=='super_admin'&&stock.warehouseId.country!==req.user.country))throw new AppError('Stock item not found.',404,'STOCK_NOT_FOUND');await completeCycleCount({stockItem:stock,countedOnHand:Number(req.body.countedOnHand),actorUserId:req.user._id,reason:String(req.body.reason||'Cycle count').slice(0,300)});res.redirect('/operations/logistics');}));
router.post('/operations/logistics/shipments/:publicId/reconcile-cod',financeLogisticsOnly,asyncHandler(async(req,res)=>{const shipment=await Shipment.findOne({publicId:req.params.publicId,...countryScope(req)});if(!shipment)throw new AppError('Shipment not found.',404,'SHIPMENT_NOT_FOUND');await reconcileCod({shipment,actorUserId:req.user._id});res.redirect('/operations/logistics');}));
router.post('/operations/logistics/cod-reconciliation',financeLogisticsOnly,asyncHandler(async(req,res)=>{const profile=await DeliveryProfile.findOne({publicId:String(req.body.deliveryProfileId||''),...countryScope(req),verificationStatus:'approved'});if(!profile)throw new AppError('Approved delivery partner not found.',404,'DELIVERY_NOT_FOUND');await reconcileCodBatch({country:profile.country,deliveryUserId:profile.userId,businessDate:String(req.body.businessDate||''),currency:String(req.body.currency||req.user.currency).toUpperCase(),declaredAmountMinor:Number(req.body.declaredAmountMinor),actorUserId:req.user._id});setFlash(req,'success','Driver/day COD batch reconciled to the ledger.');res.redirect('/operations/logistics');}));

router.post('/api/v1/delivery/actions',noStore,requireAuth,requireVerified,requireOnboarding,requirePermission('delivery:manage'),asyncHandler(async(req,res)=>{
 const input=req.body||{};const clientActionId=String(input.clientActionId||'').trim();const action=String(input.action||'').trim();const shipmentId=String(input.shipmentId||'').trim();
 if(!/^[A-Za-z0-9._:-]{8,120}$/.test(clientActionId)||!['picked_up','in_transit','delivered','failed','rescheduled','return_to_sender','returned'].includes(action)||shipmentId.length<4)throw new AppError('Offline action payload is invalid.',422,'ACTION_INVALID');
 const existing=await OperationAction.findOne({userId:req.user._id,clientActionId}).lean();if(existing)return res.json({action:existing,duplicate:true});
 let record;try{record=await OperationAction.create({publicId:publicId('opa'),clientActionId,userId:req.user._id,country:req.user.country,action,targetPublicId:shipmentId,status:'processing'});}catch(error){if(error?.code===11000){const duplicate=await OperationAction.findOne({userId:req.user._id,clientActionId}).lean();return res.json({action:duplicate,duplicate:true});}throw error;}
 try{const shipment=await Shipment.findOne({publicId:shipmentId,deliveryUserId:req.user._id,country:req.user.country}).select('+pickupCodeHash +deliveryCodeHash');if(!shipment)throw new AppError('Assigned shipment not found.',404,'SHIPMENT_NOT_FOUND');const updated=await transitionShipment({shipment,nextStatus:action,actorUserId:req.user._id,proofCode:String(input.proofCode||''),reason:String(input.reason||''),rescheduledFor:input.rescheduledFor});record.status='completed';record.result={shipmentStatus:updated.status};await record.save();res.json({action:record,shipment:{publicId:updated.publicId,status:updated.status}});}catch(error){record.status='failed';record.error=String(error.message||'Action failed').slice(0,400);await record.save();throw error;}
}));

export default router;
