import { Router } from 'express';
import { z } from 'zod';
import { AppError } from '../core/errors.js';
import { hasPermission } from '../core/roles.js';
import { requireAuth, requireVerified } from '../middleware/auth.js';
import { PaymentIntent, LedgerTransaction, LedgerAccount, Order, Refund, PayoutAccount, Payout, ReconciliationRun, Store } from '../models/index.js';
import { initiatePayment, getPaymentIntentForOrder, verifyAndApplyPayment, processFlutterwaveWebhook, createRefund, completeManualRefund, savePayoutAccount, requestPayout, submitPayout, reconcilePayments, releasePayoutHold, payoutOwnerContext, payoutAccountsForRequest, payoutsForRequest } from '../services/payments.js';
import { moneySummary } from '../services/money.js';

const router=Router();
const idem=z.string().trim().min(12).max(120);
router.post('/api/v1/orders/:orderId/payment-intents',async(req,res,next)=>{try{res.status(201).json({payment:await initiatePayment(req,{orderId:req.params.orderId,idempotencyKey:idem.parse(req.body.idempotencyKey)})});}catch(e){next(e);}});
router.get('/api/v1/orders/:orderId/payment',async(req,res,next)=>{try{const {intent}=await getPaymentIntentForOrder(req,req.params.orderId);res.set('Cache-Control','private, no-store').json({payment:intent?{id:intent.publicId,status:intent.status,provider:intent.provider,method:intent.method,amountMinor:intent.amountMinor,currency:intent.currency,paidAt:intent.paidAt}:null});}catch(e){next(e);}});
router.get('/payments/return',async(req,res,next)=>{try{const txRef=String(req.query.tx_ref||'');const transactionId=String(req.query.transaction_id||'');const intent=txRef?await PaymentIntent.findOne({providerReference:txRef}):null;if(intent&&transactionId)await verifyAndApplyPayment(intent.publicId,transactionId);res.redirect(`/track-order?order=${encodeURIComponent(intent?.orderPublicId||'')}`);}catch(e){next(e);}});
router.post('/webhooks/flutterwave',async(req,res,next)=>{try{await processFlutterwaveWebhook(req.rawBody||JSON.stringify(req.body||{}),req.body,req.get('flutterwave-signature'));res.sendStatus(200);}catch(e){next(e);}});
function financeOnly(req,_res,next){if(hasPermission(req.user,'finance:manage')||hasPermission(req.user,'finance:country')||req.user?.role==='super_admin')return next();return next(new AppError('Finance permission required.',403,'FORBIDDEN'));}
router.post('/api/v1/finance/refunds',requireAuth,requireVerified,financeOnly,async(req,res,next)=>{try{const input=z.object({orderId:z.string().min(4).max(100),amountMinor:z.coerce.number().int().positive().optional(),reason:z.string().trim().min(3).max(300),idempotencyKey:idem}).parse(req.body);res.status(201).json({refund:await createRefund(req,input)});}catch(e){next(e);}});
router.post('/api/v1/finance/refunds/:id/manual-complete',requireAuth,requireVerified,financeOnly,async(req,res,next)=>{try{const input=z.object({reference:z.string().trim().min(4).max(180)}).parse(req.body);res.json({refund:await completeManualRefund(req,req.params.id,input)});}catch(e){next(e);}});
router.get('/finance',requireAuth,requireVerified,financeOnly,async(req,res,next)=>{try{
  const country=req.user.role==='super_admin'?undefined:req.user.country;const q=country?{country}:{};
  const orderScope=country?{country,status:{$in:['paid','partially_refunded']}}:{status:{$in:['paid','partially_refunded']}};
  const refundableOrders=await Order.find(orderScope).select('publicId status totals contact createdAt').sort({createdAt:-1}).limit(100).lean();
  const orderIds=refundableOrders.map(row=>row._id);
  const [countryOrderIds,payoutAccountIds]=await Promise.all([
    country?Order.find({country}).distinct('_id'):Promise.resolve(null),
    country?PayoutAccount.find({country}).distinct('_id'):Promise.resolve(null),
  ]);
  const [accounts,transactions,refunds,payouts,reconciliations,payoutAccounts,refundTotals]=await Promise.all([
    LedgerAccount.find(q).sort({createdAt:-1}).limit(100).lean(),
    LedgerTransaction.find(q).sort({postedAt:-1}).limit(100).lean(),
    Refund.find(countryOrderIds?{orderId:{$in:countryOrderIds}}:{}).sort({createdAt:-1}).limit(50).lean(),
    Payout.find(payoutAccountIds?{payoutAccountId:{$in:payoutAccountIds}}:{}).sort({createdAt:-1}).limit(50).lean(),
    ReconciliationRun.find(country?{country}:{}).sort({createdAt:-1}).limit(20).lean(),
    PayoutAccount.find(q).select('-destinationEncrypted').sort({createdAt:-1}).limit(100).lean(),
    orderIds.length?Refund.aggregate([{$match:{orderId:{$in:orderIds},status:{$in:['processing','completed']}}},{$group:{_id:'$orderId',total:{$sum:'$amountMinor'}}}]):[],
  ]);
  const refundedByOrder=new Map(refundTotals.map(row=>[String(row._id),Number(row.total||0)]));
  const eligibleRefundOrders=refundableOrders.map(order=>({...order,remainingMinor:Math.max(0,Number(order.totals.totalMinor||0)-(refundedByOrder.get(String(order._id))||0))})).filter(order=>order.remainingMinor>0);
  res.set('Cache-Control','private, no-store');res.render('money-workspace',{accounts,transactions,refunds,payouts,reconciliations,payoutAccounts,eligibleRefundOrders});
}catch(e){next(e);}});
router.post('/api/v1/payout-accounts',requireAuth,requireVerified,async(req,res,next)=>{try{const input=z.object({method:z.enum(['mobile_money','bank']),label:z.string().trim().min(2).max(100),destination:z.object({account_bank:z.string().trim().min(2).max(40).optional(),network:z.string().trim().min(2).max(40).optional(),account_number:z.string().trim().min(4).max(80).optional(),phone:z.string().trim().min(7).max(32).optional(),beneficiary_name:z.string().trim().min(2).max(120)}).refine(v=>(v.account_bank||v.network)&&(v.account_number||v.phone),{message:'Bank/network and account/phone are required.'})}).parse(req.body);res.status(201).json({account:await savePayoutAccount(req,input)});}catch(e){next(e);}});
router.get('/api/v1/payout-accounts',requireAuth,requireVerified,async(req,res,next)=>{try{res.json({accounts:await payoutAccountsForRequest(req)});}catch(e){next(e);}});
router.post('/api/v1/payouts',requireAuth,requireVerified,async(req,res,next)=>{try{const input=z.object({payoutAccountId:z.string().min(4).max(100),amountMinor:z.coerce.number().int().positive(),idempotencyKey:idem}).parse(req.body);res.status(201).json({payout:await requestPayout(req,input)});}catch(e){next(e);}});
router.post('/api/v1/finance/payout-accounts/:id/verify',requireAuth,requireVerified,financeOnly,async(req,res,next)=>{try{const account=await PayoutAccount.findOne({publicId:req.params.id});if(account&&req.user.role!=='super_admin'&&account.country!==req.user.country)throw new AppError('Payout account is outside your country scope.',403,'COUNTRY_SCOPE');if(!account)throw new AppError('Payout account not found.',404,'PAYOUT_ACCOUNT_NOT_FOUND');account.status='verified';account.verifiedAt=new Date();await account.save();res.json({ok:true});}catch(e){next(e);}});
router.post('/api/v1/finance/payouts/:id/approve',requireAuth,requireVerified,financeOnly,async(req,res,next)=>{try{const payout=await Payout.findOne({publicId:req.params.id,status:'requested'});if(payout&&req.user.role!=='super_admin'){const pa=await PayoutAccount.findById(payout.payoutAccountId).lean();if(pa?.country!==req.user.country)throw new AppError('Payout is outside your country scope.',403,'COUNTRY_SCOPE');}if(!payout)throw new AppError('Requested payout not found.',404,'PAYOUT_NOT_FOUND');if((payout.requestedByUserId||payout.ownerUserId).equals(req.user._id))throw new AppError('You cannot approve a payout you requested.',403,'FOUR_EYES_REQUIRED');payout.status='approved';payout.approvedByUserId=req.user._id;payout.approvedAt=new Date();await payout.save();res.json({ok:true,payout});}catch(e){next(e);}});
router.post('/api/v1/finance/reconciliation',requireAuth,requireVerified,financeOnly,async(req,res,next)=>{try{const input=z.object({hours:z.coerce.number().int().min(1).max(168).default(24)}).parse(req.body||{});res.status(201).json({run:await reconcilePayments(req,input)});}catch(e){next(e);}});
router.post('/api/v1/finance/payouts/:id/submit',requireAuth,requireVerified,financeOnly,async(req,res,next)=>{try{res.json({payout:await submitPayout(req,req.params.id)});}catch(e){next(e);}});

router.get('/money',requireAuth,requireVerified,async(req,res,next)=>{try{const owner=await payoutOwnerContext(req);const [accounts,payoutAccounts,payouts]=await Promise.all([moneySummary({ownerType:owner.ownerType,ownerPublicId:owner.ownerPublicId,country:owner.country,currency:owner.currency}),payoutAccountsForRequest(req),payoutsForRequest(req)]);res.set('Cache-Control','private, no-store').render('payout-workspace',{accounts,payoutAccounts,payouts,owner});}catch(e){next(e);}});
router.post('/money/payout-accounts',requireAuth,requireVerified,async(req,res,next)=>{try{const method=z.enum(['mobile_money','bank']).parse(req.body.method);const destination={account_bank:String(req.body.account_bank||'').trim(),network:String(req.body.network||'').trim(),account_number:String(req.body.account_number||'').trim(),phone:String(req.body.phone||'').trim(),beneficiary_name:String(req.body.beneficiary_name||'').trim()};if(!(destination.account_bank||destination.network)||!(destination.account_number||destination.phone)||destination.beneficiary_name.length<2)throw new AppError('Complete the payout destination.',422,'PAYOUT_DESTINATION_INVALID');await savePayoutAccount(req,{method,label:z.string().trim().min(2).max(100).parse(req.body.label),destination});res.redirect('/money');}catch(e){next(e);}});
router.post('/money/payouts',requireAuth,requireVerified,async(req,res,next)=>{try{await requestPayout(req,{payoutAccountId:z.string().min(4).max(100).parse(req.body.payoutAccountId),amountMinor:z.coerce.number().int().positive().parse(req.body.amountMinor),idempotencyKey:idem.parse(req.body.idempotencyKey)});res.redirect('/money');}catch(e){next(e);}});
router.post('/finance/refunds',requireAuth,requireVerified,financeOnly,async(req,res,next)=>{try{const input=z.object({orderId:z.string().min(4).max(100),amountMinor:z.coerce.number().int().positive().optional(),reason:z.string().trim().min(3).max(300),idempotencyKey:idem}).parse(req.body);await createRefund(req,input);res.redirect('/finance');}catch(e){next(e);}});
router.post('/finance/refunds/:id/manual-complete',requireAuth,requireVerified,financeOnly,async(req,res,next)=>{try{const input=z.object({reference:z.string().trim().min(4).max(180)}).parse(req.body);await completeManualRefund(req,req.params.id,input);res.redirect('/finance');}catch(e){next(e);}});
router.post('/finance/reconciliation',requireAuth,requireVerified,financeOnly,async(req,res,next)=>{try{await reconcilePayments(req,{hours:z.coerce.number().int().min(1).max(168).default(24).parse(req.body.hours)});res.redirect('/finance');}catch(e){next(e);}});
router.post('/finance/payout-accounts/:id/verify',requireAuth,requireVerified,financeOnly,async(req,res,next)=>{try{const account=await PayoutAccount.findOne({publicId:req.params.id});if(!account)throw new AppError('Payout account not found.',404,'PAYOUT_ACCOUNT_NOT_FOUND');if(req.user.role!=='super_admin'&&account.country!==req.user.country)throw new AppError('Payout account is outside your country scope.',403,'COUNTRY_SCOPE');account.status='verified';account.verifiedAt=new Date();await account.save();res.redirect('/finance');}catch(e){next(e);}});
router.post('/finance/payouts/:id/approve',requireAuth,requireVerified,financeOnly,async(req,res,next)=>{try{const payout=await Payout.findOne({publicId:req.params.id,status:'requested'});if(!payout)throw new AppError('Requested payout not found.',404,'PAYOUT_NOT_FOUND');const account=await PayoutAccount.findById(payout.payoutAccountId);if(req.user.role!=='super_admin'&&account?.country!==req.user.country)throw new AppError('Payout is outside your country scope.',403,'COUNTRY_SCOPE');if((payout.requestedByUserId||payout.ownerUserId).equals(req.user._id))throw new AppError('You cannot approve a payout you requested.',403,'FOUR_EYES_REQUIRED');payout.status='approved';payout.approvedByUserId=req.user._id;payout.approvedAt=new Date();await payout.save();res.redirect('/finance');}catch(e){next(e);}});
router.post('/finance/payouts/:id/reject',requireAuth,requireVerified,financeOnly,async(req,res,next)=>{try{const payout=await Payout.findOne({publicId:req.params.id,status:{$in:['requested','approved']}});if(!payout)throw new AppError('Open payout not found.',404,'PAYOUT_NOT_FOUND');const account=await PayoutAccount.findById(payout.payoutAccountId);if(!account)throw new AppError('Payout account not found.',404,'PAYOUT_ACCOUNT_NOT_FOUND');if(req.user.role!=='super_admin'&&account.country!==req.user.country)throw new AppError('Payout is outside your country scope.',403,'COUNTRY_SCOPE');if((payout.requestedByUserId||payout.ownerUserId).equals(req.user._id))throw new AppError('You cannot reject a payout you requested.',403,'FOUR_EYES_REQUIRED');await releasePayoutHold(payout,account,String(req.body.reason||'Rejected by finance').slice(0,300));payout.status='rejected';payout.failureMessage=String(req.body.reason||'Rejected by finance').slice(0,300);await payout.save();res.redirect('/finance');}catch(e){next(e);}});
router.post('/finance/payouts/:id/submit',requireAuth,requireVerified,financeOnly,async(req,res,next)=>{try{await submitPayout(req,req.params.id);res.redirect('/finance');}catch(e){next(e);}});

export default router;
