import { Router } from 'express';
import { z } from 'zod';
import { AppError } from '../core/errors.js';
import { requireAuth, requirePermission, requireVerified } from '../middleware/auth.js';
import { loadSellerStore, requireStoreCapability } from '../middleware/store.js';
import { setFlash } from '../middleware/view.js';
import { writeAudit } from '../services/audit.js';
import { AiJob, AttributionTouch, Campaign, CampaignApplication, CommissionEntry, Product, PromoterContactRequest, PromoterVerification, Store } from '../models/index.js';
import {
  appealCommissionReversal, applyToCampaign, buildCampaignContentKit, createCampaign, createPromoterLink, promoterSummary, recordTouch, redeemPromoterCoupon, reviewCommissionAppeal,
  reviewCampaign, reviewCampaignApplication, reviewPromoterVerification, submitCampaign, submitPromoterVerification,
} from '../services/promoters.js';

const router = Router();
const adminOnly = (request, _response, next) => ['country_admin', 'super_admin'].includes(request.user?.role) ? next() : next(new AppError('Country or Super Admin required.', 403, 'FORBIDDEN'));
const campaignInput = z.object({
  name: z.string().trim().min(3).max(140), visibility: z.enum(['public', 'invite_only']).default('public'), commissionBps: z.coerce.number().int().min(0).max(5000), attributionDays: z.coerce.number().int().min(1).max(90),
  allowedChannels: z.array(z.string().trim().min(2).max(50)).max(12).default([]), facts: z.array(z.string().trim().min(2).max(240)).min(1).max(20), productPublicIds: z.array(z.string().trim().min(4).max(100)).min(1).max(100),
  assets: z.array(z.object({ type: z.enum(['image', 'video', 'document', 'copy']), url: z.string().trim().max(800).default(''), label: z.string().trim().max(120).default(''), approved: z.boolean().default(false) })).max(30).default([]),
  disclosureText: z.string().trim().min(10).max(300).default('Sponsored/affiliate promotion for Classic Mart.'), startsAt: z.coerce.date().optional(), endsAt: z.coerce.date().optional(),
}).refine(value => !value.startsAt || !value.endsAt || value.endsAt > value.startsAt, { message: 'Campaign end must be after its start.' });

function csv(value){return String(value||'').split(',').map(x=>x.trim()).filter(Boolean);}
function lines(value){return String(value||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean);}
function campaignForm(body){return campaignInput.parse({name:body.name,visibility:body.visibility,commissionBps:body.commissionBps,attributionDays:body.attributionDays,allowedChannels:csv(body.allowedChannels),facts:lines(body.facts),productPublicIds:csv(body.productPublicIds),assets:[],disclosureText:body.disclosureText,startsAt:body.startsAt||undefined,endsAt:body.endsAt||undefined});}


router.get('/r/:token', async (request, response, next) => { try { const { link, touch } = await recordTouch(request, request.params.token); if (touch.status === 'blocked') return response.status(403).render('error', { status: 403, message: 'This promotional visit was blocked by marketplace protection.' }); const separator = link.destination.includes('?') ? '&' : '?'; const params = new URLSearchParams({ utm_source: link.utmSource, utm_medium: link.utmMedium, utm_campaign: link.utmCampaign, ...(link.utmContent ? { utm_content: link.utmContent } : {}), ...(link.subId ? { sub_id: link.subId } : {}) }); response.redirect(302, `${link.destination}${separator}${params}`); } catch (error) { next(error); } });

router.post('/api/v1/promoters/verification', requireAuth, requireVerified, requirePermission('promoter:manage'), async (request, response, next) => { try { const input = z.object({ channels: z.array(z.string().trim().min(2).max(50)).min(1).max(10), niches: z.array(z.string().trim().min(2).max(50)).min(1).max(12) }).parse(request.body); response.status(201).json({ verification: await submitPromoterVerification(request, input) }); } catch (error) { next(error); } });
router.post('/api/v1/admin/promoters/:id/review', requireAuth, requireVerified, adminOnly, async (request, response, next) => { try { const input = z.object({ decision: z.enum(['approve', 'reject']), reason: z.string().trim().max(500).default('') }).parse(request.body); response.json({ verification: await reviewPromoterVerification(request, request.params.id, input) }); } catch (error) { next(error); } });

router.get('/api/v1/campaigns', async (request, response, next) => { try { const now = new Date(); const campaigns = await Campaign.find({ country: request.country.code, status: 'active', $and: [{ $or: [{ startsAt: null }, { startsAt: { $lte: now } }] }, { $or: [{ endsAt: null }, { endsAt: { $gt: now } }] }] }).select('-ownerUserId').sort({ createdAt: -1 }).limit(100).lean(); response.json({ campaigns }); } catch (error) { next(error); } });
router.post('/api/v1/seller/campaigns', requireAuth, requireVerified, loadSellerStore, requireStoreCapability('growth'), async (request, response, next) => { try { response.status(201).json({ campaign: await createCampaign(request, campaignInput.parse(request.body)) }); } catch (error) { next(error); } });
router.post('/api/v1/seller/campaigns/:id/submit', requireAuth, requireVerified, loadSellerStore, requireStoreCapability('growth'), async (request, response, next) => { try { response.json({ campaign: await submitCampaign(request, request.params.id) }); } catch (error) { next(error); } });
router.post('/api/v1/admin/campaigns/:id/review', requireAuth, requireVerified, adminOnly, async (request, response, next) => { try { const input = z.object({ decision: z.enum(['approve', 'reject']), reason: z.string().trim().max(500).default('') }).parse(request.body); response.json({ campaign: await reviewCampaign(request, request.params.id, input) }); } catch (error) { next(error); } });

router.post('/api/v1/promoters/campaigns/:id/apply', requireAuth, requireVerified, requirePermission('promoter:manage'), async (request, response, next) => { try { const input = z.object({ note: z.string().trim().max(1000).default('') }).parse(request.body || {}); response.status(201).json({ application: await applyToCampaign(request, request.params.id, input.note) }); } catch (error) { next(error); } });
router.post('/api/v1/seller/campaign-applications/:id/review', requireAuth, requireVerified, loadSellerStore, requireStoreCapability('growth'), async (request, response, next) => { try { const input = z.object({ decision: z.enum(['approve', 'reject']), reason: z.string().trim().max(500).default('') }).parse(request.body); response.json({ application: await reviewCampaignApplication(request, request.params.id, input) }); } catch (error) { next(error); } });
router.post('/api/v1/promoters/coupons/redeem', async (request, response, next) => { try { const input = z.object({ code: z.string().trim().min(2).max(32) }).parse(request.body); const { link, touch } = await redeemPromoterCoupon(request, input.code); response.json({ attribution: { linkId: link.publicId, touchId: touch.publicId, status: touch.status } }); } catch (error) { next(error); } });
router.post('/api/v1/promoters/links', requireAuth, requireVerified, requirePermission('promoter:manage'), async (request, response, next) => { try { const input = z.object({ campaignId: z.string().min(4).max(100), destination: z.string().trim().regex(/^\/[A-Za-z0-9/_?&=.%+-]*$/).max(500), couponCode: z.string().trim().max(32).optional(), subId: z.string().trim().max(80).optional(), channel: z.string().trim().max(50).optional(), utmSource: z.string().trim().max(80).optional(), utmMedium: z.string().trim().max(80).optional(), utmCampaign: z.string().trim().max(100).optional(), utmContent: z.string().trim().max(100).optional() }).parse(request.body); const link = await createPromoterLink(request, input); response.status(201).json({ link: { ...link.toObject(), url: `/r/${link.token}` } }); } catch (error) { next(error); } });


router.post('/promoter/verification', requireAuth, requireVerified, requirePermission('promoter:manage'), async (request,response,next)=>{try{await submitPromoterVerification(request,{channels:csv(request.body.channels),niches:csv(request.body.niches)});response.redirect('/promoter');}catch(error){next(error);}});
router.post('/promoter/campaigns/:id/apply', requireAuth, requireVerified, requirePermission('promoter:manage'), async(request,response,next)=>{try{await applyToCampaign(request,request.params.id,String(request.body.note||'').slice(0,1000));response.redirect('/promoter');}catch(error){next(error);}});
router.post('/promoter/links', requireAuth, requireVerified, requirePermission('promoter:manage'), async(request,response,next)=>{try{const input=z.object({campaignId:z.string().min(4).max(100),destination:z.string().trim().regex(/^\/[A-Za-z0-9/_?&=.%+-]*$/).max(500),couponCode:z.string().trim().max(32).optional(),subId:z.string().trim().max(80).optional(),channel:z.string().trim().max(50).optional(),utmSource:z.string().trim().max(80).optional(),utmMedium:z.string().trim().max(80).optional(),utmCampaign:z.string().trim().max(100).optional(),utmContent:z.string().trim().max(100).optional()}).parse(request.body);await createPromoterLink(request,input);response.redirect('/promoter');}catch(error){next(error);}});
router.post('/promoter/content-kit', requireAuth, requireVerified, requirePermission('promoter:manage'), async(request,response,next)=>{try{const input=z.object({campaignId:z.string().min(4).max(100),destination:z.string().trim().regex(/^\/[A-Za-z0-9/_?&=.%+-]*$/).max(500),couponCode:z.string().trim().max(32).optional(),subId:z.string().trim().max(80).optional(),channel:z.string().trim().max(50).default(''),utmContent:z.string().trim().max(100).optional()}).parse(request.body);request.session.promoterContentKit=await buildCampaignContentKit(request,input);response.redirect('/promoter#content-kit');}catch(error){next(error);}});

router.post('/promoter/messages/:id/reply', requireAuth, requireVerified, requirePermission('promoter:manage'), async (request,response,next)=>{try{const body=z.string().trim().min(2).max(2000).parse(request.body.message);const thread=await PromoterContactRequest.findOne({publicId:request.params.id,promoterUserId:request.user._id,status:{$ne:'resolved'}});if(!thread)throw new AppError('Conversation not found or already resolved.',404,'CONTACT_NOT_FOUND');thread.replies.push({sender:'promoter',senderUserId:request.user._id,body,at:new Date()});thread.status='read';thread.lastMessageAt=new Date();await thread.save();await writeAudit(request,'promoter_contact.promoter_reply',{targetType:'promoter_contact',targetPublicId:thread.publicId});setFlash(request,'success','Reply sent to the customer.');response.redirect('/promoter#messages');}catch(error){next(error);}});
router.post('/promoter/messages/:id/resolve', requireAuth, requireVerified, requirePermission('promoter:manage'), async (request,response,next)=>{try{const thread=await PromoterContactRequest.findOne({publicId:request.params.id,promoterUserId:request.user._id});if(!thread)throw new AppError('Conversation not found.',404,'CONTACT_NOT_FOUND');thread.status='resolved';thread.resolvedAt=new Date();thread.lastMessageAt=new Date();await thread.save();await writeAudit(request,'promoter_contact.resolved',{targetType:'promoter_contact',targetPublicId:thread.publicId});setFlash(request,'success','Conversation marked resolved.');response.redirect('/promoter#messages');}catch(error){next(error);}});

router.post('/promoter/commissions/:id/appeal', requireAuth, requireVerified, requirePermission('promoter:manage'), async(request,response,next)=>{try{const message=z.string().trim().min(10).max(1200).parse(request.body.message);await appealCommissionReversal(request,request.params.id,message);response.redirect('/promoter');}catch(error){next(error);}});
router.post('/admin/commissions/:id/appeal', requireAuth, requireVerified, adminOnly, async(request,response,next)=>{try{const input=z.object({decision:z.enum(['accept','reject']),reason:z.string().trim().min(10).max(1200)}).parse(request.body);await reviewCommissionAppeal(request,request.params.id,input);response.redirect('/admin/promoters');}catch(error){next(error);}});

router.get('/seller/campaigns', requireAuth, requireVerified, loadSellerStore, requireStoreCapability('growth'), async(request,response,next)=>{try{const store=request.store;const [campaigns,products]=await Promise.all([Campaign.find({storeId:store._id}).sort({createdAt:-1}).limit(100).lean(),Product.find({storeId:store._id,status:'published',countries:store.country}).select('publicId title').sort({title:1}).limit(200).lean()]);const ids=campaigns.map(c=>c._id);const applications=ids.length?await CampaignApplication.find({campaignId:{$in:ids}}).sort({createdAt:-1}).limit(200).lean():[];response.set('Cache-Control','private, no-store').render('seller-campaigns',{campaigns,applications,products,store});}catch(error){next(error);}});
router.post('/seller/campaigns', requireAuth, requireVerified, loadSellerStore, requireStoreCapability('growth'), async(request,response,next)=>{try{await createCampaign(request,campaignForm(request.body));response.redirect('/seller/campaigns');}catch(error){next(error);}});
router.post('/seller/campaigns/:id/submit', requireAuth, requireVerified, loadSellerStore, requireStoreCapability('growth'), async(request,response,next)=>{try{await submitCampaign(request,request.params.id);response.redirect('/seller/campaigns');}catch(error){next(error);}});
router.post('/seller/campaign-applications/:id/review', requireAuth, requireVerified, loadSellerStore, requireStoreCapability('growth'), async(request,response,next)=>{try{await reviewCampaignApplication(request,request.params.id,{decision:z.enum(['approve','reject']).parse(request.body.decision),reason:String(request.body.reason||'').slice(0,500)});response.redirect('/seller/campaigns');}catch(error){next(error);}});

router.post('/admin/promoters/:id/review', requireAuth, requireVerified, adminOnly, async(request,response,next)=>{try{await reviewPromoterVerification(request,request.params.id,{decision:z.enum(['approve','reject']).parse(request.body.decision),reason:String(request.body.reason||'').slice(0,500)});response.redirect('/admin/promoters');}catch(error){next(error);}});
router.post('/admin/campaigns/:id/review', requireAuth, requireVerified, adminOnly, async(request,response,next)=>{try{await reviewCampaign(request,request.params.id,{decision:z.enum(['approve','reject']).parse(request.body.decision),reason:String(request.body.reason||'').slice(0,500)});response.redirect('/admin/promoters');}catch(error){next(error);}});

router.get('/api/v1/promoters/me/summary', requireAuth, requireVerified, requirePermission('promoter:manage'), async (request, response, next) => { try { response.json(await promoterSummary(request.user)); } catch (error) { next(error); } });
router.get('/promoter', requireAuth, requireVerified, requirePermission('promoter:manage'), async (request, response, next) => { try { const [summary,aiJobs] = await Promise.all([promoterSummary(request.user),AiJob.find({actorUserId:request.user._id,type:'promoter_content'}).sort({createdAt:-1}).limit(30).lean()]); const contentKit=request.session.promoterContentKit||null; delete request.session.promoterContentKit; response.set('Cache-Control', 'private, no-store'); response.render('promoter-workspace', { summary, contentKit, aiJobs }); } catch (error) { next(error); } });
router.get('/admin/promoters', requireAuth, requireVerified, adminOnly, async (request, response, next) => { try { const scope = request.user.role === 'super_admin' ? {} : { country: request.user.country }; const campaignIds = await Campaign.find(scope).distinct('_id'); const [verifications, campaigns, touches, commissions, applications] = await Promise.all([PromoterVerification.find(scope).sort({ createdAt: -1 }).limit(100).lean(), Campaign.find(scope).sort({ createdAt: -1 }).limit(100).lean(), AttributionTouch.find(scope).select('-ipHash -userAgentHash -referrerHash').sort({ createdAt: -1 }).limit(100).lean(), CommissionEntry.find({ campaignId: { $in: campaignIds } }).sort({ createdAt: -1 }).limit(100).lean(), CampaignApplication.find({ campaignId: { $in: campaignIds } }).sort({ createdAt: -1 }).limit(100).lean()]); response.render('promoter-admin', { verifications, campaigns, touches, commissions, applications }); } catch (error) { next(error); } });

export default router;
