import { Router } from 'express';
import { z } from 'zod';
import { requireAuth, requireOnboarding, requireVerified } from '../middleware/auth.js';
import { noStore } from '../middleware/request.js';
import { loadSellerStore, requireStoreCapability } from '../middleware/store.js';
import { writeAudit } from '../services/audit.js';
import {
  createSellerPromotion, createStoreBroadcast, decidePurchaseOrder, promotionMarginPreview, queueStoreBroadcast, scheduleVariantPrice,
  sellerGrowthWorkspace, sellerRespondQuote, setSellerPromotionStatus,
} from '../services/seller-growth.js';
const router=Router();
const promotionInputSchema=z.object({type:z.enum(['voucher','bundle','quantity_break','free_shipping','sponsored']),name:z.string().trim().min(2).max(140),code:z.string().trim().max(40).optional().default(''),productPublicIds:z.union([z.string().trim().max(2000),z.array(z.string().trim().min(3).max(100)).max(200)]).optional().default(''),discountBps:z.coerce.number().int().min(0).max(9000).default(0),fixedDiscountMinor:z.coerce.number().int().min(0).default(0),minQuantity:z.coerce.number().int().min(1).max(9999).default(1),minSubtotalMinor:z.coerce.number().int().min(0).default(0),disclosureText:z.string().trim().max(300).optional().default('Sponsored placement.'),startsAt:z.string().optional().default(''),endsAt:z.string().optional().default(''),status:z.enum(['draft','active']).default('draft')});
function promotionInput(body){const input=promotionInputSchema.parse(body);const values=Array.isArray(input.productPublicIds)?input.productPublicIds:input.productPublicIds.split(/[\s,]+/);return{...input,productPublicIds:[...new Set(values.map(String).map(value=>value.trim()).filter(Boolean))],startsAt:input.startsAt||undefined,endsAt:input.endsAt||undefined};}
router.use('/seller/growth',noStore,requireAuth,requireVerified,requireOnboarding,loadSellerStore,requireStoreCapability('growth'));
router.get('/seller/growth',async(req,res,next)=>{try{res.render('seller-growth',{view:await sellerGrowthWorkspace(req)});}catch(e){next(e);}});
router.post('/seller/growth/promotions',async(req,res,next)=>{try{const input=promotionInput(req.body);const row=await createSellerPromotion(req,input);await writeAudit(req,'seller.promotion.created',{targetType:'seller_promotion',targetPublicId:row.publicId});res.redirect('/seller/growth#promotions');}catch(e){next(e);}});
router.post('/seller/growth/promotions/preview',async(req,res,next)=>{try{const input=promotionInput(req.body);const preview=await promotionMarginPreview(req,input);await writeAudit(req,'seller.promotion.previewed',{targetType:'store',targetPublicId:req.store.publicId,metadata:{type:input.type,variants:preview.length}});res.render('seller-growth',{view:{...(await sellerGrowthWorkspace(req)),promotionPreview:preview}});}catch(e){next(e);}});
router.post('/seller/growth/promotions/:id/status',async(req,res,next)=>{try{const status=z.enum(['active','paused','expired']).parse(req.body.status);const row=await setSellerPromotionStatus(req,req.params.id,status);await writeAudit(req,'seller.promotion.status',{targetType:'seller_promotion',targetPublicId:row.publicId,metadata:{status}});res.redirect('/seller/growth#promotions');}catch(e){next(e);}});
router.post('/seller/growth/prices',async(req,res,next)=>{try{const input=z.object({variantId:z.string().min(3).max(100),newPriceMinor:z.coerce.number().int().min(0),minimumPriceMinor:z.coerce.number().int().min(0).default(0),costMinor:z.coerce.number().int().min(0).optional(),startsAt:z.coerce.date()}).parse(req.body);const row=await scheduleVariantPrice(req,input);await writeAudit(req,'seller.price.scheduled',{targetType:'price_schedule',targetPublicId:row.publicId});res.redirect('/seller/growth#pricing');}catch(e){next(e);}});
router.post('/seller/growth/broadcasts',async(req,res,next)=>{try{const input=z.object({subject:z.string().trim().min(2).max(180),body:z.string().trim().min(2).max(4000)}).parse(req.body);const row=await createStoreBroadcast(req,input);await writeAudit(req,'seller.broadcast.created',{targetType:'store_broadcast',targetPublicId:row.publicId});res.redirect('/seller/growth#broadcasts');}catch(e){next(e);}});
router.post('/seller/growth/broadcasts/:id/queue',async(req,res,next)=>{try{const row=await queueStoreBroadcast(req,req.params.id);await writeAudit(req,'seller.broadcast.queued',{targetType:'store_broadcast',targetPublicId:row.publicId,metadata:{recipients:row.recipientCount}});res.redirect('/seller/growth#broadcasts');}catch(e){next(e);}});
router.post('/seller/growth/quotes/:id/respond',async(req,res,next)=>{try{const input=z.object({message:z.string().trim().min(2).max(2000),validUntil:z.string().optional().default('')}).parse(req.body);const offeredUnitMinor=[].concat(req.body.offeredUnitMinor||[]).map(value=>z.coerce.number().int().min(0).parse(value));const row=await sellerRespondQuote(req,req.params.id,{...input,offeredUnitMinor,validUntil:input.validUntil||undefined});await writeAudit(req,'seller.quote.responded',{targetType:'quote_request',targetPublicId:row.publicId});res.redirect('/seller/growth#quotes');}catch(e){next(e);}});

router.post('/seller/growth/purchase-orders/:id/decision',async(req,res,next)=>{try{const status=z.enum(['accepted','rejected']).parse(req.body.status);const row=await decidePurchaseOrder(req,req.params.id,status);await writeAudit(req,`seller.purchase_order.${status}`,{targetType:'purchase_order',targetPublicId:row.publicId});res.redirect('/seller/growth#purchase-orders');}catch(e){next(e);}});

export default router;
