import { Router } from 'express';
import rateLimit from 'express-rate-limit';
import { z } from 'zod';
import { AppError } from '../core/errors.js';
import { decryptSensitive } from '../core/sensitive.js';
import { hasPermission } from '../core/roles.js';
import { requireAuth, requireVerified } from '../middleware/auth.js';
import { verifyDeferredCsrf } from '../middleware/csrf.js';
import {
  Dispute, EvidenceDocument, Order, Product, ReturnRequest, Review, RiskSignal, SatisfactionSurvey, Shipment, Store,
  SupportKnowledge, SupportTicket, TrustCase, User,
} from '../models/index.js';
import { createRefund } from '../services/payments.js';
import { resolveUploadPath, sanitizeAndStoreEvidenceImage, uploadVerificationImage } from '../services/media.js';
import {
  attachEvidence, createDispute, createExchangeReplacement, createKnowledgeArticle, createPublicSupportTicket, createReturnRequest, createTicket,
  createVerifiedReview, decideReturn, disputeReview, inspectReturn, markReturnReceived, publishReview, reportTrustIssue,
  submitSatisfaction, supportRequester, supportScope,
} from '../services/trust.js';
import { sendSupportTicketEmail } from '../services/mail.js';
import { setFlash } from '../middleware/view.js';

const router=Router();
const publicSupportLimit=rateLimit({windowMs:15*60_000,limit:8,standardHeaders:'draft-8',legacyHeaders:false});
const publicTicketSchema=z.object({context:z.enum(['help','contact']).default('help'),name:z.string().trim().min(2).max(120),email:z.string().trim().email().max(254),topic:z.string().trim().min(2).max(100),orderId:z.string().trim().max(100).optional().default(''),message:z.string().trim().min(10).max(3000)});
function publicCategory(topic){const v=String(topic||'').toLowerCase();if(v.includes('order'))return 'order';if(v.includes('return'))return 'return';if(v.includes('payment'))return 'payment';if(v.includes('seller'))return 'seller';if(v.includes('privacy')||v.includes('account'))return 'account';return 'other';}
function publicPriority(topic){const v=String(topic||'').toLowerCase();return v.includes('payment')||v.includes('return')?'high':'normal';}
const returnSchema=z.object({orderId:z.string().min(4).max(100),reason:z.enum(['damaged','wrong_item','not_as_described','counterfeit_suspected','missing_parts','changed_mind','not_received','other']),details:z.string().trim().min(10).max(2000),resolution:z.enum(['refund','exchange']),returnMethod:z.enum(['dropoff','pickup']).default('dropoff'),dropoffPointId:z.string().trim().max(100).optional().default(''),items:z.array(z.object({productId:z.string().min(4).max(100),quantity:z.coerce.number().int().min(1).max(99)})).min(1).max(20)});
const disputeSchema=z.object({orderId:z.string().min(4).max(100),category:z.enum(['payment','delivery','item_missing','wrong_item','damaged','counterfeit','refund','seller_conduct','other']),subject:z.string().trim().min(4).max(180),description:z.string().trim().min(10).max(3000)});
const ticketSchema=z.object({orderId:z.string().trim().max(100).optional(),category:z.enum(['order','payment','delivery','return','refund','account','product','seller','other']),subject:z.string().trim().min(4).max(180),priority:z.enum(['low','normal','high','urgent']).default('normal'),message:z.string().trim().min(10).max(2000)});
const reviewSchema=z.object({orderId:z.string().trim().min(4).max(100).optional(),productId:z.string().min(4).max(100),rating:z.coerce.number().int().min(1).max(5),title:z.string().trim().max(140).optional(),body:z.string().trim().min(10).max(2500)});
const trustSchema=z.object({type:z.enum(['counterfeit','prohibited_product','unsafe_product','review_manipulation','seller_conduct']),productId:z.string().trim().max(100).optional(),storeId:z.string().trim().max(100).optional(),description:z.string().trim().min(10).max(2500)}).refine(v=>v.productId||v.storeId,{message:'A product or store is required.'});
function supportOnly(req,_res,next){if(hasPermission(req.user,'support:manage')||hasPermission(req.user,'trust:manage')||req.user?.role==='super_admin')return next();next(new AppError('Support or trust permission required.',403,'FORBIDDEN'));}
function financeOnly(req,_res,next){if(hasPermission(req.user,'finance:manage')||hasPermission(req.user,'finance:country')||req.user?.role==='super_admin')return next();next(new AppError('Finance permission required.',403,'FORBIDDEN'));}
function upload(middleware){return(req,res,next)=>middleware(req,res,error=>{if(error)return next(error);try{verifyDeferredCsrf(req);return next();}catch(csrfError){return next(csrfError);}});}

router.post('/support/request', publicSupportLimit, async(req,res,next)=>{
  try{
    const raw=publicTicketSchema.parse(req.body);
    const ticket=await createPublicSupportTicket(req,{
      ...raw,
      category:publicCategory(raw.topic),
      priority:publicPriority(raw.topic),
      subject:`${raw.context === 'contact' ? 'Contact' : 'Help'}: ${raw.topic}`,
    });
    await sendSupportTicketEmail({email:raw.email,name:raw.name,ticketId:ticket.publicId,subject:'Classic Mart support request received',message:`We received your request about ${raw.topic}. Our support team will respond through the contact details you provided.`}).catch(error=>req.log?.warn?.({error:error.message,ticketId:ticket.publicId},'Support acknowledgement email failed'));
    setFlash(req,'success',`Support request ${ticket.publicId} received.`,'Your request is in the support queue and is covered by the applicable service-level target.');
    return res.redirect(raw.context === 'contact' ? '/contact' : '/help');
  }catch(error){return next(error);}
});

router.get('/account/returns',requireAuth,requireVerified,async(req,res,next)=>{try{const [orders,returns,disputes,tickets,cases,surveys]=await Promise.all([Order.find({userId:req.user._id}).sort({createdAt:-1}).limit(50).lean(),ReturnRequest.find({userId:req.user._id}).populate('evidenceDocumentIds','publicId description').sort({createdAt:-1}).limit(50).lean(),Dispute.find({userId:req.user._id}).populate('evidenceDocumentIds','publicId description').sort({createdAt:-1}).limit(50).lean(),SupportTicket.find({userId:req.user._id}).populate('evidenceDocumentIds','publicId description').sort({createdAt:-1}).limit(50).lean(),TrustCase.find({reporterUserId:req.user._id}).populate('evidenceDocumentIds','publicId description').sort({createdAt:-1}).limit(50).lean(),SatisfactionSurvey.find({userId:req.user._id}).lean()]);const surveyByTicket=Object.fromEntries(surveys.map(s=>[s.ticketPublicId,s]));const returnPickupCodes={};for(const ret of returns){if(!ret.returnShipmentPublicId)continue;const shipment=await Shipment.findOne({publicId:ret.returnShipmentPublicId,kind:'return'}).select('+pickupCodeEncrypted').lean();if(shipment?.pickupCodeEncrypted&&['ready','offered','assigned'].includes(shipment.status))returnPickupCodes[ret.publicId]={shipmentId:shipment.publicId,pickupCode:decryptSensitive(shipment.pickupCodeEncrypted)};}res.set('Cache-Control','private, no-store').render('returns-workspace',{orders,returns,disputes,tickets,cases,surveys,surveyByTicket,returnPickupCodes});}catch(e){next(e);}});
router.post('/api/v1/returns',requireAuth,requireVerified,async(req,res,next)=>{try{res.status(201).json(await createReturnRequest(req,returnSchema.parse(req.body)));}catch(e){next(e);}});
router.post('/account/returns',requireAuth,requireVerified,async(req,res,next)=>{try{const input=returnSchema.parse({orderId:req.body.orderId,reason:req.body.reason,details:req.body.details,resolution:req.body.resolution,returnMethod:req.body.returnMethod,dropoffPointId:req.body.dropoffPointId,items:[{productId:req.body.productId,quantity:req.body.quantity}]});await createReturnRequest(req,input);res.redirect('/account/returns');}catch(e){next(e);}});
router.post('/account/returns/:id/evidence',requireAuth,requireVerified,upload(uploadVerificationImage),async(req,res,next)=>{try{const ret=await ReturnRequest.findOne({publicId:req.params.id,userId:req.user._id});if(!ret)throw new AppError('Return not found.',404,'RETURN_NOT_FOUND');const evidence=await sanitizeAndStoreEvidenceImage({file:req.file,user:req.user,country:ret.country,contextType:'return',contextPublicId:ret.publicId,description:req.body.description});await attachEvidence(ret,evidence);res.redirect('/account/returns');}catch(e){next(e);}});
router.post('/account/evidence/:contextType/:id',requireAuth,requireVerified,upload(uploadVerificationImage),async(req,res,next)=>{try{const type=String(req.params.contextType||'');let doc=null,contextType='';if(type==='dispute'){doc=await Dispute.findOne({publicId:req.params.id,userId:req.user._id});contextType='dispute';}else if(type==='support'){doc=await SupportTicket.findOne({publicId:req.params.id,userId:req.user._id});contextType='support';}else if(type==='trust_case'){doc=await TrustCase.findOne({publicId:req.params.id,reporterUserId:req.user._id});contextType='trust_case';}else throw new AppError('Evidence context is invalid.',422,'EVIDENCE_CONTEXT_INVALID');if(!doc)throw new AppError('Case not found.',404,'CASE_NOT_FOUND');const evidence=await sanitizeAndStoreEvidenceImage({file:req.file,user:req.user,country:doc.country,contextType,contextPublicId:doc.publicId,description:req.body.description});await attachEvidence(doc,evidence);res.redirect('/account/returns');}catch(e){next(e);}});
router.get('/api/v1/returns/:id/pickup-code',requireAuth,requireVerified,async(req,res,next)=>{try{const ret=await ReturnRequest.findOne({publicId:req.params.id,userId:req.user._id});if(!ret?.returnShipmentPublicId)throw new AppError('Return pickup is not active.',404,'RETURN_PICKUP_NOT_FOUND');const shipment=await Shipment.findOne({publicId:ret.returnShipmentPublicId,kind:'return'}).select('+pickupCodeEncrypted');if(!shipment)throw new AppError('Return pickup is not active.',404,'RETURN_PICKUP_NOT_FOUND');res.set('Cache-Control','private, no-store').json({pickupCode:decryptSensitive(shipment.pickupCodeEncrypted),shipmentId:shipment.publicId});}catch(e){next(e);}});

router.post('/account/disputes',requireAuth,requireVerified,async(req,res,next)=>{try{await createDispute(req,disputeSchema.parse(req.body));res.redirect('/account/returns');}catch(e){next(e);}});
router.post('/account/disputes/:id/appeal',requireAuth,requireVerified,async(req,res,next)=>{try{const message=z.string().trim().min(10).max(1500).parse(req.body.message);const d=await Dispute.findOne({publicId:req.params.id,userId:req.user._id,status:{$in:['resolved','rejected','closed']}});if(!d)throw new AppError('Eligible dispute not found.',404,'DISPUTE_NOT_FOUND');d.status='appealed';d.resolvedAt=undefined;d.events.push({type:'dispute.appealed',message,actorUserId:req.user._id});await d.save();res.redirect('/account/returns');}catch(e){next(e);}});
router.post('/account/support',requireAuth,requireVerified,async(req,res,next)=>{try{await createTicket(req,ticketSchema.parse(req.body));res.redirect('/account/returns');}catch(e){next(e);}});
router.post('/account/support/:id/csat',requireAuth,requireVerified,async(req,res,next)=>{try{const input=z.object({rating:z.coerce.number().int().min(1).max(5),comment:z.string().trim().max(1000).default('')}).parse(req.body);await submitSatisfaction(req,req.params.id,input);res.redirect('/account/returns');}catch(e){next(e);}});
router.post('/account/reviews',requireAuth,requireVerified,async(req,res,next)=>{try{await createVerifiedReview(req,reviewSchema.parse(req.body));res.redirect('/account/returns');}catch(e){next(e);}});
router.post('/account/trust-report',requireAuth,requireVerified,async(req,res,next)=>{try{await reportTrustIssue(req,trustSchema.parse(req.body));res.redirect('/account/returns');}catch(e){next(e);}});
router.post('/account/trust-cases/:id/appeal',requireAuth,requireVerified,async(req,res,next)=>{try{const message=z.string().trim().min(10).max(1500).parse(req.body.message);const c=await TrustCase.findOne({publicId:req.params.id,reporterUserId:req.user._id,status:{$in:['actioned','dismissed','closed']}});if(!c)throw new AppError('Eligible trust case not found.',404,'TRUST_CASE_NOT_FOUND');c.status='appealed';c.decision=`Appeal: ${message}`;c.resolvedAt=undefined;await c.save();res.redirect('/account/returns');}catch(e){next(e);}});
router.post('/api/v1/disputes',requireAuth,requireVerified,async(req,res,next)=>{try{res.status(201).json({dispute:await createDispute(req,disputeSchema.parse(req.body))});}catch(e){next(e);}});
router.post('/api/v1/support/tickets',requireAuth,requireVerified,async(req,res,next)=>{try{res.status(201).json({ticket:await createTicket(req,ticketSchema.parse(req.body))});}catch(e){next(e);}});
router.post('/api/v1/support/tickets/:id/csat',requireAuth,requireVerified,async(req,res,next)=>{try{const input=z.object({rating:z.coerce.number().int().min(1).max(5),comment:z.string().trim().max(1000).default('')}).parse(req.body);res.status(201).json({survey:await submitSatisfaction(req,req.params.id,input)});}catch(e){next(e);}});
router.post('/api/v1/reviews',requireAuth,requireVerified,async(req,res,next)=>{try{res.status(201).json({review:await createVerifiedReview(req,reviewSchema.parse(req.body))});}catch(e){next(e);}});
router.post('/api/v1/trust/reports',requireAuth,requireVerified,async(req,res,next)=>{try{res.status(201).json({case:await reportTrustIssue(req,trustSchema.parse(req.body))});}catch(e){next(e);}});

router.get('/evidence/:id',requireAuth,requireVerified,async(req,res,next)=>{try{const evidence=await EvidenceDocument.findOne({publicId:req.params.id,status:'ready'}).select('+storageKey');if(!evidence)throw new AppError('Evidence not found.',404,'EVIDENCE_NOT_FOUND');const deliveryOperator=evidence.contextType==='delivery_verification'&&['country_admin','super_admin'].includes(req.user.role);const trustOperator=evidence.contextType!=='delivery_verification'&&(hasPermission(req.user,'support:manage')||hasPermission(req.user,'trust:manage')||req.user.role==='super_admin');const canOperate=deliveryOperator||trustOperator;if(!evidence.ownerUserId.equals(req.user._id)&&(!canOperate||(req.user.role!=='super_admin'&&evidence.country!==req.user.country)))throw new AppError('Evidence access denied.',403,'FORBIDDEN');res.set('Cache-Control','private, no-store');res.type('image/webp').sendFile(resolveUploadPath(evidence.storageKey));}catch(e){next(e);}});

router.get('/operations/support',requireAuth,requireVerified,supportOnly,async(req,res,next)=>{try{const scope=supportScope(req.user);const [returns,disputes,tickets,reviews,cases,knowledge,risks,surveys]=await Promise.all([ReturnRequest.find(scope).populate('evidenceDocumentIds','publicId description').sort({createdAt:-1}).limit(100).lean(),Dispute.find(scope).populate('evidenceDocumentIds','publicId description').sort({createdAt:-1}).limit(100).lean(),SupportTicket.find(scope).select('+requesterEmailEncrypted').populate('evidenceDocumentIds','publicId description').sort({priority:-1,slaDueAt:1}).limit(100).lean(),Review.find(scope).sort({createdAt:-1}).limit(100).lean(),TrustCase.find(scope).populate('evidenceDocumentIds','publicId description').sort({createdAt:-1}).limit(100).lean(),SupportKnowledge.find(scope).sort({updatedAt:-1}).limit(100).lean(),RiskSignal.find(scope).sort({severity:-1,createdAt:-1}).limit(100).lean(),SatisfactionSurvey.find().sort({createdAt:-1}).limit(100).lean()]);const ticketRequesters=Object.fromEntries(tickets.map(t=>[t.publicId,supportRequester(t)]));res.set('Cache-Control','private, no-store').render('support-workspace',{returns,disputes,tickets,ticketRequesters,reviews,cases,knowledge,risks,surveys});}catch(e){next(e);}});
router.post('/operations/support/returns/:id/decision',requireAuth,requireVerified,supportOnly,async(req,res,next)=>{try{const input=z.object({decision:z.enum(['approve','reject']),note:z.string().trim().max(1000).optional()}).parse(req.body);await decideReturn(req,req.params.id,input);res.redirect('/operations/support');}catch(e){next(e);}});
router.post('/operations/support/returns/:id/received',requireAuth,requireVerified,supportOnly,async(req,res,next)=>{try{await markReturnReceived(req,req.params.id,String(req.body.note||'').slice(0,1000));res.redirect('/operations/support');}catch(e){next(e);}});
router.post('/operations/support/returns/:id/inspect',requireAuth,requireVerified,supportOnly,async(req,res,next)=>{try{const input=z.object({condition:z.enum(['unopened','good','damaged','wrong_item','counterfeit_suspected','missing_parts','not_received']),notes:z.string().trim().max(1000).optional()}).parse(req.body);await inspectReturn(req,req.params.id,input);res.redirect('/operations/support');}catch(e){next(e);}});
router.post('/api/v1/finance/returns/:id/refund',requireAuth,requireVerified,financeOnly,async(req,res,next)=>{try{const ret=await ReturnRequest.findOne({publicId:req.params.id,...supportScope(req.user)});if(!ret)throw new AppError('Return not found.',404,'RETURN_NOT_FOUND');if(ret.status!=='refund_pending')throw new AppError('Return is not approved and inspected for refund.',409,'RETURN_STATE');const amount=ret.items.reduce((sum,item)=>sum+item.requestedRefundMinor,0);const order=await Order.findById(ret.orderId).lean();const allocations=ret.items.map(item=>{const original=order?.items?.find(row=>row.productPublicId===item.productPublicId&&row.variantPublicId===item.variantPublicId);const storePublicId=item.storePublicId||original?.storePublicId;if(!storePublicId)throw new AppError('Return item seller snapshot is unavailable.',409,'RETURN_SELLER_SNAPSHOT_MISSING');return {storePublicId,productPublicId:item.productPublicId,grossMinor:item.requestedRefundMinor};});const refund=await createRefund(req,{orderId:ret.orderPublicId,amountMinor:amount,reason:`Approved return ${ret.publicId}`,idempotencyKey:`return-refund:${ret.publicId}`,allocations});ret.refundPublicId=refund.publicId;ret.status=refund.status==='completed'?'refunded':'refund_processing';ret.timeline.push({type:'return.refund_started',message:`Refund ${refund.publicId} started by finance.`,actorUserId:req.user._id});await ret.save();res.status(201).json({refund,returnRequest:ret});}catch(e){next(e);}});
router.post('/operations/support/returns/:id/exchange-complete',requireAuth,requireVerified,supportOnly,async(req,res,next)=>{try{await createExchangeReplacement(req,req.params.id);res.redirect('/operations/support');}catch(e){next(e);}});

router.post('/operations/support/reviews/:id/moderate',requireAuth,requireVerified,supportOnly,async(req,res,next)=>{try{const input=z.object({decision:z.enum(['publish','reject']),reason:z.string().trim().max(500).optional()}).parse(req.body);await publishReview(req,req.params.id,input);res.redirect('/operations/support');}catch(e){next(e);}});
router.post('/api/v1/seller/reviews/:id/dispute',requireAuth,requireVerified,async(req,res,next)=>{try{const input=z.object({reason:z.string().trim().min(10).max(1000)}).parse(req.body);res.json({review:await disputeReview(req,req.params.id,input.reason)});}catch(e){next(e);}});
router.post('/operations/support/disputes/:id/status',requireAuth,requireVerified,supportOnly,async(req,res,next)=>{try{const input=z.object({status:z.enum(['investigating','awaiting_customer','awaiting_seller','resolved','rejected','closed']),message:z.string().trim().min(3).max(1000)}).parse(req.body);const d=await Dispute.findOne({publicId:req.params.id,...supportScope(req.user)});if(!d)throw new AppError('Dispute not found.',404,'DISPUTE_NOT_FOUND');d.status=input.status;d.assignedUserId=req.user._id;d.events.push({type:`dispute.${input.status}`,message:input.message,actorUserId:req.user._id});if(['resolved','rejected','closed'].includes(input.status))d.resolvedAt=new Date();await d.save();res.redirect('/operations/support');}catch(e){next(e);}});
router.post('/api/v1/disputes/:id/appeal',requireAuth,requireVerified,async(req,res,next)=>{try{const input=z.object({message:z.string().trim().min(10).max(1500)}).parse(req.body);const d=await Dispute.findOne({publicId:req.params.id,userId:req.user._id,status:{$in:['resolved','rejected','closed']}});if(!d)throw new AppError('Eligible dispute not found.',404,'DISPUTE_NOT_FOUND');d.status='appealed';d.resolvedAt=undefined;d.events.push({type:'dispute.appealed',message:input.message,actorUserId:req.user._id});await d.save();res.json({dispute:d});}catch(e){next(e);}});
router.post('/operations/support/tickets/:id/status',requireAuth,requireVerified,supportOnly,async(req,res,next)=>{try{const input=z.object({status:z.enum(['in_progress','waiting_customer','escalated','resolved','closed']),message:z.string().trim().min(3).max(2000),internal:z.coerce.boolean().optional().default(false)}).parse(req.body);const t=await SupportTicket.findOne({publicId:req.params.id,...supportScope(req.user)}).select('+requesterEmailEncrypted');if(!t)throw new AppError('Ticket not found.',404,'TICKET_NOT_FOUND');t.status=input.status;t.assignedUserId=req.user._id;t.notes.push({message:input.message,actorUserId:req.user._id,internal:input.internal});if(['resolved','closed'].includes(input.status))t.resolvedAt=new Date();await t.save();if(!input.internal){let recipient=supportRequester(t);if(t.userId){const u=await User.findById(t.userId).select('name email').lean();if(u)recipient={name:u.name,email:u.email};}await sendSupportTicketEmail({email:recipient.email,name:recipient.name,ticketId:t.publicId,subject:`Support ticket ${input.status.replaceAll('_',' ')}`,message:input.message}).catch(error=>req.log?.warn?.({error:error.message,ticketId:t.publicId},'Support update email failed'));}res.redirect('/operations/support');}catch(e){next(e);}});
router.post('/operations/support/trust/:id/status',requireAuth,requireVerified,supportOnly,async(req,res,next)=>{try{const input=z.object({status:z.enum(['investigating','actioned','dismissed','closed']),enforcement:z.enum(['none','suspend_product','restore_product','suspend_store','restore_store']).default('none'),decision:z.string().trim().min(3).max(1000)}).parse(req.body);const c=await TrustCase.findOne({publicId:req.params.id,...supportScope(req.user)});if(!c)throw new AppError('Trust case not found.',404,'TRUST_CASE_NOT_FOUND');if(input.status!=='actioned'&&input.enforcement!=='none')throw new AppError('Enforcement requires an actioned trust case.',422,'TRUST_ENFORCEMENT_STATE');if(input.enforcement==='suspend_product'){const product=await Product.findOne({publicId:c.productPublicId});if(!product)throw new AppError('Product not found for enforcement.',404,'PRODUCT_NOT_FOUND');if(product.status!=='suspended'){product.suspension.previousStatus=product.status;product.suspension.reason=input.decision;product.suspension.suspendedAt=new Date();product.suspension.suspendedByUserId=req.user._id;product.status='suspended';await product.save();}}else if(input.enforcement==='restore_product'){const product=await Product.findOne({publicId:c.productPublicId,status:'suspended'});if(!product)throw new AppError('Suspended product not found.',404,'PRODUCT_NOT_FOUND');product.status=['published','approved'].includes(product.suspension?.previousStatus)?product.suspension.previousStatus:'approved';product.suspension.reason='';product.suspension.suspendedAt=undefined;product.suspension.suspendedByUserId=undefined;await product.save();}else if(input.enforcement==='suspend_store'){const store=c.storePublicId?await Store.findOne({publicId:c.storePublicId}):c.productId?await Product.findById(c.productId).then(product=>product?Store.findById(product.storeId):null):null;if(!store)throw new AppError('Store not found for enforcement.',404,'STORE_NOT_FOUND');store.status='suspended';store.suspendedAt=new Date();store.suspensionReason=input.decision;store.suspendedByUserId=req.user._id;await store.save();}else if(input.enforcement==='restore_store'){const store=c.storePublicId?await Store.findOne({publicId:c.storePublicId,status:'suspended'}):c.productId?await Product.findById(c.productId).then(product=>product?Store.findOne({_id:product.storeId,status:'suspended'}):null):null;if(!store)throw new AppError('Suspended store not found.',404,'STORE_NOT_FOUND');store.status='verified';store.suspendedAt=undefined;store.suspensionReason='';store.suspendedByUserId=undefined;await store.save();}c.status=input.status;c.decision=input.decision;c.assignedUserId=req.user._id;if(['actioned','dismissed','closed'].includes(input.status))c.resolvedAt=new Date();await c.save();res.redirect('/operations/support');}catch(e){next(e);}});
router.post('/operations/support/knowledge',requireAuth,requireVerified,supportOnly,async(req,res,next)=>{try{const input=z.object({country:z.string().length(2).optional(),title:z.string().trim().min(4).max(180),slug:z.string().trim().min(3).max(180),body:z.string().trim().min(20).max(12000),category:z.string().trim().min(2).max(80),status:z.enum(['draft','published']).default('draft')}).parse(req.body);if(req.user.role!=='super_admin')input.country=req.user.country;await createKnowledgeArticle(req,input);res.redirect('/operations/support');}catch(e){next(e);}});
router.get('/api/v1/support/knowledge',async(req,res,next)=>{try{const articles=await SupportKnowledge.find({country:req.country.code,status:'published'}).select('publicId title slug body category publishedAt').sort({publishedAt:-1}).limit(100).lean();res.json({articles});}catch(e){next(e);}});
router.post('/operations/support/risks/:id/review',requireAuth,requireVerified,supportOnly,async(req,res,next)=>{try{const input=z.object({status:z.enum(['reviewed','dismissed','actioned']),decision:z.string().trim().min(3).max(1000)}).parse(req.body);const risk=await RiskSignal.findOne({publicId:req.params.id,...supportScope(req.user)});if(!risk)throw new AppError('Risk signal not found.',404,'RISK_NOT_FOUND');risk.status=input.status;risk.decision=input.decision;risk.reviewedByUserId=req.user._id;risk.reviewedAt=new Date();await risk.save();res.redirect('/operations/support');}catch(e){next(e);}});
router.get('/api/v1/reviews/product/:productId',async(req,res,next)=>{try{const reviews=await Review.find({productPublicId:req.params.productId,status:'published',country:req.country.code}).select('publicId rating title body verifiedPurchase publishedAt createdAt').sort({publishedAt:-1}).limit(100).lean();res.set('Cache-Control','public, max-age=30').json({reviews});}catch(e){next(e);}});

export default router;
