import { Router } from 'express';
import mongoose from 'mongoose';
import rateLimit from 'express-rate-limit';
import { z } from 'zod';
import { AppError } from '../core/errors.js';
import { decryptSensitive } from '../core/sensitive.js';
import { hasPermission } from '../core/roles.js';
import { requireAuth, requireVerified } from '../middleware/auth.js';
import { verifyDeferredCsrf } from '../middleware/csrf.js';
import {
  Dispute, EvidenceDocument, Order, PaymentIntent, Product, Refund, ReturnRequest, Review, RiskSignal, SatisfactionSurvey, SellerOrder, SellerReturnCase, Shipment, Store, StoreMember,
  SupportKnowledge, SupportMacro, SupportTicket, SupportTicketPresence, TrustCase, User,
} from '../models/index.js';
import { createRefund } from '../services/payments.js';
import { sanitizeAndStoreEvidenceImage, uploadVerificationImage } from '../services/media.js';
import { sendStoredMedia } from '../services/media-delivery.js';
import {
  attachEvidence, createDispute, createExchangeReplacement, createKnowledgeArticle, createPublicSupportTicket, createReturnRequest, createTicket,
  createVerifiedReview, decideReturn, disputeReview, inspectReturn, markReturnReceived, publishReview, reportTrustIssue,
  submitSatisfaction, supportRequester, supportScope,
} from '../services/trust.js';
import { sendSupportTicketEmail } from '../services/mail.js';
import { setFlash } from '../middleware/view.js';
import { assertOperationalCountry, operationalCountriesFor } from '../services/authorization.js';
import { cursorScope, cursorSort, pageResult } from '../services/pagination.js';
import { writeAudit } from '../services/audit.js';

const router=Router();
const publicSupportLimit=rateLimit({windowMs:15*60_000,limit:8,standardHeaders:'draft-8',legacyHeaders:false});
const publicTicketSchema=z.object({context:z.enum(['help','contact']).default('help'),name:z.string().trim().min(2).max(120),email:z.string().trim().email().max(254),topic:z.string().trim().min(2).max(100),orderId:z.string().trim().max(100).optional().default(''),message:z.string().trim().min(10).max(3000)});
function publicCategory(topic){const v=String(topic||'').toLowerCase();if(v.includes('order'))return 'order';if(v.includes('return'))return 'return';if(v.includes('payment'))return 'payment';if(v.includes('seller'))return 'seller';if(v.includes('privacy')||v.includes('account'))return 'account';return 'other';}
function publicPriority(topic){const v=String(topic||'').toLowerCase();return v.includes('payment')||v.includes('return')?'high':'normal';}
const returnSchema=z.object({orderId:z.string().min(4).max(100),reason:z.enum(['damaged','wrong_item','not_as_described','counterfeit_suspected','missing_parts','changed_mind','other']),details:z.string().trim().min(10).max(2000),resolution:z.enum(['refund','exchange']),returnMethod:z.enum(['dropoff','pickup']).default('dropoff'),dropoffPointId:z.string().trim().max(100).optional().default(''),items:z.array(z.object({orderLineId:z.string().min(4).max(100),quantity:z.coerce.number().int().min(1).max(99)})).min(1).max(20)});
const disputeSchema=z.object({orderId:z.string().min(4).max(100),category:z.enum(['payment','delivery','item_missing','wrong_item','damaged','counterfeit','refund','seller_conduct','other']),subject:z.string().trim().min(4).max(180),description:z.string().trim().min(10).max(3000)});
const ticketSchema=z.object({orderId:z.string().trim().max(100).optional(),category:z.enum(['order','payment','delivery','return','refund','account','product','seller','other']),subject:z.string().trim().min(4).max(180),priority:z.enum(['low','normal','high','urgent']).default('normal'),message:z.string().trim().min(10).max(2000)});
const reviewSchema=z.object({orderId:z.string().trim().min(4).max(100).optional(),productId:z.string().min(4).max(100),rating:z.coerce.number().int().min(1).max(5),title:z.string().trim().max(140).optional(),body:z.string().trim().min(10).max(2500)});
const trustSchema=z.object({type:z.enum(['counterfeit','prohibited_product','unsafe_product','review_manipulation','seller_conduct']),productId:z.string().trim().max(100).optional(),storeId:z.string().trim().max(100).optional(),description:z.string().trim().min(10).max(2500)}).refine(v=>v.productId||v.storeId,{message:'A product or store is required.'});
function canSupportOperations(user){return hasPermission(user,'support:manage')||user?.role==='super_admin';}
function canTrustOperations(user){return hasPermission(user,'trust:manage')||hasPermission(user,'catalogue:moderate')||user?.role==='super_admin';}
function operationsWorkspaceOnly(req,_res,next){if(canSupportOperations(req.user)||canTrustOperations(req.user))return next();next(new AppError('Support or trust permission required.',403,'FORBIDDEN'));}
function supportOnly(req,_res,next){if(canSupportOperations(req.user))return next();next(new AppError('Support permission required.',403,'FORBIDDEN'));}
function trustOnly(req,_res,next){if(canTrustOperations(req.user))return next();next(new AppError('Trust/moderation permission required.',403,'FORBIDDEN'));}
function financeOnly(req,_res,next){if(hasPermission(req.user,'finance:manage')||hasPermission(req.user,'finance:country')||req.user?.role==='super_admin')return next();next(new AppError('Finance permission required.',403,'FORBIDDEN'));}
function upload(middleware){return(req,res,next)=>middleware(req,res,error=>{if(error)return next(error);try{verifyDeferredCsrf(req);return next();}catch(csrfError){return next(csrfError);}});}
function escapeRegex(value){return String(value||'').replace(/[.*+?^${}()|[\]\\]/g,'\\$&');}
function supportSlaHours(priority){return priority==='urgent'?4:priority==='high'?12:48;}

router.post('/support/request', publicSupportLimit, async(req,res,next)=>{
  try{
    const raw=publicTicketSchema.parse(req.body);
    const ticket=await createPublicSupportTicket(req,{
      ...raw,
      category:publicCategory(raw.topic),
      priority:publicPriority(raw.topic),
      subject:`${raw.context === 'contact' ? 'Contact' : 'Help'}: ${raw.topic}`,
    });
    await sendSupportTicketEmail({email:raw.email,name:raw.name,ticketId:ticket.publicId,subject:'Classic Mart support request received',message:`We received your request about ${raw.topic}. Our support team will respond through the contact details you provided.`}).catch(error=>req.log?.warn?.({error:error.message,ticketId:ticket.publicId},'Support acknowledgement email failed'));
    setFlash(req,'success',`Support request ${ticket.publicId} received.`,'Your request is in the support queue and is covered by the applicable service-level target.');
    return res.redirect(raw.context === 'contact' ? '/contact' : '/help');
  }catch(error){return next(error);}
});

router.get('/account/returns',requireAuth,requireVerified,async(req,res,next)=>{try{
  const pageSize=25,base={userId:req.user._id};
  const fetchPage=async(Model,cursor,{populate=[]}={})=>{let q=Model.find(cursorScope(base,cursor)).sort(cursorSort()).limit(pageSize+1);for(const spec of populate)q=q.populate(...spec);const [rows,total]=await Promise.all([q.lean(),Model.countDocuments(base)]);return pageResult(rows,{limit:pageSize,total});};
  const [orderPage,returnPage,disputePage,ticketPage,casePage]=await Promise.all([
    fetchPage(Order,req.query.ordersAfter),
    fetchPage(ReturnRequest,req.query.returnsAfter,{populate:[['evidenceDocumentIds','publicId description']]}),
    fetchPage(Dispute,req.query.disputesAfter,{populate:[['evidenceDocumentIds','publicId description']]}),
    fetchPage(SupportTicket,req.query.ticketsAfter,{populate:[['evidenceDocumentIds','publicId description']]}),
    (async()=>{const caseBase={reporterUserId:req.user._id};let q=TrustCase.find(cursorScope(caseBase,req.query.casesAfter)).populate('evidenceDocumentIds','publicId description').sort(cursorSort()).limit(pageSize+1);const [rows,total]=await Promise.all([q.lean(),TrustCase.countDocuments(caseBase)]);return pageResult(rows,{limit:pageSize,total});})(),
  ]);
  const orders=orderPage.items,returns=returnPage.items,disputes=disputePage.items,tickets=ticketPage.items,cases=casePage.items;
  const surveys=tickets.length?await SatisfactionSurvey.find({userId:req.user._id,ticketPublicId:{$in:tickets.map(t=>t.publicId)}}).lean():[];
  const surveyByTicket=Object.fromEntries(surveys.map(row=>[row.ticketPublicId,row]));
  const returnableLines=[],reviewableLines=[];
  for(const order of orders){if(order.fulfillmentState!=='delivered')continue;for(const item of order.items||[]){const delivered=Number(item.deliveredQuantity||0),remaining=Math.max(0,delivered-Number(item.returnReservedQuantity||0)-Number(item.returnedQuantity||0));if(remaining>0)returnableLines.push({orderPublicId:order.publicId,orderLineId:item.linePublicId,productPublicId:item.productPublicId,title:item.title,variantTitle:item.variantTitle,sku:item.sku,remaining});if(delivered>0)reviewableLines.push({orderPublicId:order.publicId,productPublicId:item.productPublicId,title:item.title,variantTitle:item.variantTitle,sku:item.sku});}}
  const shipmentIds=returns.map(r=>r.returnShipmentPublicId).filter(Boolean),returnPickupCodes={};
  if(shipmentIds.length){const shipments=await Shipment.find({publicId:{$in:shipmentIds},kind:'return',status:{$in:['ready','offered','assigned']}}).select('+pickupCodeEncrypted publicId').lean();const byId=new Map(shipments.map(x=>[x.publicId,x]));for(const ret of returns){const shipment=byId.get(ret.returnShipmentPublicId);if(shipment?.pickupCodeEncrypted)returnPickupCodes[ret.publicId]={shipmentId:shipment.publicId,pickupCode:decryptSensitive(shipment.pickupCodeEncrypted)};}}
  res.set('Cache-Control','private, no-store').render('returns-workspace',{orders,returns,disputes,tickets,cases,surveys,surveyByTicket,returnPickupCodes,returnableLines,reviewableLines,queuePages:{orders:orderPage.page,returns:returnPage.page,disputes:disputePage.page,tickets:ticketPage.page,cases:casePage.page}});
}catch(e){next(e);}});
router.post('/api/v1/returns',requireAuth,requireVerified,async(req,res,next)=>{try{res.status(201).json(await createReturnRequest(req,returnSchema.parse(req.body)));}catch(e){next(e);}});
router.post('/account/returns',requireAuth,requireVerified,async(req,res,next)=>{try{const [orderId,orderLineId]=String(req.body.returnLine||'').split('::');const input=returnSchema.parse({orderId,reason:req.body.reason,details:req.body.details,resolution:req.body.resolution,returnMethod:req.body.returnMethod,dropoffPointId:req.body.dropoffPointId,items:[{orderLineId,quantity:req.body.quantity}]});await createReturnRequest(req,input);res.redirect('/account/returns');}catch(e){next(e);}});
router.post('/account/returns/:id/evidence',requireAuth,requireVerified,upload(uploadVerificationImage),async(req,res,next)=>{try{const ret=await ReturnRequest.findOne({publicId:req.params.id,userId:req.user._id});if(!ret)throw new AppError('Return not found.',404,'RETURN_NOT_FOUND');const evidence=await sanitizeAndStoreEvidenceImage({file:req.file,user:req.user,country:ret.country,contextType:'return',contextPublicId:ret.publicId,description:req.body.description});await attachEvidence(ret,evidence);res.redirect('/account/returns');}catch(e){next(e);}});
router.post('/account/evidence/:contextType/:id',requireAuth,requireVerified,upload(uploadVerificationImage),async(req,res,next)=>{try{const type=String(req.params.contextType||'');let doc=null,contextType='';if(type==='dispute'){doc=await Dispute.findOne({publicId:req.params.id,userId:req.user._id});contextType='dispute';}else if(type==='support'){doc=await SupportTicket.findOne({publicId:req.params.id,userId:req.user._id});contextType='support';}else if(type==='trust_case'){doc=await TrustCase.findOne({publicId:req.params.id,reporterUserId:req.user._id});contextType='trust_case';}else throw new AppError('Evidence context is invalid.',422,'EVIDENCE_CONTEXT_INVALID');if(!doc)throw new AppError('Case not found.',404,'CASE_NOT_FOUND');const evidence=await sanitizeAndStoreEvidenceImage({file:req.file,user:req.user,country:doc.country,contextType,contextPublicId:doc.publicId,description:req.body.description});await attachEvidence(doc,evidence);res.redirect('/account/returns');}catch(e){next(e);}});
router.get('/api/v1/returns/:id/pickup-code',requireAuth,requireVerified,async(req,res,next)=>{try{const ret=await ReturnRequest.findOne({publicId:req.params.id,userId:req.user._id});if(!ret?.returnShipmentPublicId)throw new AppError('Return pickup is not active.',404,'RETURN_PICKUP_NOT_FOUND');const shipment=await Shipment.findOne({publicId:ret.returnShipmentPublicId,kind:'return'}).select('+pickupCodeEncrypted');if(!shipment)throw new AppError('Return pickup is not active.',404,'RETURN_PICKUP_NOT_FOUND');res.set('Cache-Control','private, no-store').json({pickupCode:decryptSensitive(shipment.pickupCodeEncrypted),shipmentId:shipment.publicId});}catch(e){next(e);}});

router.post('/account/disputes',requireAuth,requireVerified,async(req,res,next)=>{try{await createDispute(req,disputeSchema.parse(req.body));res.redirect('/account/returns');}catch(e){next(e);}});
router.post('/account/disputes/:id/appeal',requireAuth,requireVerified,async(req,res,next)=>{try{const message=z.string().trim().min(10).max(1500).parse(req.body.message);const d=await Dispute.findOne({publicId:req.params.id,userId:req.user._id,status:{$in:['resolved','rejected','closed']}});if(!d)throw new AppError('Eligible dispute not found.',404,'DISPUTE_NOT_FOUND');d.status='appealed';d.resolvedAt=undefined;d.events.push({type:'dispute.appealed',message,actorUserId:req.user._id});await d.save();res.redirect('/account/returns');}catch(e){next(e);}});
router.post('/account/support',requireAuth,requireVerified,async(req,res,next)=>{try{await createTicket(req,ticketSchema.parse(req.body));res.redirect('/account/returns');}catch(e){next(e);}});
router.post('/account/support/:id/csat',requireAuth,requireVerified,async(req,res,next)=>{try{const input=z.object({rating:z.coerce.number().int().min(1).max(5),comment:z.string().trim().max(1000).default('')}).parse(req.body);await submitSatisfaction(req,req.params.id,input);res.redirect('/account/returns');}catch(e){next(e);}});
router.post('/account/support/:id/reopen',requireAuth,requireVerified,async(req,res,next)=>{try{const message=z.string().trim().min(3).max(2000).parse(req.body.message||'Customer requested more help.');const t=await SupportTicket.findOne({publicId:req.params.id,userId:req.user._id,status:{$in:['resolved','closed']}});if(!t)throw new AppError('Resolved support ticket not found.',404,'TICKET_NOT_FOUND');if(t.resolvedAt&&Date.now()-t.resolvedAt.getTime()>30*24*60*60*1000)throw new AppError('This ticket has been closed for more than 30 days. Open a new support request instead.',409,'TICKET_REOPEN_WINDOW');const from=t.status;t.status='open';t.resolvedAt=undefined;t.reopenedAt=new Date();t.assignedUserId=undefined;t.assignedAt=undefined;t.slaDueAt=new Date(Date.now()+supportSlaHours(t.priority)*60*60*1000);t.notes.push({message,actorUserId:req.user._id,internal:false});t.workflowHistory.push({action:'reopened',actorUserId:req.user._id,fromStatus:from,toStatus:'open',note:'Customer reopened ticket.'});await t.save();setFlash(req,'success',`Support ticket ${t.publicId} reopened.`);res.redirect('/account/returns');}catch(e){next(e);}});
router.post('/account/reviews',requireAuth,requireVerified,async(req,res,next)=>{try{const [orderId,productId]=String(req.body.reviewLine||'').split('::');await createVerifiedReview(req,reviewSchema.parse({orderId,productId,rating:req.body.rating,title:req.body.title,body:req.body.body}));res.redirect('/account/returns');}catch(e){next(e);}});
router.post('/account/trust-report',requireAuth,requireVerified,async(req,res,next)=>{try{await reportTrustIssue(req,trustSchema.parse(req.body));res.redirect('/account/returns');}catch(e){next(e);}});
router.post('/account/trust-cases/:id/appeal',requireAuth,requireVerified,async(req,res,next)=>{try{const message=z.string().trim().min(10).max(1500).parse(req.body.message);const c=await TrustCase.findOne({publicId:req.params.id,reporterUserId:req.user._id,status:{$in:['actioned','dismissed','closed']}});if(!c)throw new AppError('Eligible trust case not found.',404,'TRUST_CASE_NOT_FOUND');c.status='appealed';c.decision=`Appeal: ${message}`;c.resolvedAt=undefined;await c.save();res.redirect('/account/returns');}catch(e){next(e);}});
router.post('/api/v1/disputes',requireAuth,requireVerified,async(req,res,next)=>{try{res.status(201).json({dispute:await createDispute(req,disputeSchema.parse(req.body))});}catch(e){next(e);}});
router.post('/api/v1/support/tickets',requireAuth,requireVerified,async(req,res,next)=>{try{res.status(201).json({ticket:await createTicket(req,ticketSchema.parse(req.body))});}catch(e){next(e);}});
router.post('/api/v1/support/tickets/:id/csat',requireAuth,requireVerified,async(req,res,next)=>{try{const input=z.object({rating:z.coerce.number().int().min(1).max(5),comment:z.string().trim().max(1000).default('')}).parse(req.body);res.status(201).json({survey:await submitSatisfaction(req,req.params.id,input)});}catch(e){next(e);}});
router.post('/api/v1/reviews',requireAuth,requireVerified,async(req,res,next)=>{try{res.status(201).json({review:await createVerifiedReview(req,reviewSchema.parse(req.body))});}catch(e){next(e);}});
router.post('/api/v1/trust/reports',requireAuth,requireVerified,async(req,res,next)=>{try{res.status(201).json({case:await reportTrustIssue(req,trustSchema.parse(req.body))});}catch(e){next(e);}});

router.get('/evidence/:id',requireAuth,requireVerified,async(req,res,next)=>{try{const evidence=await EvidenceDocument.findOne({publicId:req.params.id,status:'ready'}).select('+storageKey');if(!evidence)throw new AppError('Evidence not found.',404,'EVIDENCE_NOT_FOUND');const deliveryOperator=['delivery_verification','delivery_job'].includes(evidence.contextType)&&['country_admin','super_admin','support','finance'].includes(req.user.role);const supportOperator=['return','seller_return','dispute','support'].includes(evidence.contextType)&&canSupportOperations(req.user);const trustOperator=evidence.contextType==='trust_case'&&canTrustOperations(req.user);let sellerOperator=false;if(evidence.contextType==='seller_return'){const sellerCase=await SellerReturnCase.findOne({publicId:evidence.contextPublicId}).select('storeId').lean();if(sellerCase){const store=await Store.findById(sellerCase.storeId).select('ownerUserId').lean();sellerOperator=String(store?.ownerUserId||'')===String(req.user._id)||Boolean(await StoreMember.exists({storeId:sellerCase.storeId,userId:req.user._id,status:'active',role:{$in:['owner','admin','support']}}));}}const canOperate=deliveryOperator||supportOperator||trustOperator||sellerOperator;if(deliveryOperator||supportOperator||trustOperator)assertOperationalCountry(req.user,evidence.country);if(!evidence.ownerUserId.equals(req.user._id)&&!canOperate)throw new AppError('Evidence access denied.',403,'FORBIDDEN');await sendStoredMedia(res,evidence.storageKey,{cacheControl:'private, no-store',contentType:'image/webp',contentDisposition:'inline'});}catch(e){next(e);}});

router.get('/operations/support',requireAuth,requireVerified,operationsWorkspaceOnly,async(req,res,next)=>{try{
  const scope=supportScope(req.user),canSupport=canSupportOperations(req.user),canTrust=canTrustOperations(req.user),pageSize=50;
  const emptyRows=Promise.resolve([]),zero=Promise.resolve(0);
  const ticketFilters={search:String(req.query.ticketSearch||'').trim().slice(0,80),status:String(req.query.ticketStatus||''),priority:String(req.query.ticketPriority||''),category:String(req.query.ticketCategory||''),queue:String(req.query.ticketQueue||''),assignment:String(req.query.ticketAssignment||''),overdue:String(req.query.ticketOverdue||'')==='1'};
  const ticketClauses=[scope];
  if(['open','in_progress','waiting_customer','escalated','resolved','closed'].includes(ticketFilters.status))ticketClauses.push({status:ticketFilters.status});
  if(['low','normal','high','urgent'].includes(ticketFilters.priority))ticketClauses.push({priority:ticketFilters.priority});
  if(['order','payment','delivery','return','refund','account','product','seller','other'].includes(ticketFilters.category))ticketClauses.push({category:ticketFilters.category});
  if(['general','orders','payments','delivery','returns','accounts','seller'].includes(ticketFilters.queue))ticketClauses.push({queue:ticketFilters.queue});
  if(ticketFilters.assignment==='mine')ticketClauses.push({assignedUserId:req.user._id});else if(ticketFilters.assignment==='unassigned')ticketClauses.push({$or:[{assignedUserId:null},{assignedUserId:{$exists:false}}]});
  if(ticketFilters.overdue)ticketClauses.push({status:{$nin:['resolved','closed']},slaDueAt:{$lt:new Date()}});
  if(ticketFilters.search){const pattern=new RegExp(escapeRegex(ticketFilters.search),'i');ticketClauses.push({$or:[{publicId:pattern},{subject:pattern},{orderPublicId:pattern},{requesterName:pattern}]});}
  const ticketScope=ticketClauses.length===1?scope:{$and:ticketClauses};
  const queueConfig={
    returns:{model:ReturnRequest,field:'createdAt',direction:-1,cursor:req.query.returnsAfter},
    disputes:{model:Dispute,field:'createdAt',direction:-1,cursor:req.query.disputesAfter},
    tickets:{model:SupportTicket,field:'slaDueAt',direction:1,cursor:req.query.ticketsAfter},
    reviews:{model:Review,field:'createdAt',direction:-1,cursor:req.query.reviewsAfter},
    cases:{model:TrustCase,field:'createdAt',direction:-1,cursor:req.query.casesAfter},
    knowledge:{model:SupportKnowledge,field:'updatedAt',direction:-1,cursor:req.query.knowledgeAfter},
    risks:{model:RiskSignal,field:'createdAt',direction:-1,cursor:req.query.risksAfter},
    surveys:{model:SatisfactionSurvey,field:'createdAt',direction:-1,cursor:req.query.surveysAfter},
  };
  const supportEnabled=new Set(['returns','disputes','tickets','knowledge','surveys']);
  const trustEnabled=new Set(['reviews','cases','risks']);
  const enabled=name=>(canSupport&&supportEnabled.has(name))||(canTrust&&trustEnabled.has(name));
  const queryFor=(name)=>{const c=queueConfig[name],base=name==='tickets'?ticketScope:scope;return enabled(name)?c.model.find(cursorScope(base,c.cursor,{field:c.field,direction:c.direction})).sort(cursorSort(c.field,c.direction)).limit(pageSize+1):null;};
  let rq=queryFor('returns');if(rq)rq=rq.populate('evidenceDocumentIds','publicId description');
  let dq=queryFor('disputes');if(dq)dq=dq.populate('evidenceDocumentIds','publicId description');
  let tq=queryFor('tickets');if(tq)tq=tq.select('+requesterEmailEncrypted').populate('evidenceDocumentIds','publicId description').populate('assignedUserId','name email');
  let cq=queryFor('cases');if(cq)cq=cq.populate('evidenceDocumentIds','publicId description');
  const [returnRows,disputeRows,ticketRows,reviewRows,caseRows,knowledgeRows,riskRows,surveyRows,returnTotal,disputeTotal,ticketTotal,reviewTotal,caseTotal,knowledgeTotal,riskTotal,surveyTotal]=await Promise.all([
    rq?rq.lean():emptyRows,dq?dq.lean():emptyRows,tq?tq.lean():emptyRows,queryFor('reviews')?.lean()||emptyRows,cq?cq.lean():emptyRows,queryFor('knowledge')?.lean()||emptyRows,queryFor('risks')?.lean()||emptyRows,queryFor('surveys')?.lean()||emptyRows,
    enabled('returns')?ReturnRequest.countDocuments(scope):zero,enabled('disputes')?Dispute.countDocuments(scope):zero,enabled('tickets')?SupportTicket.countDocuments(ticketScope):zero,enabled('reviews')?Review.countDocuments(scope):zero,enabled('cases')?TrustCase.countDocuments(scope):zero,enabled('knowledge')?SupportKnowledge.countDocuments(scope):zero,enabled('risks')?RiskSignal.countDocuments(scope):zero,enabled('surveys')?SatisfactionSurvey.countDocuments(scope):zero,
  ]);
  const pages={
    returns:pageResult(returnRows,{field:'createdAt',limit:pageSize,total:returnTotal}),
    disputes:pageResult(disputeRows,{field:'createdAt',limit:pageSize,total:disputeTotal}),
    tickets:pageResult(ticketRows,{field:'slaDueAt',direction:1,limit:pageSize,total:ticketTotal}),
    reviews:pageResult(reviewRows,{field:'createdAt',limit:pageSize,total:reviewTotal}),
    cases:pageResult(caseRows,{field:'createdAt',limit:pageSize,total:caseTotal}),
    knowledge:pageResult(knowledgeRows,{field:'updatedAt',limit:pageSize,total:knowledgeTotal}),
    risks:pageResult(riskRows,{field:'createdAt',limit:pageSize,total:riskTotal}),
    surveys:pageResult(surveyRows,{field:'createdAt',limit:pageSize,total:surveyTotal}),
  };
  const returns=pages.returns.items,disputes=pages.disputes.items,tickets=pages.tickets.items,reviews=pages.reviews.items,cases=pages.cases.items,knowledge=pages.knowledge.items,risks=pages.risks.items,surveys=pages.surveys.items;
  const macroBase=canSupport?{...scope,active:true}:{_id:{$in:[]}};const [macroRows,macroTotal]=canSupport?await Promise.all([SupportMacro.find(cursorScope(macroBase,req.query.macrosAfter,{field:'updatedAt'})).sort(cursorSort('updatedAt')).limit(pageSize+1).lean(),SupportMacro.countDocuments(macroBase)]):[[],0];const macroPage=pageResult(macroRows,{field:'updatedAt',limit:pageSize,total:macroTotal});
  const sellerReturnCases=returns.length?await SellerReturnCase.find({...scope,returnPublicId:{$in:returns.map(r=>r.publicId)}}).populate('evidenceDocumentIds','publicId description createdAt').populate('respondedByUserId','name email').sort({createdAt:-1}).lean():[];
  const ticketRequesters=Object.fromEntries(tickets.map(t=>[t.publicId,supportRequester(t)]));
  const sellerCasesByReturn={};for(const row of sellerReturnCases){(sellerCasesByReturn[row.returnPublicId]??=[]).push(row);}
  res.set('Cache-Control','private, no-store').render('support-workspace',{returns,disputes,tickets,ticketRequesters,reviews,cases,knowledge,risks,surveys,macros:macroPage.items,ticketFilters,sellerCasesByReturn,canSupport,canTrust,queuePages:{...Object.fromEntries(Object.entries(pages).map(([name,value])=>[name,value.page])),macros:macroPage.page}});
}catch(e){next(e);}});
router.post('/operations/support/returns/:id/decision',requireAuth,requireVerified,supportOnly,async(req,res,next)=>{try{const input=z.object({decision:z.enum(['approve','reject']),note:z.string().trim().max(1000).optional()}).parse(req.body);await decideReturn(req,req.params.id,input);res.redirect('/operations/support');}catch(e){next(e);}});
router.post('/operations/support/returns/:id/received',requireAuth,requireVerified,supportOnly,async(req,res,next)=>{try{await markReturnReceived(req,req.params.id,String(req.body.note||'').slice(0,1000));res.redirect('/operations/support');}catch(e){next(e);}});
router.post('/operations/support/returns/:id/inspect',requireAuth,requireVerified,supportOnly,async(req,res,next)=>{try{const input=z.object({condition:z.enum(['unopened','good','damaged','wrong_item','counterfeit_suspected','missing_parts']),notes:z.string().trim().max(1000).optional()}).parse(req.body);await inspectReturn(req,req.params.id,input);res.redirect('/operations/support');}catch(e){next(e);}});
router.post('/api/v1/finance/returns/:id/refund',requireAuth,requireVerified,financeOnly,async(req,res,next)=>{try{const ret=await ReturnRequest.findOne({publicId:req.params.id,...supportScope(req.user)});if(!ret)throw new AppError('Return not found.',404,'RETURN_NOT_FOUND');if(ret.status!=='refund_pending')throw new AppError('Return is not approved and inspected for refund.',409,'RETURN_STATE');const amount=ret.items.reduce((sum,item)=>sum+item.requestedRefundMinor,0);const order=await Order.findById(ret.orderId).lean();const allocations=ret.items.map(item=>{const original=order?.items?.find(row=>String(row.linePublicId||row._id)===String(item.orderLineId));const storePublicId=item.storePublicId||original?.storePublicId;if(!storePublicId)throw new AppError('Return item seller snapshot is unavailable.',409,'RETURN_SELLER_SNAPSHOT_MISSING');return {storePublicId,productPublicId:item.productPublicId,orderLineId:item.orderLineId,grossMinor:item.requestedRefundMinor};});const refund=await createRefund(req,{orderId:ret.orderPublicId,amountMinor:amount,reason:`Approved return ${ret.publicId}`,idempotencyKey:`return-refund:${ret.publicId}`,allocations});ret.refundPublicId=refund.publicId;ret.status=refund.status==='completed'?'refunded':'refund_processing';ret.timeline.push({type:'return.refund_started',message:`Refund ${refund.publicId} started by finance.`,actorUserId:req.user._id});await ret.save();res.status(201).json({refund,returnRequest:ret});}catch(e){next(e);}});
router.post('/operations/support/returns/:id/exchange-complete',requireAuth,requireVerified,supportOnly,async(req,res,next)=>{try{await createExchangeReplacement(req,req.params.id);res.redirect('/operations/support');}catch(e){next(e);}});

router.post('/operations/support/reviews/:id/moderate',requireAuth,requireVerified,trustOnly,async(req,res,next)=>{try{const input=z.object({decision:z.enum(['publish','reject']),reason:z.string().trim().max(500).optional()}).parse(req.body);await publishReview(req,req.params.id,input);res.redirect('/operations/support');}catch(e){next(e);}});
router.post('/api/v1/seller/reviews/:id/dispute',requireAuth,requireVerified,async(req,res,next)=>{try{const input=z.object({reason:z.string().trim().min(10).max(1000)}).parse(req.body);res.json({review:await disputeReview(req,req.params.id,input.reason)});}catch(e){next(e);}});
router.post('/operations/support/disputes/:id/status',requireAuth,requireVerified,supportOnly,async(req,res,next)=>{try{const input=z.object({status:z.enum(['investigating','awaiting_customer','awaiting_seller','resolved','rejected','closed']),message:z.string().trim().min(3).max(1000)}).parse(req.body);const d=await Dispute.findOne({publicId:req.params.id,...supportScope(req.user)});if(!d)throw new AppError('Dispute not found.',404,'DISPUTE_NOT_FOUND');d.status=input.status;d.assignedUserId=req.user._id;d.events.push({type:`dispute.${input.status}`,message:input.message,actorUserId:req.user._id});if(['resolved','rejected','closed'].includes(input.status))d.resolvedAt=new Date();await d.save();res.redirect('/operations/support');}catch(e){next(e);}});
router.post('/api/v1/disputes/:id/appeal',requireAuth,requireVerified,async(req,res,next)=>{try{const input=z.object({message:z.string().trim().min(10).max(1500)}).parse(req.body);const d=await Dispute.findOne({publicId:req.params.id,userId:req.user._id,status:{$in:['resolved','rejected','closed']}});if(!d)throw new AppError('Eligible dispute not found.',404,'DISPUTE_NOT_FOUND');d.status='appealed';d.resolvedAt=undefined;d.events.push({type:'dispute.appealed',message:input.message,actorUserId:req.user._id});await d.save();res.json({dispute:d});}catch(e){next(e);}});
router.get('/operations/support/tickets/:id',requireAuth,requireVerified,supportOnly,async(req,res,next)=>{try{
  const ticket=await SupportTicket.findOne({publicId:req.params.id,...supportScope(req.user)}).select('+requesterEmailEncrypted').populate('evidenceDocumentIds','publicId description createdAt').populate('assignedUserId','name publicId role').populate('notes.actorUserId','name publicId role').populate('assignmentHistory.actorUserId','name publicId role').populate('assignmentHistory.assignedUserId','name publicId role').populate('workflowHistory.actorUserId','name publicId role');
  if(!ticket)throw new AppError('Support ticket not found.',404,'TICKET_NOT_FOUND');
  const now=new Date(),expiresAt=new Date(now.getTime()+90_000);await SupportTicketPresence.findOneAndUpdate({ticketId:ticket._id,userId:req.user._id},{$set:{country:ticket.country,expiresAt}},{upsert:true,setDefaultsOnInsert:true});
  const transferSearch=String(req.query.transferQ||'').trim().slice(0,120);
  const transferBase={status:'active',role:{$in:['support','country_admin','super_admin']},$or:[{role:'super_admin'},{country:ticket.country},{operationalCountries:ticket.country},{operationalCountries:'*'}]};
  if(transferSearch){const re=new RegExp(escapeRegex(transferSearch),'i');transferBase.$and=[{$or:[{name:re},{email:re},{publicId:re}]}];}
  const [presence,order,shipments,payments,refunds,sellerOrders,macros,transferCandidates]=await Promise.all([
    SupportTicketPresence.find({ticketId:ticket._id,userId:{$ne:req.user._id},expiresAt:{$gt:now}}).populate('userId','name publicId role').lean(),
    ticket.orderId?Order.findById(ticket.orderId).select('publicId paymentState fulfillmentState cancellationState returnState refundState totals contact createdAt').lean():null,
    ticket.orderId?Shipment.find({orderId:ticket.orderId}).select('publicId kind status mode deliveredAt failedReason updatedAt').sort({createdAt:-1}).lean():[],
    ticket.orderId?PaymentIntent.find({orderId:ticket.orderId}).select('publicId provider status amountMinor currency createdAt paidAt').sort({createdAt:-1}).lean():[],
    ticket.orderId?Refund.find({orderId:ticket.orderId}).select('publicId status amountMinor currency reason createdAt completedAt').sort({createdAt:-1}).lean():[],
    ticket.orderId?SellerOrder.find({orderId:ticket.orderId}).select('publicId storePublicId status fulfillmentStatus currency totalMinor updatedAt').lean():[],
    SupportMacro.find({country:ticket.country,active:true,$or:[{category:''},{category:ticket.category}]}).sort({title:1}).lean(),
    User.find(transferBase).select('+operationalCountries name email publicId role country').sort({name:1,_id:1}).limit(51).lean(),
  ]);
  const authorizedCandidates=transferCandidates.filter(candidate=>canSupportOperations(candidate)&&operationalCountriesFor(candidate).some(code=>code==='*'||code===ticket.country));
  const transferHasMore=authorizedCandidates.length>50,candidates=authorizedCandidates.slice(0,50);
  res.set('Cache-Control','private, no-store').render('support-ticket',{ticket,requester:supportRequester(ticket),presence,order,shipments,payments,refunds,sellerOrders,macros,transferCandidates:candidates,transferSearch,transferHasMore});
}catch(e){next(e);}});
router.post('/operations/support/tickets/:id/presence',requireAuth,requireVerified,supportOnly,async(req,res,next)=>{try{const ticket=await SupportTicket.findOne({publicId:req.params.id,...supportScope(req.user)}).select('_id country').lean();if(!ticket)throw new AppError('Support ticket not found.',404,'TICKET_NOT_FOUND');await SupportTicketPresence.findOneAndUpdate({ticketId:ticket._id,userId:req.user._id},{$set:{country:ticket.country,expiresAt:new Date(Date.now()+90_000)}},{upsert:true,setDefaultsOnInsert:true});res.status(204).end();}catch(e){next(e);}});
router.post('/operations/support/tickets/:id/transfer',requireAuth,requireVerified,supportOnly,async(req,res,next)=>{try{const input=z.object({userPublicId:z.string().trim().min(4).max(120)}).parse(req.body);const t=await SupportTicket.findOne({publicId:req.params.id,...supportScope(req.user),status:{$nin:['resolved','closed']}});if(!t)throw new AppError('Active support ticket not found.',404,'TICKET_NOT_FOUND');const supervisor=['country_admin','super_admin'].includes(req.user.role);if(!t.assignedUserId)throw new AppError('Claim the ticket before transferring it.',409,'TICKET_CLAIM_REQUIRED');if(!t.assignedUserId.equals(req.user._id)&&!supervisor)throw new AppError('Only the assigned operator or supervisor can transfer this ticket.',409,'TICKET_TRANSFER_FORBIDDEN');const target=await User.findOne({publicId:input.userPublicId,status:'active'}).select('+operationalCountries');if(!target||!canSupportOperations(target)||!operationalCountriesFor(target).some(code=>code==='*'||code===t.country))throw new AppError('Target support operator is not authorized for this ticket country.',422,'TICKET_TRANSFER_TARGET_INVALID');if(t.assignedUserId.equals(target._id))throw new AppError('Ticket is already assigned to that operator.',409,'TICKET_TRANSFER_SAME');const now=new Date();t.assignedUserId=target._id;t.assignedAt=now;t.assignmentHistory.push({action:'transfer',actorUserId:req.user._id,assignedUserId:target._id,at:now});if(t.status==='open')t.status='in_progress';await t.save();await writeAudit(req,'support.ticket_transferred',{targetType:'support_ticket',targetPublicId:t.publicId,country:t.country,metadata:{toUserPublicId:target.publicId}});setFlash(req,'success',`Ticket transferred to ${target.name}.`);res.redirect(`/operations/support/tickets/${encodeURIComponent(t.publicId)}`);}catch(e){next(e);}});
router.post('/operations/support/tickets/:id/reopen',requireAuth,requireVerified,supportOnly,async(req,res,next)=>{try{const t=await SupportTicket.findOne({publicId:req.params.id,...supportScope(req.user),status:{$in:['resolved','closed']}});if(!t)throw new AppError('Resolved support ticket not found.',404,'TICKET_NOT_FOUND');const from=t.status;t.status='open';t.resolvedAt=undefined;t.reopenedAt=new Date();t.assignedUserId=req.user._id;t.assignedAt=t.reopenedAt;t.slaDueAt=new Date(Date.now()+supportSlaHours(t.priority)*60*60*1000);t.assignmentHistory.push({action:'claim',actorUserId:req.user._id,assignedUserId:req.user._id,at:t.reopenedAt});t.workflowHistory.push({action:'reopened',actorUserId:req.user._id,fromStatus:from,toStatus:'open',note:'Support operator reopened ticket.'});await t.save();await writeAudit(req,'support.ticket_reopened',{targetType:'support_ticket',targetPublicId:t.publicId,country:t.country});res.redirect(`/operations/support/tickets/${encodeURIComponent(t.publicId)}`);}catch(e){next(e);}});
router.post('/operations/support/tickets/:id/merge',requireAuth,requireVerified,supportOnly,async(req,res,next)=>{try{if(!['country_admin','super_admin'].includes(req.user.role))throw new AppError('Supervisor permission is required to merge support tickets.',403,'TICKET_MERGE_FORBIDDEN');const targetPublicId=z.string().trim().min(4).max(120).parse(req.body.targetPublicId);if(targetPublicId===req.params.id)throw new AppError('A ticket cannot be merged into itself.',422,'TICKET_MERGE_SELF');const session=await mongoose.startSession();let target;try{await session.withTransaction(async()=>{const source=await SupportTicket.findOne({publicId:req.params.id,...supportScope(req.user),status:{$nin:['resolved','closed']}}).session(session);if(!source)throw new AppError('Active source ticket not found.',404,'TICKET_NOT_FOUND');target=await SupportTicket.findOne({publicId:targetPublicId,country:source.country,status:{$nin:['resolved','closed']}}).session(session);if(!target)throw new AppError('Active merge target not found in the same country.',404,'TICKET_MERGE_TARGET_NOT_FOUND');const now=new Date(),sourceStatus=source.status;source.status='closed';source.resolvedAt=now;source.mergedIntoPublicId=target.publicId;source.mergedAt=now;source.mergedByUserId=req.user._id;source.assignedUserId=undefined;source.assignedAt=undefined;source.notes.push({message:`Merged into ${target.publicId}. Continue work on the target ticket.`,actorUserId:req.user._id,internal:true});source.workflowHistory.push({action:'merged',actorUserId:req.user._id,fromStatus:sourceStatus,toStatus:'closed',targetTicketPublicId:target.publicId,note:'Supervisor merged duplicate ticket.'});target.mergedTicketPublicIds.addToSet(source.publicId);target.notes.push({message:`Duplicate ticket ${source.publicId} was merged into this ticket.`,actorUserId:req.user._id,internal:true});target.workflowHistory.push({action:'merge_received',actorUserId:req.user._id,targetTicketPublicId:source.publicId,note:'Duplicate ticket merged here.'});await source.save({session});await target.save({session});});}finally{await session.endSession();}await writeAudit(req,'support.ticket_merged',{targetType:'support_ticket',targetPublicId:req.params.id,country:target.country,metadata:{mergedInto:target.publicId}});setFlash(req,'success',`Ticket merged into ${target.publicId}.`);res.redirect(`/operations/support/tickets/${encodeURIComponent(target.publicId)}`);}catch(e){next(e);}});
router.post('/operations/support/macros',requireAuth,requireVerified,supportOnly,async(req,res,next)=>{try{const input=z.object({country:z.string().trim().length(2),title:z.string().trim().min(2).max(120),body:z.string().trim().min(3).max(4000),category:z.enum(['','order','payment','delivery','return','refund','account','product','seller','other']).default('')}).parse(req.body);const country=input.country.toUpperCase();if(req.user.role!=='super_admin')assertOperationalCountry(req.user,country);const macro=await SupportMacro.create({publicId:publicId('mac'),country,title:input.title,body:input.body,category:input.category,createdByUserId:req.user._id,updatedByUserId:req.user._id});await writeAudit(req,'support.macro_created',{targetType:'support_macro',targetPublicId:macro.publicId,country});setFlash(req,'success','Saved reply macro created.');res.redirect('/operations/support');}catch(e){next(e);}});
router.post('/operations/support/macros/:id/archive',requireAuth,requireVerified,supportOnly,async(req,res,next)=>{try{const macro=await SupportMacro.findOne({publicId:req.params.id,...supportScope(req.user),active:true});if(!macro)throw new AppError('Support macro not found.',404,'SUPPORT_MACRO_NOT_FOUND');macro.active=false;macro.updatedByUserId=req.user._id;await macro.save();await writeAudit(req,'support.macro_archived',{targetType:'support_macro',targetPublicId:macro.publicId,country:macro.country});res.redirect('/operations/support');}catch(e){next(e);}});
router.post('/operations/support/tickets/:id/macro',requireAuth,requireVerified,supportOnly,async(req,res,next)=>{try{const input=z.object({macroPublicId:z.string().trim().min(4).max(120),status:z.enum(['in_progress','waiting_customer','escalated','resolved']).default('in_progress'),internal:z.coerce.boolean().optional().default(false)}).parse(req.body);const t=await SupportTicket.findOne({publicId:req.params.id,...supportScope(req.user)}).select('+requesterEmailEncrypted');if(!t)throw new AppError('Support ticket not found.',404,'TICKET_NOT_FOUND');const supervisor=['country_admin','super_admin'].includes(req.user.role);if(!t.assignedUserId||(!t.assignedUserId.equals(req.user._id)&&!supervisor))throw new AppError('Claim the ticket before using a saved reply.',409,'TICKET_CLAIM_REQUIRED');const macro=await SupportMacro.findOne({publicId:input.macroPublicId,country:t.country,active:true,$or:[{category:''},{category:t.category}]});if(!macro)throw new AppError('Saved reply is not available for this ticket.',404,'SUPPORT_MACRO_NOT_FOUND');const from=t.status;t.status=input.status;t.notes.push({message:macro.body,actorUserId:req.user._id,internal:input.internal});t.workflowHistory.push({action:'status',actorUserId:req.user._id,fromStatus:from,toStatus:input.status,note:`Applied macro ${macro.publicId}.`});if(input.status==='resolved')t.resolvedAt=new Date();await t.save();if(!input.internal){let recipient=supportRequester(t);if(t.userId){const u=await User.findById(t.userId).select('name email').lean();if(u)recipient={name:u.name,email:u.email};}await sendSupportTicketEmail({email:recipient.email,name:recipient.name,ticketId:t.publicId,subject:`Support ticket ${input.status.replaceAll('_',' ')}`,message:macro.body}).catch(error=>req.log?.warn?.({error:error.message,ticketId:t.publicId},'Support macro email failed'));}res.redirect(`/operations/support/tickets/${encodeURIComponent(t.publicId)}`);}catch(e){next(e);}});
router.post('/operations/support/tickets/:id/claim',requireAuth,requireVerified,supportOnly,async(req,res,next)=>{try{
  const scope=supportScope(req.user);const now=new Date();
  const ticket=await SupportTicket.findOneAndUpdate({publicId:req.params.id,...scope,status:{$nin:['resolved','closed']},$or:[{assignedUserId:null},{assignedUserId:{$exists:false}},{assignedUserId:req.user._id}]},{$set:{assignedUserId:req.user._id,assignedAt:now},$push:{assignmentHistory:{action:'claim',actorUserId:req.user._id,assignedUserId:req.user._id,at:now}}},{returnDocument:'after'});
  if(!ticket){const exists=await SupportTicket.exists({publicId:req.params.id,...scope});if(!exists)throw new AppError('Ticket not found.',404,'TICKET_NOT_FOUND');throw new AppError('This ticket is already claimed by another support operator.',409,'TICKET_ALREADY_CLAIMED');}
  res.redirect('/operations/support');
}catch(e){next(e);}});
router.post('/operations/support/tickets/:id/release',requireAuth,requireVerified,supportOnly,async(req,res,next)=>{try{
  const scope=supportScope(req.user),supervisor=['country_admin','super_admin'].includes(req.user.role);const query={publicId:req.params.id,...scope,status:{$nin:['resolved','closed']}};if(!supervisor)query.assignedUserId=req.user._id;
  const now=new Date(),ticket=await SupportTicket.findOneAndUpdate(query,{$set:{assignedUserId:null,assignedAt:null},$push:{assignmentHistory:{action:'release',actorUserId:req.user._id,at:now}}},{returnDocument:'after'});
  if(!ticket)throw new AppError('Only the assigned operator or a supervisor can release this ticket.',409,'TICKET_RELEASE_FORBIDDEN');res.redirect('/operations/support');
}catch(e){next(e);}});
router.post('/operations/support/tickets/:id/status',requireAuth,requireVerified,supportOnly,async(req,res,next)=>{try{
  const input=z.object({status:z.enum(['in_progress','waiting_customer','escalated','resolved','closed']),message:z.string().trim().min(3).max(2000),internal:z.coerce.boolean().optional().default(false)}).parse(req.body);
  const t=await SupportTicket.findOne({publicId:req.params.id,...supportScope(req.user)}).select('+requesterEmailEncrypted');if(!t)throw new AppError('Ticket not found.',404,'TICKET_NOT_FOUND');
  const supervisor=['country_admin','super_admin'].includes(req.user.role);if(!t.assignedUserId)throw new AppError('Claim the ticket before updating it.',409,'TICKET_CLAIM_REQUIRED');if(!t.assignedUserId.equals(req.user._id)&&!supervisor)throw new AppError('This ticket is assigned to another support operator.',409,'TICKET_ASSIGNED_OTHER');
  const fromStatus=t.status;t.status=input.status;t.notes.push({message:input.message,actorUserId:req.user._id,internal:input.internal});t.workflowHistory.push({action:'status',actorUserId:req.user._id,fromStatus,toStatus:input.status,note:input.internal?'Internal status update':'Customer-facing status update'});if(['resolved','closed'].includes(input.status))t.resolvedAt=new Date();else t.resolvedAt=undefined;await t.save();
  if(!input.internal){let recipient=supportRequester(t);if(t.userId){const u=await User.findById(t.userId).select('name email').lean();if(u)recipient={name:u.name,email:u.email};}await sendSupportTicketEmail({email:recipient.email,name:recipient.name,ticketId:t.publicId,subject:`Support ticket ${input.status.replaceAll('_',' ')}`,message:input.message}).catch(error=>req.log?.warn?.({error:error.message,ticketId:t.publicId},'Support update email failed'));}
  res.redirect('/operations/support');
}catch(e){next(e);}});
router.post('/operations/support/trust/:id/status',requireAuth,requireVerified,trustOnly,async(req,res,next)=>{try{const input=z.object({status:z.enum(['investigating','actioned','dismissed','closed']),enforcement:z.enum(['none','suspend_product','restore_product','suspend_store','restore_store']).default('none'),decision:z.string().trim().min(3).max(1000)}).parse(req.body);const c=await TrustCase.findOne({publicId:req.params.id,...supportScope(req.user)});if(!c)throw new AppError('Trust case not found.',404,'TRUST_CASE_NOT_FOUND');if(input.status!=='actioned'&&input.enforcement!=='none')throw new AppError('Enforcement requires an actioned trust case.',422,'TRUST_ENFORCEMENT_STATE');if(input.enforcement==='suspend_product'){const product=await Product.findOne({publicId:c.productPublicId});if(!product)throw new AppError('Product not found for enforcement.',404,'PRODUCT_NOT_FOUND');if(product.status!=='suspended'){product.suspension.previousStatus=product.status;product.suspension.reason=input.decision;product.suspension.suspendedAt=new Date();product.suspension.suspendedByUserId=req.user._id;product.status='suspended';await product.save();}}else if(input.enforcement==='restore_product'){const product=await Product.findOne({publicId:c.productPublicId,status:'suspended'});if(!product)throw new AppError('Suspended product not found.',404,'PRODUCT_NOT_FOUND');product.status=['published','approved'].includes(product.suspension?.previousStatus)?product.suspension.previousStatus:'approved';product.suspension.reason='';product.suspension.suspendedAt=undefined;product.suspension.suspendedByUserId=undefined;await product.save();}else if(input.enforcement==='suspend_store'){const store=c.storePublicId?await Store.findOne({publicId:c.storePublicId}):c.productId?await Product.findById(c.productId).then(product=>product?Store.findById(product.storeId):null):null;if(!store)throw new AppError('Store not found for enforcement.',404,'STORE_NOT_FOUND');store.status='suspended';store.suspendedAt=new Date();store.suspensionReason=input.decision;store.suspendedByUserId=req.user._id;await store.save();}else if(input.enforcement==='restore_store'){const store=c.storePublicId?await Store.findOne({publicId:c.storePublicId,status:'suspended'}):c.productId?await Product.findById(c.productId).then(product=>product?Store.findOne({_id:product.storeId,status:'suspended'}):null):null;if(!store)throw new AppError('Suspended store not found.',404,'STORE_NOT_FOUND');store.status='verified';store.suspendedAt=undefined;store.suspensionReason='';store.suspendedByUserId=undefined;await store.save();}c.status=input.status;c.decision=input.decision;c.assignedUserId=req.user._id;if(['actioned','dismissed','closed'].includes(input.status))c.resolvedAt=new Date();await c.save();res.redirect('/operations/support');}catch(e){next(e);}});
router.post('/operations/support/knowledge',requireAuth,requireVerified,supportOnly,async(req,res,next)=>{try{const input=z.object({country:z.string().trim().length(2).optional(),title:z.string().trim().min(4).max(180),slug:z.string().trim().min(3).max(180),body:z.string().trim().min(20).max(12000),category:z.string().trim().min(2).max(80),status:z.enum(['draft','published']).default('draft')}).parse(req.body);const grants=operationalCountriesFor(req.user);const country=String(input.country||(!grants.includes('*')&&grants.length===1?grants[0]:'')).toUpperCase();if(!country)throw new AppError('Choose a country for this knowledge article.',422,'COUNTRY_REQUIRED');if(req.user.role!=='super_admin')assertOperationalCountry(req.user,country);await createKnowledgeArticle(req,{...input,country});res.redirect('/operations/support');}catch(e){next(e);}});
router.get('/api/v1/support/knowledge',async(req,res,next)=>{try{const limit=Math.max(1,Math.min(100,Number(req.query.limit)||50)),base={country:req.country.code,status:'published'};const [rows,total]=await Promise.all([SupportKnowledge.find(cursorScope(base,req.query.after,{field:'publishedAt'})).select('publicId title slug body category publishedAt').sort(cursorSort('publishedAt')).limit(limit+1).lean(),SupportKnowledge.countDocuments(base)]);const page=pageResult(rows,{field:'publishedAt',limit,total});res.json({articles:page.items,page:page.page});}catch(e){next(e);}});
router.post('/operations/support/risks/:id/review',requireAuth,requireVerified,trustOnly,async(req,res,next)=>{try{const input=z.object({status:z.enum(['reviewed','dismissed','actioned']),decision:z.string().trim().min(3).max(1000)}).parse(req.body);const risk=await RiskSignal.findOne({publicId:req.params.id,...supportScope(req.user)});if(!risk)throw new AppError('Risk signal not found.',404,'RISK_NOT_FOUND');risk.status=input.status;risk.decision=input.decision;risk.reviewedByUserId=req.user._id;risk.reviewedAt=new Date();await risk.save();res.redirect('/operations/support');}catch(e){next(e);}});
router.get('/api/v1/reviews/product/:productId',async(req,res,next)=>{try{const limit=Math.max(1,Math.min(100,Number(req.query.limit)||50)),base={productPublicId:req.params.productId,status:'published',country:req.country.code};const [rows,total]=await Promise.all([Review.find(cursorScope(base,req.query.after,{field:'publishedAt'})).select('publicId rating title body verifiedPurchase publishedAt createdAt').sort(cursorSort('publishedAt')).limit(limit+1).lean(),Review.countDocuments(base)]);const page=pageResult(rows,{field:'publishedAt',limit,total});res.set('Cache-Control','public, max-age=30').json({reviews:page.items,page:page.page});}catch(e){next(e);}});

export default router;
