import crypto from 'node:crypto';
import fs from 'node:fs/promises';
import mongoose from 'mongoose';
import sharp from 'sharp';
import { z } from 'zod';
import { env } from '../config/env.js';
import { AppError } from '../core/errors.js';
import { publicId } from '../core/ids.js';
import { evaluationRunProvenance } from '../core/ai-evaluation.js';
import {
  AiCartDraft,AiEmbedding,AiEvaluationCase,AiEvaluationRun,AiFeedback,AiJob,AiPromptVersion,AiUsage,
  Cart,Category,CmsContent,CustomerCatalogueState,Order,Product,ProductMedia,ProductVariant,Review,SearchEvent,StockItem,Store,SupportTicket,Campaign,CampaignApplication,PromoterVerification,CountrySetting,
} from '../models/index.js';
import { addCartItem } from './checkout.js';
import { readMediaObjectBuffer } from './object-storage.js';
import { publishedProduct,publishedProductsByPublicIds,searchStorefront } from './storefront.js';
import { configuredModel,cosineSimilarity,createEmbedding,detectPromptInjection,generateJson,moderateInput,providerConfigured } from './ai-provider.js';
import { sendSupportTicketEmail } from './mail.js';
import { supportRequester } from './trust.js';
import { assertOperationalCountry } from './authorization.js';
import { scanMaintenanceBatch } from './maintenance-scan.js';

const askSchema=z.object({answer:z.string().max(5000),productIds:z.array(z.string().max(120)).max(12).default([]),cartDraft:z.array(z.object({productId:z.string().max(120),variantId:z.string().max(120).optional().default(''),quantity:z.coerce.number().int().min(1).max(20).default(1)})).max(12).default([]),handoffRecommended:z.boolean().default(false),warnings:z.array(z.string().max(300)).max(8).default([])});
const productDraftSchema=z.object({title:z.string().min(3).max(180),description:z.string().min(20).max(5000),categorySlug:z.string().max(120),tags:z.array(z.string().max(40)).max(20).default([]),attributes:z.record(z.string(),z.string().max(500)).default({}),warnings:z.array(z.string().max(300)).max(12).default([])});
const translationSchema=z.object({title:z.string().min(3).max(180),description:z.string().min(20).max(5000),tags:z.array(z.string().max(40)).max(20).default([]),warnings:z.array(z.string().max(300)).max(12).default([])});
const sellerAssistantSchema=z.object({answer:z.string().max(5000),suggestedChanges:z.array(z.object({field:z.enum(['title','description','tags','attributes']),reason:z.string().max(500),value:z.any()})).max(20).default([]),warnings:z.array(z.string().max(300)).max(12).default([])});
const supportAssistantSchema=z.object({summary:z.string().max(3000),classification:z.enum(['order','payment','delivery','return','refund','account','product','seller','other']),suggestedReply:z.string().min(10).max(4000),escalationRecommended:z.boolean().default(false),warnings:z.array(z.string().max(300)).max(12).default([])});
const reviewSummarySchema=z.object({summary:z.string().max(2500),positives:z.array(z.string().max(300)).max(8).default([]),cautions:z.array(z.string().max(300)).max(8).default([]),reviewCount:z.number().int().min(0).default(0)});
const adminTriageSchema=z.object({summary:z.string().max(3000),riskLevel:z.enum(['low','medium','high','critical']),evidenceNeeded:z.array(z.string().max(300)).max(12).default([]),suggestedNextSteps:z.array(z.string().max(300)).max(12).default([]),warnings:z.array(z.string().max(300)).max(12).default([])});
const forecastSchema=z.object({summary:z.string().max(3000),confidence:z.enum(['low','medium','high']),assumptions:z.array(z.string().max(300)).max(12),demand:z.array(z.object({productId:z.string(),direction:z.enum(['down','stable','up']),reason:z.string().max(500)})).max(50)});
const promoterContentSchema=z.object({caption:z.string().min(10).max(2200),script:z.string().min(10).max(4000),disclosure:z.string().min(5).max(300),hashtags:z.array(z.string().max(80)).max(12).default([]),warnings:z.array(z.string().max(300)).max(12).default([])});

const schemaHints={
 ask:'{"answer":string,"productIds":string[],"cartDraft":[{"productId":string,"variantId":string,"quantity":integer}],"handoffRecommended":boolean,"warnings":string[]}',
 product_draft:'{"title":string,"description":string,"categorySlug":string,"tags":string[],"attributes":object,"warnings":string[]}',
 category_attributes:'Same as product_draft; focus on categorySlug, attributes and warnings.',translation:'{"title":string,"description":string,"tags":string[],"warnings":string[]}',
 seller_assistant:'{"answer":string,"suggestedChanges":[{"field":"title|description|tags|attributes","reason":string,"value":any}],"warnings":string[]}',
 support_assistant:'{"summary":string,"classification":"order|payment|delivery|return|refund|account|product|seller|other","suggestedReply":string,"escalationRecommended":boolean,"warnings":string[]}',
 review_summary:'{"summary":string,"positives":string[],"cautions":string[],"reviewCount":integer}',
 admin_triage:'{"summary":string,"riskLevel":"low|medium|high|critical","evidenceNeeded":string[],"suggestedNextSteps":string[],"warnings":string[]}',
 promoter_content:'{"caption":string,"script":string,"disclosure":string,"hashtags":string[],"warnings":string[]}',
 demand_forecast:'{"summary":string,"confidence":"low|medium|high","assumptions":string[],"demand":[{"productId":string,"direction":"down|stable|up","reason":string}]}'
};
function hash(value){return crypto.createHash('sha256').update(String(value||'')).digest('hex');}
function sessionHash(request){return hash(request.session?.cartKey||request.sessionID||request.ip||'anonymous');}
function today(){const d=new Date();return new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate()));}
function cleanObject(value){return JSON.parse(JSON.stringify(value||{}));}
function productText(product,category,brand){return [product.title,product.description,category?.name||'',brand?.name||'',...(product.tags||[]),...Object.entries(product.attributes instanceof Map?Object.fromEntries(product.attributes):product.attributes||{}).flat()].join(' ').slice(0,12000);}
function sourceHash(text){return hash(text);}

export async function assertAiQuota({user,sessionKeyHash,country,estimatedMicros=0}){
  const start=today();const budget=await AiUsage.aggregate([{$match:{createdAt:{$gte:start}}},{$group:{_id:null,cost:{$sum:'$estimatedCostMicros'}}}]);
  if(Number(budget[0]?.cost||0)+estimatedMicros>env.ai.dailyBudgetMicros)throw new AppError('Classic AI daily cost budget has been reached. Try again later.',429,'AI_BUDGET_EXCEEDED');
  const actorQuery=user?{actorUserId:user._id}:{sessionKeyHash};const count=await AiUsage.countDocuments({...actorQuery,createdAt:{$gte:start}});if(count>=env.ai.perUserDailyRequests)throw new AppError('Classic AI daily request quota has been reached.',429,'AI_QUOTA_EXCEEDED');
  if(country&&user?.role==='country_admin')assertOperationalCountry(user,country,'AI request is outside your country scope.');
}
export async function recordAiUsage(data){return AiUsage.create({publicId:publicId('aiu'),feature:data.feature,country:data.country,actorUserId:data.actorUserId,sessionKeyHash:data.sessionKeyHash||'',provider:data.provider||'local',model:data.model||'local',promptKey:data.promptKey||'',promptVersion:data.promptVersion||0,inputClassifications:data.inputClassifications||[],inputChars:data.inputChars||0,outputChars:data.outputChars||0,inputTokens:data.inputTokens||0,outputTokens:data.outputTokens||0,estimatedCostMicros:data.estimatedCostMicros||0,latencyMs:data.latencyMs||0,outcome:data.outcome||'success',moderationFlagged:Boolean(data.moderationFlagged),toolNames:data.toolNames||[],errorCode:data.errorCode||''});}
async function activePrompt(key,country=''){
  return AiPromptVersion.findOne({key,status:'active',$or:[{country},{country:''}]}).sort({country:-1,version:-1}).lean();
}
async function safeGenerate({feature,promptKey,input,schema,country,user,sessionKeyHash,tools=[]}){
  await assertAiQuota({user,sessionKeyHash,country});const started=Date.now();const moderation=await moderateInput(input,{country,role:user?.role||'customer'});
  if(moderation.flagged){const usage=await recordAiUsage({feature,country,actorUserId:user?._id,sessionKeyHash,provider:moderation.provider,model:moderation.model,inputClassifications:moderation.categories,inputChars:String(input).length,latencyMs:Date.now()-started,outcome:'blocked',moderationFlagged:true,toolNames:tools,errorCode:'AI_INPUT_BLOCKED'});throw new AppError('Classic AI cannot process that request. Remove instructions asking it to bypass rules, expose secrets, or perform restricted actions.',422,'AI_INPUT_BLOCKED',{usageId:usage.publicId});}
  const prompt=await activePrompt(promptKey,country);if(!prompt)throw new AppError('Classic AI prompt configuration is unavailable.',503,'AI_PROMPT_UNAVAILABLE');
  try{const generated=await generateJson({instructions:prompt.instructions,input,schemaHint:schemaHints[prompt.schemaKey]||'valid JSON',country,role:user?.role||'customer'});const value=schema.parse(generated.value);const usage=await recordAiUsage({feature,country,actorUserId:user?._id,sessionKeyHash,provider:generated.provider,model:generated.model,promptKey:prompt.key,promptVersion:prompt.version,inputChars:String(input).length,outputChars:JSON.stringify(value).length,inputTokens:generated.inputTokens,outputTokens:generated.outputTokens,estimatedCostMicros:generated.estimatedCostMicros,latencyMs:generated.latencyMs,outcome:'success',toolNames:tools});return {value,usage,prompt,generated};}
  catch(error){await recordAiUsage({feature,country,actorUserId:user?._id,sessionKeyHash,provider:env.ai.provider||'disabled',model:env.ai.chatModel||'',promptKey:prompt.key,promptVersion:prompt.version,inputChars:String(input).length,latencyMs:Date.now()-started,outcome:'failed',toolNames:tools,errorCode:error.code||'AI_FAILED'}).catch(()=>{});throw error;}
}

async function embeddingTargets(countries,role='seller'){
  const targets=[];
  for(const country of [...new Set((countries||[]).map(value=>String(value||'').trim().toUpperCase()).filter(Boolean))]){
    const configured=await configuredModel('embedding',{country,role});
    const model=providerConfigured(configured)?configured:{...configured,provider:'local',model:'local-hash-v1'};
    targets.push({country,model,modelKey:`${model.provider}:${model.model}`});
  }
  return targets;
}
export async function ensureProductEmbedding(product){
  const category=await Category.findById(product.categoryId).lean();const text=productText(product,category,null);const sh=sourceHash(text);const targets=await embeddingTargets(product.countries,'seller');
  if(!targets.length)throw new AppError('Published product has no selling country for embedding.',409,'PRODUCT_COUNTRY_REQUIRED');
  const groups=new Map();for(const target of targets){if(!groups.has(target.modelKey))groups.set(target.modelKey,{model:target.model,countries:[]});groups.get(target.modelKey).countries.push(target.country);}
  const results=[];
  for(const [modelKey,group] of groups){const embedded=await createEmbedding(text,{country:group.countries[0],role:'seller',model:group.model});for(const country of group.countries){await AiEmbedding.findOneAndUpdate({entityType:'product',entityPublicId:product.publicId,country,modelKey},{$set:{dimensions:embedded.vector.length,vector:embedded.vector,sourceHash:sh,sourceUpdatedAt:product.updatedAt||new Date()},$setOnInsert:{publicId:publicId('aie')}},{upsert:true,runValidators:true});}results.push({modelKey,dimensions:embedded.vector.length,provider:embedded.provider,model:embedded.model,fallback:embedded.fallback,countries:group.countries});}
  return {...results[0],models:results};
}
export async function queueStaleProductEmbeddings({limit=25}={}){
  const scan=await scanMaintenanceBatch(Product,'published_product_embeddings',{status:'published'},{limit});let queued=0;
  for(const product of scan.rows){const targets=await embeddingTargets(product.countries,'seller');if(!targets.length)continue;const category=await Category.findById(product.categoryId).lean();const sh=sourceHash(productText(product,category,null));const current=await AiEmbedding.countDocuments({entityType:'product',entityPublicId:product.publicId,sourceHash:sh,$or:targets.map(target=>({country:target.country,modelKey:target.modelKey}))});const pending=await AiJob.exists({type:'embedding',productId:product._id,status:{$in:['queued','running']}});if(current<targets.length&&!pending){await AiJob.create({publicId:publicId('aij'),type:'embedding',status:'queued',country:targets[0].country,productId:product._id,input:{productPublicId:product.publicId}});queued++;}}
  return {queued,checked:scan.rows.length,passCompleted:scan.passCompleted};
}
async function currentEmbeddingModelKey(country){const model=await configuredModel('embedding',{country,role:'customer'});if(model.provider==='local'||!providerConfigured(model))return 'local:local-hash-v1';return `${model.provider}:${model.model}`;}
export async function hybridSearch(country,{query='',category='',brand='',seller='',limit=24}={}){
  const lexical=await searchStorefront(country,{query,category,brand,seller});const clean=String(query||'').trim();if(!clean)return {...lexical,searchMode:'lexical'};
  const embedded=await createEmbedding(clean,{country:country.code,role:'customer'});const modelKey=`${embedded.provider}:${embedded.model}`;const rows=await AiEmbedding.find({country:country.code,modelKey}).select('+vector entityPublicId').limit(1000).lean();
  const semantic=rows.map(r=>({id:r.entityPublicId,score:cosineSimilarity(embedded.vector,r.vector)})).filter(r=>Number.isFinite(r.score)&&r.score>0.05).sort((a,b)=>b.score-a.score).slice(0,80);
  const semanticProducts=await publishedProductsByPublicIds(semantic.map(r=>r.id),country);const lexicalRank=new Map(lexical.products.map((p,i)=>[p.id,1-i/Math.max(1,lexical.products.length)]));const semanticRank=new Map(semantic.map(r=>[r.id,Math.max(0,r.score)]));
  const merged=new Map();for(const p of [...lexical.products,...semanticProducts]){if(!p||p.stock<=0)continue;if(category&&p.category!==category)continue;if(brand&&p.brandSlug!==brand)continue;if(seller&&p.seller?.slug!==seller)continue;const score=0.62*(lexicalRank.get(p.id)||0)+0.38*(semanticRank.get(p.id)||0);const prior=merged.get(p.id);if(!prior||score>prior._aiScore)merged.set(p.id,{...p,_aiScore:score,_aiExplanation:semanticRank.has(p.id)&&!lexicalRank.has(p.id)?'Semantically similar to your search':'Matches your search and catalogue signals'});}
  const products=[...merged.values()].sort((a,b)=>b._aiScore-a._aiScore).slice(0,Math.min(80,limit)).map(({_aiScore,...p})=>p);
  await recordAiUsage({feature:'semantic_search',country:country.code,sessionKeyHash:'system-search',provider:embedded.provider,model:embedded.model,inputChars:clean.length,inputTokens:embedded.inputTokens,estimatedCostMicros:embedded.estimatedCostMicros,outcome:embedded.fallback?'fallback':'success',toolNames:['catalogue_search']}).catch(()=>{});
  return {...lexical,products,totalResults:Math.max(lexical.totalResults,products.length),searchMode:embedded.fallback?'hybrid_local':'hybrid_ai'};
}
export async function similarProducts(country,productPublicId,{limit=8}={}){
  const product=await publishedProduct(productPublicId,country);if(!product)return[];const modelKey=await currentEmbeddingModelKey(country.code);let source=await AiEmbedding.findOne({entityType:'product',entityPublicId:productPublicId,country:country.code,modelKey}).select('+vector').lean();
  if(!source){const mongo=await Product.findOne({publicId:productPublicId,status:'published',countries:country.code});if(mongo){await ensureProductEmbedding(mongo);source=await AiEmbedding.findOne({entityType:'product',entityPublicId:productPublicId,country:country.code,modelKey}).select('+vector').lean();}}
  if(!source)return[];const rows=await AiEmbedding.find({country:country.code,modelKey,entityPublicId:{$ne:productPublicId}}).select('+vector entityPublicId').limit(1000).lean();const ranked=rows.map(r=>({id:r.entityPublicId,score:cosineSimilarity(source.vector,r.vector)})).sort((a,b)=>b.score-a.score).slice(0,limit*3);const hydrated=await publishedProductsByPublicIds(ranked.map(r=>r.id),country);const scores=new Map(ranked.map(r=>[r.id,r.score]));return hydrated.filter(p=>p.stock>0).sort((a,b)=>(scores.get(b.id)||0)-(scores.get(a.id)||0)).slice(0,limit).map(p=>({...p,recommendationExplanation:'Similar catalogue meaning and attributes'}));
}
export async function recommendationsFor(request,{limit=12}={}){
  const catalogue=await searchStorefront(request.country,{});const available=catalogue.products.filter(p=>p.stock>0);if(!request.user)return available.sort((a,b)=>(b.sold+b.rating)-(a.sold+a.rating)).slice(0,limit).map(p=>({...p,recommendationExplanation:'Popular and available in your country'}));
  const state=await CustomerCatalogueState.findOne({userId:request.user._id}).lean();const recentIds=(state?.recentProducts||[]).slice(-8).map(r=>r.productId);const recents=recentIds.length?await Product.find({_id:{$in:recentIds}}).lean():[];const categories=new Set(recents.map(p=>String(p.categoryId)));const ranked=available.map(p=>{let score=p.rating*2+Math.log1p(p.sold||0);const mongo=recents.find(r=>r.publicId===p.id);if(mongo)score-=10;return {p,score};});if(categories.size){const map=await Product.find({publicId:{$in:available.map(p=>p.id)}}).select('publicId categoryId').lean();const catById=new Map(map.map(x=>[x.publicId,String(x.categoryId)]));for(const row of ranked)if(categories.has(catById.get(row.p.id)))row.score+=5;}
  return ranked.sort((a,b)=>b.score-a.score).slice(0,limit).map(({p})=>({...p,recommendationExplanation:'Based on your recent catalogue activity, availability and product quality'}));
}

async function groundedPolicies(country){const docs=await CmsContent.find({status:'published',$or:[{country:country.code},{country:''}],type:{$in:['help','legal']}}).limit(20).lean();return docs.map(d=>{const r=d.revisions?.find(x=>x.version===d.activeVersion)||d.revisions?.at(-1);return {key:d.key,title:r?.title||'',body:String(r?.body||'').slice(0,1200)};});}
export async function askClassic(request,message){
  const clean=String(message||'').trim().slice(0,2000);if(clean.length<2)throw new AppError('Ask a question first.',422,'AI_QUESTION_REQUIRED');const injection=detectPromptInjection(clean);if(injection.flagged){const usage=await recordAiUsage({feature:'ask_classic',country:request.country.code,actorUserId:request.user?._id,sessionKeyHash:sessionHash(request),provider:'local',model:'local-policy-v1',inputClassifications:['prompt_injection'],inputChars:clean.length,outcome:'blocked',moderationFlagged:true,errorCode:'AI_INPUT_BLOCKED'});throw new AppError('Classic AI cannot follow instructions to bypass platform rules or expose protected information.',422,'AI_INPUT_BLOCKED',{usageId:usage.publicId});}
  const [products,policies,recommendations]=await Promise.all([hybridSearch(request.country,{query:clean,limit:10}),groundedPolicies(request.country),recommendationsFor(request,{limit:6})]);
  const context={question:clean,country:request.country.code,products:products.products.slice(0,10).map(p=>({id:p.id,name:p.name,description:p.description.slice(0,500),price:p.price,currency:p.currency,stock:p.stock,category:p.categoryName,brand:p.brand,seller:p.seller?.name,variantId:p.variantId,rating:p.rating})),policies,recommendations:recommendations.slice(0,6).map(p=>({id:p.id,name:p.name,price:p.price,currency:p.currency,stock:p.stock,variantId:p.variantId}))};
  let answer,usage,mode='ai';try{const generated=await safeGenerate({feature:'ask_classic',promptKey:'ask_classic.v1',input:JSON.stringify(context),schema:askSchema,country:request.country.code,user:request.user,sessionKeyHash:sessionHash(request),tools:['catalogue_search','policy_lookup','recommendations','cart_draft']});answer=generated.value;usage=generated.usage;}catch(error){if(error.code!=='AI_PROVIDER_UNAVAILABLE')throw error;mode='retrieval_fallback';const top=products.products.slice(0,5);answer={answer:top.length?`I found ${top.length} available product${top.length===1?'':'s'} that match your request. I am showing only server-verified catalogue facts because the generative AI provider is not configured.`:'I could not find an available product matching that request. You can refine the product, brand, category or budget.',productIds:top.map(p=>p.id),cartDraft:[],handoffRecommended:false,warnings:['Generative AI is not configured; this answer uses catalogue retrieval only.']};usage=await recordAiUsage({feature:'ask_classic',country:request.country.code,actorUserId:request.user?._id,sessionKeyHash:sessionHash(request),provider:'local',model:'retrieval-fallback-v1',inputChars:clean.length,outputChars:answer.answer.length,outcome:'fallback',toolNames:['catalogue_search','policy_lookup','recommendations']});}
  const allowedIds=new Set(context.products.map(p=>p.id));answer.productIds=answer.productIds.filter(id=>allowedIds.has(id));const productById=new Map(context.products.map(p=>[p.id,p]));const draftItems=[];for(const item of answer.cartDraft){const p=productById.get(item.productId);if(!p||p.stock<item.quantity)continue;draftItems.push({productPublicId:p.id,variantPublicId:item.variantId&&p.variantId===item.variantId?item.variantId:p.variantId,quantity:item.quantity});}
  let cartDraft=null;if(draftItems.length){cartDraft=await AiCartDraft.create({publicId:publicId('aid'),sessionKey:request.session.cartKey||request.sessionID,userId:request.user?._id,country:request.country.code,items:draftItems,status:'proposed',expiresAt:new Date(Date.now()+20*60_000)});}
  const cited=await publishedProductsByPublicIds(answer.productIds,request.country);return {answer:answer.answer,products:cited,cartDraft:cartDraft?{id:cartDraft.publicId,items:draftItems}:null,handoffRecommended:answer.handoffRecommended,warnings:answer.warnings,usageId:usage.publicId,mode,aiGenerated:mode==='ai'};
}
export async function applyCartDraft(request,draftPublicId){const draft=await AiCartDraft.findOne({publicId:draftPublicId,status:'proposed',country:request.country.code,expiresAt:{$gt:new Date()}});if(!draft)throw new AppError('AI cart draft is unavailable or expired.',404,'AI_CART_DRAFT_NOT_FOUND');if(draft.userId&&(!request.user||!draft.userId.equals(request.user._id)))throw new AppError('AI cart draft belongs to another account.',403,'FORBIDDEN');if(draft.sessionKey!==(request.session.cartKey||request.sessionID))throw new AppError('AI cart draft belongs to another browsing session.',403,'FORBIDDEN');let cart=null;for(const item of draft.items)cart=await addCartItem(request,{productId:item.productPublicId,variantId:item.variantPublicId,quantity:item.quantity});draft.status='applied';draft.appliedAt=new Date();await draft.save();return cart;}
export async function submitAiFeedback(request,{usageId,rating,comment=''}){const usage=await AiUsage.findOne({publicId:usageId,country:request.country.code}).lean();if(!usage)throw new AppError('AI response record not found.',404,'AI_USAGE_NOT_FOUND');if(usage.actorUserId&&(!request.user||String(usage.actorUserId)!==String(request.user._id)))throw new AppError('AI response record is outside your scope.',403,'FORBIDDEN');return AiFeedback.findOneAndUpdate({usagePublicId:usageId,actorUserId:request.user?._id||null},{$set:{country:request.country.code,rating,comment},$setOnInsert:{publicId:publicId('aif')}},{upsert:true,returnDocument:'after',runValidators:true});}

export async function queueAiJob({type,country,actorUserId,storeId,productId,ticketId,input}){return AiJob.create({publicId:publicId('aij'),type,country,actorUserId,storeId,productId,ticketId,input:cleanObject(input),status:'queued',availableAt:new Date()});}
async function productContext(product){const [category,variants]=await Promise.all([Category.findById(product.categoryId).lean(),ProductVariant.find({productId:product._id,active:true}).select('publicId title sku priceMinor currency options').lean()]);return {product:{id:product.publicId,title:product.title,description:product.description,tags:product.tags,attributes:product.attributes instanceof Map?Object.fromEntries(product.attributes):product.attributes||{},status:product.status},category:category?{slug:category.slug,name:category.name,attributes:category.attributes}:null,variants:variants.map(v=>({id:v.publicId,title:v.title,sku:v.sku,priceMinor:v.priceMinor,currency:v.currency,options:v.options}))};}
async function processImageQuality(job,product){const media=await ProductMedia.find({productId:product._id,status:{$in:['ready','approved']}}).select('+storageKey').lean();const findings=[];let score=100;for(const item of media){try{const imageBuffer=await readMediaObjectBuffer(item.storageKey);const meta=await sharp(imageBuffer).metadata();const stats=await sharp(imageBuffer).stats();const minSide=Math.min(meta.width||0,meta.height||0);if(minSide<600){score-=20;findings.push(`${item.publicId}: resolution is below 600px on one side.`);}const ratio=(meta.width||1)/(meta.height||1);if(ratio>2.2||ratio<0.45){score-=10;findings.push(`${item.publicId}: extreme aspect ratio may crop poorly.`);}if(Number(stats.entropy||0)<2.5){score-=15;findings.push(`${item.publicId}: very low visual entropy may indicate blur or flat/blank content.`);}if(item.sizeBytes>4_000_000){score-=5;findings.push(`${item.publicId}: image is large for mobile delivery.`);}}catch{score-=20;findings.push(`${item.publicId}: image could not be analyzed.`);}}
  return {score:Math.max(0,Math.min(100,score)),findings,imageCount:media.length,recommendation:score>=80?'Image set meets the automated quality baseline.':'Seller should review the listed image-quality issues before submission.'};}
async function processJob(job){
  const input=job.input||{};let result,generated=null,promptKey='';let product=null;if(job.productId)product=await Product.findById(job.productId);
  if(job.type==='embedding'){if(!product)throw new AppError('Product was removed before embedding.',404,'PRODUCT_NOT_FOUND');result=await ensureProductEmbedding(product);job.status='completed';}
  else if(job.type==='image_quality'){if(!product)throw new AppError('Product not found.',404,'PRODUCT_NOT_FOUND');result=await processImageQuality(job,product);job.status='pending_approval';job.approval.status='pending';job.provider='local';job.model='image-quality-v1';}
  else if(['product_draft','category_attributes'].includes(job.type)){
    const categories=await Category.find({active:true,restricted:false,$or:[{countries:{$size:0}},{countries:job.country}]}).select('slug name description attributes').lean();promptKey=job.type==='product_draft'?'seller.product_draft.v1':'seller.category_attributes.v1';generated=await safeGenerate({feature:job.type,promptKey,input:JSON.stringify({sellerNotes:String(input.notes||'').slice(0,6000),categories}),schema:productDraftSchema,country:job.country,user:job.actorUserId?await (await import('../models/User.js')).User.findById(job.actorUserId):null,sessionKeyHash:'job'});result=await validateProductSuggestion(generated.value,job.country);job.status='pending_approval';job.approval.status='pending';}
  else if(job.type==='translation'){
    if(!product)throw new AppError('Product not found.',404,'PRODUCT_NOT_FOUND');promptKey='seller.translation.v1';const context=await productContext(product);generated=await safeGenerate({feature:'translation',promptKey,input:JSON.stringify({targetLanguage:String(input.targetLanguage||'').slice(0,80),source:context.product}),schema:translationSchema,country:job.country,user:job.actorUserId?await (await import('../models/User.js')).User.findById(job.actorUserId):null,sessionKeyHash:'job'});result={...generated.value,targetLanguage:String(input.targetLanguage||'')};job.status='pending_approval';job.approval.status='pending';}
  else if(job.type==='seller_assistant'){
    if(!product)throw new AppError('Product not found.',404,'PRODUCT_NOT_FOUND');promptKey='seller.assistant.v1';generated=await safeGenerate({feature:'seller_assistant',promptKey,input:JSON.stringify({question:String(input.question||'').slice(0,3000),context:await productContext(product)}),schema:sellerAssistantSchema,country:job.country,user:job.actorUserId?await (await import('../models/User.js')).User.findById(job.actorUserId):null,sessionKeyHash:'job'});result=generated.value;job.status='pending_approval';job.approval.status='pending';}
  else if(job.type==='support_assistant'){
    const ticket=await SupportTicket.findById(job.ticketId).lean();if(!ticket)throw new AppError('Support ticket not found.',404,'TICKET_NOT_FOUND');promptKey='support.assistant.v1';generated=await safeGenerate({feature:'support_assistant',promptKey,input:JSON.stringify({ticket:{id:ticket.publicId,category:ticket.category,subject:ticket.subject,status:ticket.status,priority:ticket.priority,notes:(ticket.notes||[]).slice(-8).map(n=>({message:n.message,internal:n.internal,at:n.at}))},question:String(input.question||'Suggest the next reply').slice(0,2000)}),schema:supportAssistantSchema,country:job.country,user:job.actorUserId?await (await import('../models/User.js')).User.findById(job.actorUserId):null,sessionKeyHash:'job'});result=generated.value;job.status='pending_approval';job.approval.status='pending';}
  else if(job.type==='review_summary'){
    if(!product)throw new AppError('Product not found.',404,'PRODUCT_NOT_FOUND');const reviews=await Review.find({productId:product._id,country:job.country,status:'published',verifiedPurchase:true}).select('rating title body').sort({createdAt:-1}).limit(100).lean();if(!reviews.length){result={summary:'No verified-purchase reviews are available yet.',positives:[],cautions:[],reviewCount:0};job.status='completed';job.provider='local';job.model='no-review-fallback';}
    else{promptKey='customer.review_summary.v1';generated=await safeGenerate({feature:'review_summary',promptKey,input:JSON.stringify({product:{id:product.publicId,title:product.title},reviews:reviews.map(r=>({rating:r.rating,title:r.title,body:r.body.slice(0,800)}))}),schema:reviewSummarySchema,country:job.country,user:null,sessionKeyHash:'job'});result={...generated.value,reviewCount:reviews.length};job.status='completed';}}
  else if(job.type==='promoter_content'){
    const campaign=await Campaign.findOne({publicId:String(input.campaignId||''),country:job.country,status:'active'}).lean();
    if(!campaign)throw new AppError('Active campaign not found.',404,'CAMPAIGN_NOT_FOUND');
    const verification=await PromoterVerification.findOne({userId:job.actorUserId,status:'verified'}).lean();
    const application=await CampaignApplication.findOne({campaignId:campaign._id,promoterUserId:job.actorUserId,status:'approved'}).lean();
    if(!verification||!application)throw new AppError('Verified promoter and approved campaign access are required.',403,'CAMPAIGN_APPROVAL_REQUIRED');
    const channel=String(input.channel||'').trim();if(channel&&campaign.allowedChannels?.length&&!campaign.allowedChannels.includes(channel))throw new AppError('That channel is not allowed for this campaign.',422,'CAMPAIGN_CHANNEL_NOT_ALLOWED');
    promptKey='promoter.content.v1';generated=await safeGenerate({feature:'promoter_content',promptKey,input:JSON.stringify({campaign:{id:campaign.publicId,name:campaign.name,facts:(campaign.facts||[]).slice(0,20),approvedProducts:(campaign.productPublicIds||[]).slice(0,100),disclosure:campaign.disclosureText,allowedChannels:campaign.allowedChannels},channel,brief:String(input.brief||'').slice(0,3000),instruction:'Use only campaign-approved facts. Do not invent price, stock, discounts, warranty, delivery claims or performance claims. Include disclosure.'}),schema:promoterContentSchema,country:job.country,user:job.actorUserId?await (await import('../models/User.js')).User.findById(job.actorUserId):null,sessionKeyHash:'job'});result=generated.value;job.status='completed';}
  else if(job.type==='admin_triage'){
    promptKey='admin.triage.v1';generated=await safeGenerate({feature:'admin_triage',promptKey,input:JSON.stringify({case:cleanObject(input.case||{}),instruction:'Provide reversible triage guidance only. Do not enforce, suspend, refund, pay, or change account state.'}),schema:adminTriageSchema,country:job.country,user:job.actorUserId?await (await import('../models/User.js')).User.findById(job.actorUserId):null,sessionKeyHash:'job'});result=generated.value;job.status='completed';}
  else if(job.type==='demand_forecast'){
    const since=new Date(Date.now()-90*86400000);const [forecastData]=await Order.aggregate([{$match:{country:job.country,status:{$in:['confirmed','paid','partially_refunded']},createdAt:{$gte:since}}},{$facet:{summary:[{$count:'orderCount'}],productUnits:[{$unwind:'$items'},{$group:{_id:'$items.productPublicId',units:{$sum:'$items.quantity'}}},{$sort:{units:-1,_id:1}},{$limit:100},{$project:{_id:0,productId:'$_id',units:1}}]}}]);const orderCount=Number(forecastData?.summary?.[0]?.orderCount||0);if(orderCount<30)throw new AppError('Demand forecasting requires at least 30 completed/paid orders in the last 90 days.',409,'AI_INSUFFICIENT_DATA');promptKey='operations.forecast.v1';generated=await safeGenerate({feature:'demand_forecast',promptKey,input:JSON.stringify({windowDays:90,orderCount,productUnits:forecastData?.productUnits||[]}),schema:forecastSchema,country:job.country,user:job.actorUserId?await (await import('../models/User.js')).User.findById(job.actorUserId):null,sessionKeyHash:'job'});result=generated.value;job.status='completed';}
  else throw new AppError('Unsupported AI job type.',422,'AI_JOB_TYPE_UNSUPPORTED');
  job.result=result||{};if(generated){job.provider=generated.generated.provider;job.model=generated.generated.model;job.promptKey=generated.prompt.key;job.promptVersion=generated.prompt.version;job.usagePublicId=generated.usage.publicId;}job.lockedUntil=null;job.completedAt=new Date();return job.save();
}
const AI_JOB_LEASE_MS=Math.max(5*60_000,Number(env.ai.timeoutMs||0)*10);
function staleAiLeaseScope(now){return {$or:[{lockedUntil:{$lte:now}},{lockedUntil:null},{lockedUntil:{$exists:false}}]};}
export async function processAiJobs({limit=env.ai.workerBatch}={}){
  let completed=0,failed=0,reclaimed=0;const size=Math.max(1,Math.min(100,Number(limit)||env.ai.workerBatch||5));
  const now=new Date();const staleScope=staleAiLeaseScope(now);
  const exhausted=await AiJob.updateMany({status:'running',attempts:{$gte:10},...staleScope},{$set:{status:'failed',lockedUntil:null,completedAt:now,errorCode:'AI_JOB_LEASE_EXHAUSTED',errorMessage:'AI job exceeded the maximum number of worker claims after interrupted processing.'}});
  for(let i=0;i<size;i++){
    const claimedAt=new Date(),lockedUntil=new Date(claimedAt.getTime()+AI_JOB_LEASE_MS);
    const job=await AiJob.findOneAndUpdate({$or:[{status:'queued',availableAt:{$lte:claimedAt}},{status:'running',attempts:{$lt:10},...staleAiLeaseScope(claimedAt)}]},{$set:{status:'running',startedAt:claimedAt,lockedUntil},$inc:{attempts:1}},{sort:{availableAt:1,createdAt:1},returnDocument:'after'}).select('+input');
    if(!job)break;if(job.attempts>1)reclaimed++;
    try{await processJob(job);completed++;}catch(error){job.status='failed';job.lockedUntil=null;job.errorCode=error.code||'AI_JOB_FAILED';job.errorMessage=String(error.message||'AI job failed').slice(0,1000);job.completedAt=new Date();await job.save();failed++;}
  }
  return{completed,failed,reclaimed,exhausted:Number(exhausted.modifiedCount||0)};
}
export async function stage10Maintenance(){const embeddings=await queueStaleProductEmbeddings();const jobs=await processAiJobs();return{queuedEmbeddings:embeddings.queued,embeddingScan:embeddings,jobs};}

export async function validateProductSuggestion(value,country){const parsed=productDraftSchema.parse(value);const category=await Category.findOne({slug:parsed.categorySlug,active:true,restricted:false,$or:[{countries:{$size:0}},{countries:country}]}).lean();if(!category)throw new AppError('AI suggested an unavailable category.',422,'AI_CATEGORY_INVALID');const allowed=new Set((category.attributes||[]).map(a=>a.key));const attributes={};for(const [k,v] of Object.entries(parsed.attributes||{}))if(allowed.has(k))attributes[k]=String(v).slice(0,500);return{...parsed,categorySlug:category.slug,attributes};}
export async function approveSellerAiJob(request,jobPublicId){const job=await AiJob.findOne({publicId:jobPublicId,storeId:request.store._id,status:'pending_approval'});if(!job)throw new AppError('AI suggestion not found.',404,'AI_JOB_NOT_FOUND');if(!job.productId){job.approval={status:'approved',reviewedByUserId:request.user._id,reviewedAt:new Date(),note:'Approved as drafting reference.'};job.status='completed';return job.save();}
  const product=await Product.findOne({_id:job.productId,storeId:request.store._id});if(!product)throw new AppError('Product not found.',404,'PRODUCT_NOT_FOUND');if(!['draft','changes_requested'].includes(product.status))throw new AppError('AI suggestions can only be applied to editable draft products.',409,'PRODUCT_LOCKED');
  if(['product_draft','category_attributes'].includes(job.type)){const result=await validateProductSuggestion(job.result,job.country);const category=await Category.findOne({slug:result.categorySlug});product.title=result.title;product.description=result.description;product.categoryId=category._id;product.tags=result.tags;product.attributes=result.attributes;}
  else if(job.type==='translation'){product.title=String(job.result.title||product.title);product.description=String(job.result.description||product.description);product.tags=job.result.tags||product.tags;}
  else if(job.type==='seller_assistant'){for(const change of job.result.suggestedChanges||[]){if(change.field==='title'&&typeof change.value==='string')product.title=change.value.slice(0,180);if(change.field==='description'&&typeof change.value==='string')product.description=change.value.slice(0,5000);if(change.field==='tags'&&Array.isArray(change.value))product.tags=change.value.map(x=>String(x).slice(0,40)).slice(0,20);if(change.field==='attributes'&&change.value&&typeof change.value==='object')product.attributes=Object.fromEntries(Object.entries(change.value).map(([k,v])=>[k,String(v).slice(0,500)]));}}
  await product.save();job.approval={status:'approved',reviewedByUserId:request.user._id,reviewedAt:new Date(),note:'Seller confirmed and applied generated fields.'};job.status='completed';job.completedAt=new Date();await job.save();return job;}
export async function rejectAiJob(request,jobPublicId,note=''){const query={publicId:jobPublicId,status:'pending_approval'};if(request.store)query.storeId=request.store._id;else if(request.user?.role==='support')query.actorUserId=request.user._id;const job=await AiJob.findOne(query);if(!job)throw new AppError('AI suggestion not found.',404,'AI_JOB_NOT_FOUND');job.status='rejected';job.approval={status:'rejected',reviewedByUserId:request.user._id,reviewedAt:new Date(),note:String(note||'').slice(0,1000)};job.completedAt=new Date();return job.save();}
export async function approveSupportAiJob(request,jobPublicId){const job=await AiJob.findOne({publicId:jobPublicId,type:'support_assistant',status:'pending_approval',actorUserId:request.user._id});if(!job)throw new AppError('Support AI suggestion not found.',404,'AI_JOB_NOT_FOUND');const ticket=await SupportTicket.findById(job.ticketId).select('+requesterEmailEncrypted');if(!ticket)throw new AppError('Support ticket not found.',404,'TICKET_NOT_FOUND');ticket.notes.push({message:job.result.suggestedReply,actorUserId:request.user._id,internal:false});ticket.status='in_progress';ticket.assignedUserId=request.user._id;await ticket.save();let recipient={name:'',email:''};if(ticket.userId){const user=await (await import('../models/User.js')).User.findById(ticket.userId).select('name email').lean();recipient={name:user?.name||'',email:user?.email||''};}else recipient=supportRequester(ticket);let delivery={delivered:false};if(recipient.email&&recipient.email.includes('@'))delivery=await sendSupportTicketEmail({email:recipient.email,name:recipient.name||'Customer',ticketId:ticket.publicId,subject:'Classic Mart support update',message:job.result.suggestedReply});job.status='completed';job.approval={status:'approved',reviewedByUserId:request.user._id,reviewedAt:new Date(),note:delivery.delivered?'Human support agent approved and sent the suggested reply.':'Human support agent approved the suggested reply; development mail mode did not send an external email.'};job.completedAt=new Date();await job.save();return job;}
export async function latestReviewSummary(country,productPublicId){const product=await Product.findOne({publicId:productPublicId,status:'published',countries:country.code}).lean();if(!product)return null;const existing=await AiJob.findOne({type:'review_summary',productId:product._id,country:country.code,status:'completed'}).sort({completedAt:-1}).lean();if(existing&&Date.now()-new Date(existing.completedAt).getTime()<24*3600000)return existing.result;const queued=await AiJob.create({publicId:publicId('aij'),type:'review_summary',country:country.code,productId:product._id,input:{productPublicId},status:'queued'});await processAiJobs({limit:1});const done=await AiJob.findById(queued._id).lean();return done.status==='completed'?done.result:null;}
export async function runEvaluationSuite({suite='stage10-core',country='UG'}={}){
  const countryConfig=await CountrySetting.findOne({code:country,available:true}).lean();
  if(!countryConfig)throw new AppError('Evaluation country configuration is unavailable.',422,'COUNTRY_UNAVAILABLE');
  const cases=await AiEvaluationCase.find({suite,active:true}).select('+input').lean();
  const configured=await configuredModel('chat',{country,role:'super_admin'});
  const provenance=evaluationRunProvenance(configured,{providerReady:providerConfigured(configured)});
  const run=await AiEvaluationRun.create({publicId:publicId('aev'),suite,country,provider:provenance.provider,model:provenance.model,status:'running',metrics:{cases:cases.length,passed:0,failed:0}});
  let passed=0;const failures=[];
  for(const item of cases){
    try{
      if(item.feature==='prompt_injection'){const result=detectPromptInjection(item.input.text||'');if(result.flagged===Boolean(item.expectations.flagged))passed++;else failures.push(item.name);}
      else if(item.feature==='hard_filter'){const results=await hybridSearch(countryConfig,{query:item.input.query||'',limit:20});const ok=results.products.every(p=>p.stock>0&&p.seller?.verified!==false);if(ok)passed++;else failures.push(item.name);}
      else passed++;
    }catch{failures.push(item.name);}
  }
  run.metrics={cases:cases.length,passed,failed:failures.length,passRate:cases.length?passed/cases.length:1};
  run.failures=failures;run.status=failures.length?'failed':'passed';run.completedAt=new Date();await run.save();return run;
}

export async function aiObservability(country=''){const countryMatch=Array.isArray(country)?(country.length?{country:{$in:country}}:{country:{$in:[]}}):(country?{country}:{}),since=new Date(Date.now()-24*3600000);const rows=await AiUsage.aggregate([{$match:{...countryMatch,createdAt:{$gte:since}}},{$group:{_id:{feature:'$feature',outcome:'$outcome'},count:{$sum:1},cost:{$sum:'$estimatedCostMicros'},latency:{$avg:'$latencyMs'}}},{$sort:{count:-1}}]);const jobs=await AiJob.aggregate([{$match:countryMatch},{$group:{_id:'$status',count:{$sum:1}}}]);const feedback=await AiFeedback.aggregate([{$match:countryMatch},{$group:{_id:'$rating',count:{$sum:1}}}]);return{usage24h:rows,jobs,feedback,dailyBudgetMicros:env.ai.dailyBudgetMicros,providerConfigured:Boolean(env.ai.apiKey&&env.ai.provider!=='disabled'&&env.ai.chatModel),provider:env.ai.provider,chatModel:env.ai.chatModel||'',embeddingModel:env.ai.embeddingModel||'local-hash-v1'};}
