import mongoose from 'mongoose';
const {Schema}=mongoose;
const addressSchema=new Schema({companyName:{type:String,required:true,maxlength:180},contactName:{type:String,required:true,maxlength:120},email:{type:String,required:true,maxlength:254},phone:{type:String,required:true,maxlength:32},address:{type:String,required:true,maxlength:240},city:{type:String,required:true,maxlength:120},country:{type:String,required:true,uppercase:true,minlength:2,maxlength:2},taxIdMasked:{type:String,maxlength:140,default:''}},{_id:false});
const lineSchema=new Schema({productPublicId:{type:String,required:true},variantPublicId:{type:String,required:true},sku:{type:String,required:true,maxlength:64},title:{type:String,required:true,maxlength:220},variantTitle:{type:String,required:true,maxlength:120},quantity:{type:Number,required:true,min:1},unitMinor:{type:Number,required:true,min:0},lineMinor:{type:Number,required:true,min:0}},{_id:false});
const eventSchema=new Schema({type:{type:String,required:true,maxlength:80},message:{type:String,required:true,maxlength:500},actorUserId:{type:Schema.Types.ObjectId,ref:'User'},at:{type:Date,default:Date.now}},{_id:false});
const schema=new Schema({
 publicId:{type:String,required:true,unique:true,immutable:true,index:true},invoiceNumber:{type:String,required:true,unique:true,immutable:true,index:true},organizationId:{type:Schema.Types.ObjectId,ref:'BusinessOrganization',required:true,index:true},purchaseOrderId:{type:Schema.Types.ObjectId,ref:'PurchaseOrder',required:true,unique:true,index:true},orderId:{type:Schema.Types.ObjectId,ref:'Order',required:true,unique:true,index:true},orderPublicId:{type:String,required:true,index:true},storeId:{type:Schema.Types.ObjectId,ref:'Store',required:true,index:true},storePublicId:{type:String,required:true,index:true},country:{type:String,required:true,uppercase:true,index:true},currency:{type:String,required:true,uppercase:true},paymentTerms:{type:String,enum:['immediate','credit'],required:true,index:true},termsDays:{type:Number,min:0,max:120,default:0},status:{type:String,enum:['awaiting_payment','credit_pending_delivery','open','paid','overdue','void','refunded'],required:true,index:true},subtotalMinor:{type:Number,required:true,min:0},taxBps:{type:Number,min:0,max:10000,default:0},taxPolicyVersion:{type:String,maxlength:40,default:'legacy-zero-tax'},taxMinor:{type:Number,required:true,min:0,default:0},shippingMinor:{type:Number,required:true,min:0,default:0},totalMinor:{type:Number,required:true,min:0},paidMinor:{type:Number,required:true,min:0,default:0},lines:{type:[lineSchema],required:true},billTo:{type:addressSchema,required:true},shipTo:{type:addressSchema,required:true},issuedAt:Date,deliveredAt:Date,dueAt:{type:Date,index:true},paidAt:Date,paymentIntentPublicId:{type:String,maxlength:100,default:''},timeline:{type:[eventSchema],default:[]},
},{timestamps:true,optimisticConcurrency:true});
schema.index({organizationId:1,status:1,dueAt:1});schema.index({storeId:1,status:1,createdAt:-1});
export const BusinessInvoice=mongoose.model('BusinessInvoice',schema);
