import mongoose from 'mongoose';
const { Schema } = mongoose;
const itemSchema = new Schema({orderLineId:{type:String,required:true,maxlength:100},productId:{type:Schema.Types.ObjectId,ref:'Product',required:true},variantId:{type:Schema.Types.ObjectId,ref:'ProductVariant',required:true},storeId:{type:Schema.Types.ObjectId,ref:'Store'},storePublicId:{type:String,maxlength:100,default:''},productPublicId:{type:String,required:true},variantPublicId:{type:String,required:true},sku:{type:String,maxlength:64,default:''},title:{type:String,required:true,maxlength:220},variantTitle:{type:String,maxlength:120,default:''},quantity:{type:Number,required:true,min:1,max:99},unitPriceMinor:{type:Number,required:true,min:0},requestedRefundMinor:{type:Number,required:true,min:0},warehouseTaskPublicId:{type:String,maxlength:100,default:''},warehouseInspectionStatus:{type:String,enum:['','pending','completed'],default:''},stockDisposition:{type:String,enum:['','good','damaged','quarantine'],default:''},inspectedQuantity:{type:Number,min:0,max:99,default:0},warehouseInspectedByUserId:{type:Schema.Types.ObjectId,ref:'User'},warehouseInspectedAt:Date},{_id:false});
const eventSchema = new Schema({type:{type:String,required:true,maxlength:80},message:{type:String,required:true,maxlength:300},actorUserId:{type:Schema.Types.ObjectId,ref:'User'},at:{type:Date,default:Date.now}},{_id:false});
const inspectionSchema = new Schema({condition:{type:String,enum:['unopened','good','damaged','wrong_item','counterfeit_suspected','missing_parts']},notes:{type:String,maxlength:1000,default:''},inspectedByUserId:{type:Schema.Types.ObjectId,ref:'User'},inspectedAt:Date},{_id:false});
const schema = new Schema({
 publicId:{type:String,required:true,unique:true,immutable:true,index:true},orderId:{type:Schema.Types.ObjectId,ref:'Order',required:true,index:true},orderPublicId:{type:String,required:true,index:true},userId:{type:Schema.Types.ObjectId,ref:'User',required:true,index:true},country:{type:String,required:true,uppercase:true,minlength:2,maxlength:2,index:true},
 status:{type:String,enum:['requested','approved','rejected','awaiting_return','received','inspected','refund_pending','refund_processing','refunded','exchange_pending','exchanged','closed'],default:'requested',index:true},reason:{type:String,enum:['damaged','wrong_item','not_as_described','counterfeit_suspected','missing_parts','changed_mind','other'],required:true},details:{type:String,required:true,maxlength:2000},resolution:{type:String,enum:['refund','exchange'],required:true},items:{type:[itemSchema],required:true,validate:v=>v.length>0},
 returnMethod:{type:String,enum:['dropoff','pickup'],default:'dropoff'},dropoffPointPublicId:{type:String,maxlength:100,default:''},evidenceDocumentIds:{type:[Schema.Types.ObjectId],ref:'EvidenceDocument',default:[]},eligibleUntil:{type:Date,required:true},policyVersion:{type:String,maxlength:40,required:true},inspection:{type:inspectionSchema},refundPublicId:{type:String,index:true},returnShipmentPublicId:{type:String,index:true,default:''},replacementOrderPublicId:{type:String,index:true,default:''},timeline:{type:[eventSchema],default:[]},decidedByUserId:{type:Schema.Types.ObjectId,ref:'User'},decidedAt:Date
},{timestamps:true,optimisticConcurrency:true});
schema.index({userId:1,createdAt:-1});schema.index({country:1,status:1,createdAt:-1});schema.index({orderId:1,status:1});
export const ReturnRequest=mongoose.model('ReturnRequest',schema);
