import mongoose from 'mongoose';
const { Schema }=mongoose;
const assignmentSchema=new Schema({userId:{type:Schema.Types.ObjectId,ref:'User'},action:{type:String,enum:['claimed','released','completed'],required:true},at:{type:Date,default:Date.now}},{_id:false});
const warehouseTaskSchema=new Schema({
 publicId:{type:String,required:true,unique:true,immutable:true,index:true},sourceKey:{type:String,trim:true,maxlength:180,default:''},warehouseId:{type:Schema.Types.ObjectId,ref:'Warehouse',required:true,index:true},storeId:{type:Schema.Types.ObjectId,ref:'Store',required:true,index:true},orderId:{type:Schema.Types.ObjectId,ref:'Order',index:true},shipmentId:{type:Schema.Types.ObjectId,ref:'Shipment',index:true},parcelId:{type:Schema.Types.ObjectId,ref:'Parcel',index:true},returnRequestId:{type:Schema.Types.ObjectId,ref:'ReturnRequest',index:true},returnOrderLineId:{type:String,maxlength:100,default:'',index:true},stockItemId:{type:Schema.Types.ObjectId,ref:'StockItem',index:true},variantId:{type:Schema.Types.ObjectId,ref:'ProductVariant',index:true},destinationWarehouseId:{type:Schema.Types.ObjectId,ref:'Warehouse',index:true},quantity:{type:Number,min:0,max:2_000_000_000,default:0},binCode:{type:String,trim:true,maxlength:80,default:''},disposition:{type:String,enum:['','good','damaged','quarantine'],default:''},
 type:{type:String,enum:['receive','put_away','pick','pack','dispatch','cycle_count','transfer','return_inspection'],required:true,index:true},status:{type:String,enum:['open','in_progress','completed','cancelled'],default:'open',index:true},assignedUserId:{type:Schema.Types.ObjectId,ref:'User',index:true},wavePublicId:{type:String,maxlength:100,default:'',index:true},claimedAt:Date,dueAt:{type:Date,index:true},assignmentHistory:{type:[assignmentSchema],default:[]},reference:{type:String,maxlength:120,default:''},notes:{type:String,maxlength:500,default:''},result:{type:Schema.Types.Mixed,default:{}},completedAt:Date,
},{timestamps:true,optimisticConcurrency:true});
warehouseTaskSchema.index({warehouseId:1,status:1,createdAt:-1});
warehouseTaskSchema.index({warehouseId:1,status:1,dueAt:1});
warehouseTaskSchema.index({sourceKey:1},{unique:true,partialFilterExpression:{sourceKey:{$type:'string',$gt:''}}});
export const WarehouseTask=mongoose.model('WarehouseTask',warehouseTaskSchema);
